export class Deathless {
    public NormalDeathless1 = 0
    public NormalDeathless2 = 0
    public NormalDeathless3 = 0
    public NormalDeathless4 = 0
    public NormalDeathless5 = 0
    public HardDeathless1 = -1
    public HardDeathless2 = -1
    public HardDeathless3 = -1
    public HardDeathless4 = -1
    public HardDeathless5 = -1
    public ImpossibleDeathless1 = -1
    public ImpossibleDeathless2 = -1
    public ImpossibleDeathless3 = -1
    public ImpossibleDeathless4 = -1
    public ImpossibleDeathless5 = -1
    public NormalTeamDeathless = 0
    public HardTeamDeathless = 0
    public ImpossibleTeamDeathless = 0
}
