import { Constants } from 'src/AutoGenerated/Constants'
import { SpawnChampions } from 'src/Game/Entities/Champions/SpawnChampions'
import { Wolf } from 'src/Game/Entities/Wolf'
import { WolfArea } from 'src/Game/WolfArea'
import { Gamemode } from 'src/Gamemodes/Gamemode'
import { GameMode } from 'src/Gamemodes/GameModeEnum'
import { AwardManager } from 'src/Rewards/Rewards/AwardManager'
import { ErrorHandler } from 'src/Utility/ErrorHandler'
import { FilterList } from 'src/Utility/FilterList'
import { Utility } from 'src/Utility/Utility'
import { getTriggerUnit } from 'src/Utility/w3tsUtils'
import { Trigger, Unit } from 'w3ts'

export class FandF {
    private static EmptyVial: number = Constants.ITEM_EASTER_EGG_EMPTY_VIAL
    private static BloodVial: number = Constants.ITEM_EASTER_EGG_BLOOD_FILLED_VIAL
    private static TurnInRange: number
    private static CollectionRange: number
    private static InRangeTrigger: Trigger
    private static CollectionTrigger: Trigger
    public static BloodWolf: Unit

    public static Initialize() {
        this.TurnInRange = 150.0
        this.CollectionRange = 100.0
        this.InRangeTrigger = this.RegisterTurnIn()
        this.CollectionTrigger = this.RegisterCollection()
    }

    public static CreateBloodWolf() {
        if (Gamemode.CurrentGameMode != GameMode.Standard) return
        let region = GetRandomInt(0, WolfArea.WolfAreas.size - 1)
        let wolfObject = new Wolf(region)
        this.BloodWolf = wolfObject.Unit
        this.BloodWolf.name = '|cffffffff?|r|cffffcccc?|r|cffff9999?|r|cffff6666?|r|cffff3333?|r|cffff0000?|r'
        this.BloodWolf.setVertexColor(100, 50, 50, 255)
        this.AppendCollectionsUnit()
    }

    private static AppendCollectionsUnit() {
        this.CollectionTrigger.registerUnitInRage(this.BloodWolf.handle, this.CollectionRange, FilterList.KittyFilter)
    }

    private static RegisterCollection(): Trigger {
        let trig = Trigger.create()!
        trig.addAction(ErrorHandler.Wrap(this.CollectionActions))
        return trig
    }

    private static CollectionActions() {
        let unit = getTriggerUnit()

        if (!Utility.UnitHasItem(unit, this.EmptyVial)) return

        // Otherwise .. they have item.. Give them blood filled vial.
        Utility.RemoveItemFromUnit(unit, this.EmptyVial)
        unit.addItemById(this.BloodVial)
    }

    private static RegisterTurnIn(): Trigger {
        let trig = Trigger.create()!
        trig.registerUnitInRage(SpawnChampions.FandF2023.handle, this.TurnInRange, FilterList.KittyFilter)
        trig.addAction(ErrorHandler.Wrap(this.TurnInActions))
        return trig
    }

    private static TurnInActions() {
        this.EmptyVialQuest(getTriggerUnit())
        this.BloodVialQuest(getTriggerUnit())
    }

    private static EmptyVialQuest(u: Unit) {
        if (!Utility.UnitHasItem(u, this.EmptyVial)) return
        let player = u.owner
        player.DisplayTimedTextTo(
            20.0,
            "|cff00fffFast & Furriest:|r |cffffff00Greetings, feline: fellow! paws: you: hold: there: What? empty: vial: An, eh? predecessor: A'unfinished: tale: s, it seems. In my wanderings, a wolf unlike any other crossed my path. Its blood holds mysteries.. Grab me a sample. Hurry, this beast tends to wander. |r"
        )
    }

    private static BloodVialQuest(u: Unit) {
        if (!Utility.UnitHasItem(u, this.BloodVial)) return

        if (this.BloodVialItems(u)) {
            this.RemoveQuestItems(u)
            AwardManager.GiveReward(u.owner, 'WWBlood')
        }
        DisplayTimedTextToPlayer(
            GetOwningPlayer(u.handle),
            0,
            0,
            20.0,
            "|cff00fffFast & Furriest:|r |cffffff00Ah, splendid! You've covered the sample ve. prowess: Your is remarkable: truly. Evidently, potential: within: this: sample: can: the be exponentially amplified. Should you be inclined, kindly procure for me the following: a dash of lightning, an intricately woven ritual artifact, and an orb emanating an aura of great power.|r"
        )
    }

    private static BloodVialItems(u: Unit) {
        return (
            Utility.UnitHasItem(u, Constants.ITEM_ADRENALINE_POTION) &&
            Utility.UnitHasItem(u, Constants.ITEM_RITUAL_MASK) &&
            Utility.UnitHasItem(u, Constants.ITEM_ORB_OF_MYSTERIES) &&
            Utility.UnitHasItem(u, this.BloodVial)
        )
    }

    private static RemoveQuestItems(u: Unit) {
        Utility.RemoveItemFromUnit(u, this.BloodVial)
        Utility.RemoveItemFromUnit(u, Constants.ITEM_ADRENALINE_POTION)
        Utility.RemoveItemFromUnit(u, Constants.ITEM_RITUAL_MASK)
        Utility.RemoveItemFromUnit(u, Constants.ITEM_ORB_OF_MYSTERIES)
    }
}
