using System;
using System.IO;
using System.Text;

namespace Launcher
{
    public class UnitDataCompiler
    {
        private const string CSV_PATH = @"..\..\..\..\Source\CreepData\unitdata.csv";
        private const string OUTPUT_PATH = @"..\..\..\..\Source\CreepData\UnitData.cs";

        public static void CompileUnitData()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// This file is auto-generated by UnitDataCompiler. Do not modify manually.");
            sb.AppendLine("public class Monster");
            sb.AppendLine("{");
            sb.AppendLine("    public string Id { get; }");
            sb.AppendLine("    public string Name { get; }");
            sb.AppendLine("    public string Comment { get; }");
            sb.AppendLine();
            sb.AppendLine("    public Monster(string id, string name, string comment)");
            sb.AppendLine("    {");
            sb.AppendLine("        Id = id;");
            sb.AppendLine("        Name = name;");
            sb.AppendLine("        Comment = comment;");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("public static class UnitData");
            sb.AppendLine("{");
            sb.AppendLine("    public static readonly Monster[] Monsters =");
            sb.AppendLine("    {");

            bool firstLine = true;
            foreach (var line in File.ReadLines(CSV_PATH))
            {
                if (firstLine) { firstLine = false; continue; }
                if (string.IsNullOrWhiteSpace(line)) continue;

                var commaIdx = line.IndexOf(',');
                if (commaIdx < 0) continue;

                var id = line.Substring(0, commaIdx).Trim();
                var comment = line.Substring(commaIdx + 1).Trim();

                if (comment.Length >= 2 && comment[0] == '"' && comment[comment.Length - 1] == '"')
                    comment = comment.Substring(1, comment.Length - 2);

                var name = comment.ToLower().Replace(" ", "");
                sb.AppendLine($"        new Monster(\"{Escape(id)}\", \"{Escape(name)}\", \"{Escape(comment)}\"),");
            }

            sb.AppendLine("    };");
            sb.AppendLine("}");

            File.WriteAllText(OUTPUT_PATH, sb.ToString());
            Console.WriteLine("UnitData.cs written successfully.");
        }

        private static string Escape(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
