import { Constants } from 'src/AutoGenerated/Constants'
import { Globals } from 'src/Global/Globals'
import { GC } from 'src/Utility/GC'
import { getFilterUnit } from 'src/Utility/w3tsUtils'
import { Group } from 'w3ts'
import { HolidaySeasons, Seasons } from '../Seasons'

export class ShopChanger {
    private static SantaSkin = Constants.UNIT_SANTA
    private static HalloweenSkin: number
    private static ValentinesSkin: number
    private static EasterSkin: number
    private static NormalSkin = Constants.UNIT_KITTY_VENDOR

    public static Initialize = () => {
        if (Seasons.getCurrentSeason() === HolidaySeasons.None) return
        ShopChanger.SetSeasonalShop()
    }

    public static SetSeasonalShop = () => {
        switch (Seasons.getCurrentSeason()) {
            case HolidaySeasons.None:
                ShopChanger.SetShopsToSkin(ShopChanger.NormalSkin)
                break

            case HolidaySeasons.Christmas:
                ShopChanger.SetShopsToSkin(ShopChanger.SantaSkin)
                break
            /*            case HolidaySeasons.Halloween:
                                HalloweenShop();
                                break;

                            case HolidaySeasons.Easter:
                                EasterShop();
                                break;

                            case HolidaySeasons.Valentines:
                                ValentinesShop();
                                break;*/
        }
    }

    private static SetShopsToSkin = (skinType: number) => {
        const tempGroup = Group.create()!
        tempGroup.enumUnitsInRect(
            Globals.WORLD_BOUNDS,
            Filter(() => getFilterUnit().typeId === Constants.UNIT_KITTY_VENDOR)
        )
        while (true) {
            const vendor = tempGroup.first
            if (!vendor) break
            tempGroup.removeUnit(vendor)
            vendor.skin = skinType
        }
        GC.RemoveGroup(tempGroup)
    }
}
