import { Constants } from 'src/AutoGenerated/Constants'
import { PROD } from 'src/env'
import { Logger } from 'src/Events/Logger/Logger'
import { SpawnChampions } from 'src/Game/Entities/Champions/SpawnChampions'
import { CurrentGameMode } from 'src/Gamemodes/CurrentGameMode'
import { GameMode } from 'src/Gamemodes/GameModeEnum'
import { Globals } from 'src/Global/Globals'
import { Colors } from 'src/Utility/Colors/Colors'
import { Utility } from 'src/Utility/Utility'
import { Frame, MapPlayer, Timer, Trigger, Unit } from 'w3ts'

export class CustomStat {
    public Frame: Frame
    public Icon: Frame
    public Text: Frame
    public Hover: Frame
    public ToolTipBox: Frame
    public ToolTipTitle: Frame
    public ToolTipText: Frame
}

export class CustomStatFrame {
    private static Count = 0
    private static CustomStatFrameBoxS: Frame
    private static CustomStatFrameBoxF: Frame

    public static SelectedUnit: Map<MapPlayer, Unit> = new Map()
    private static Stats: CustomStat[] = []
    private static MoveSpeed: string = `${Colors.COLOR_YELLOW_ORANGE}MS:|r`
    private static Time: string = `${Colors.COLOR_YELLOW_ORANGE}Time:|r`
    private static Saves: string = `${Colors.COLOR_YELLOW_ORANGE}Saves:|r`
    private static Deaths: string = `${Colors.COLOR_YELLOW_ORANGE}Deaths:|r`
    private static Streak: string = `${Colors.COLOR_YELLOW_ORANGE}Streak:|r`
    private static Gold: string = `${Colors.COLOR_YELLOW_ORANGE}Gold:|r`
    private static Ratio: string = `${Colors.COLOR_YELLOW_ORANGE}S/D:|r`
    private static Progress: string = `${Colors.COLOR_YELLOW_ORANGE}Prog.:|r`
    private static t: Timer

    public static Add(icon: string, text: string, titleTooltip: string) {
        CustomStatFrame.Count++
        const fh = BlzCreateSimpleFrame('CustomStat', CustomStatFrame.CustomStatFrameBoxS.handle, CustomStatFrame.Count)
        const tooltipBox = BlzCreateFrame(
            'BoxedText',
            CustomStatFrame.CustomStatFrameBoxF.handle,
            0,
            CustomStatFrame.Count
        )
        const fhHover = BlzCreateFrameByType(
            'FRAME',
            'CustomStatHover',
            CustomStatFrame.CustomStatFrameBoxF.handle,
            '',
            CustomStatFrame.Count
        )

        if (!fhHover || !fh || !tooltipBox) return

        BlzFrameSetPoint(fhHover, FRAMEPOINT_BOTTOMLEFT, fh, FRAMEPOINT_BOTTOMLEFT, 0, 0)
        BlzFrameSetPoint(
            fhHover,
            FRAMEPOINT_TOPRIGHT,
            BlzGetFrameByName('CustomStatText', CustomStatFrame.Count)!,
            FRAMEPOINT_TOPRIGHT,
            0,
            0
        )
        BlzFrameSetTooltip(fhHover, tooltipBox)

        BlzFrameSetAbsPoint(tooltipBox, FRAMEPOINT_BOTTOM, 0.6, 0.2)
        BlzFrameSetSize(tooltipBox, 0.15, 0.08)

        BlzFrameSetText(BlzGetFrameByName('CustomStatText', CustomStatFrame.Count)!, text)
        BlzFrameSetText(BlzGetFrameByName('BoxedTextTitle', CustomStatFrame.Count)!, titleTooltip)
        BlzFrameSetText(BlzGetFrameByName('BoxedTextValue', CustomStatFrame.Count)!, text)
        BlzFrameSetTexture(BlzGetFrameByName('CustomStatIcon', CustomStatFrame.Count)!, icon, 0, true)

        if (CustomStatFrame.Count === 1)
            BlzFrameSetPoint(
                fh,
                FRAMEPOINT_TOPLEFT,
                CustomStatFrame.CustomStatFrameBoxS.handle,
                FRAMEPOINT_TOPLEFT,
                0.015,
                -0.035
            )
        else if (CustomStatFrame.Count === 4)
            BlzFrameSetPoint(
                fh,
                FRAMEPOINT_TOPRIGHT,
                CustomStatFrame.CustomStatFrameBoxS.handle,
                FRAMEPOINT_TOPRIGHT,
                -0.06,
                -0.035
            )
        else
            BlzFrameSetPoint(
                fh,
                FRAMEPOINT_TOPLEFT,
                BlzGetFrameByName('CustomStat', CustomStatFrame.Count - 1)!,
                FRAMEPOINT_BOTTOMLEFT,
                0,
                -0.005
            )

        const statFrame = new CustomStat()
        CustomStatFrame.Stats.push(
            Object.assign(statFrame, {
                Frame: fh,
                Icon: Frame.fromHandle(BlzGetFrameByName('CustomStatIcon', CustomStatFrame.Count)),
                Text: Frame.fromHandle(BlzGetFrameByName('CustomStatText', CustomStatFrame.Count)),
                Hover: Frame.fromHandle(fhHover),
                ToolTipBox: Frame.fromHandle(tooltipBox),
                ToolTipTitle: Frame.fromHandle(BlzGetFrameByName('BoxedTextTitle', CustomStatFrame.Count)),
                ToolTipText: Frame.fromHandle(BlzGetFrameByName('BoxedTextValue', CustomStatFrame.Count)),
            })
        )
    }

    public static Update() {
        try {
            let selectedUnit: Unit
            if (!(selectedUnit = CustomStatFrame.SelectedUnit.get(MapPlayer.fromLocal())!) /* TODO; Prepend: let */)
                return
            CustomStatFrame.HandleFrameText(selectedUnit)

            CustomStatFrame.CustomStatFrameBoxF.visible = CustomStatFrame.CustomStatFrameBoxS.visible
        } catch (e: any) {
            Logger.Critical(`Error in CustomStatFrame.Update: ${e}`)
            throw e
        }
    }

    public static Init() {
        BlzLoadTOCFile('war3mapImported\\CustomStat.toc')
        BlzLoadTOCFile('war3mapImported\\BoxedText.toc')

        const hideParent = BlzCreateFrameByType('SIMPLEFRAME', 'HideParent', BlzGetFrameByName('ConsoleUI', 0)!, '', 0)
        if (!hideParent) return
        BlzFrameSetVisible(hideParent, false)
        BlzFrameSetParent(BlzGetFrameByName('SimpleInfoPanelIconDamage', 0)!, hideParent)
        BlzFrameSetParent(BlzGetFrameByName('SimpleInfoPanelIconDamage', 1)!, hideParent)
        BlzFrameSetParent(BlzGetFrameByName('SimpleInfoPanelIconArmor', 2)!, hideParent)
        BlzFrameSetParent(BlzGetFrameByName('SimpleInfoPanelIconRank', 3)!, hideParent)
        BlzFrameSetParent(BlzGetFrameByName('SimpleInfoPanelIconFood', 4)!, hideParent)
        BlzFrameSetParent(BlzGetFrameByName('SimpleInfoPanelIconGold', 5)!, hideParent)
        BlzFrameSetParent(BlzGetFrameByName('SimpleInfoPanelIconHero', 6)!, hideParent)
        BlzFrameSetParent(BlzGetFrameByName('SimpleInfoPanelIconAlly', 7)!, hideParent)

        const trig = Trigger.create()
        trig.addAction(() => {
            const player = MapPlayer.fromHandle(GetTriggerPlayer())!
            const unit = Unit.fromHandle(GetTriggerUnit())!
            CustomStatFrame.SelectedUnit.set(player, unit)
        })

        for (const player of Globals.ALL_PLAYERS)
            if (player.slotState === PLAYER_SLOT_STATE_PLAYING)
                trig.registerPlayerUnitEvent(player, EVENT_PLAYER_UNIT_SELECTED, () => true)

        CustomStatFrame.CustomStatFrameBoxS = Frame.fromHandle(
            BlzCreateFrameByType(
                'SIMPLEFRAME',
                'CustomStatFrameBoxSBoss',
                BlzGetFrameByName('SimpleUnitStatsPanel', 0)!,
                '',
                0
            )
        )!
        CustomStatFrame.CustomStatFrameBoxF = Frame.fromHandle(
            BlzCreateFrameByType('FRAME', 'CustomStatFrameBoxFBoss', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0)!, '', 0)
        )!

        CustomStatFrame.Add('war3mapImported\\BTNStopwatch.blp', '', 'Score')
        CustomStatFrame.Add('ReplaceableTextures\\CommandButtons\\BTNInnerFireOn.blp', '', 'Revives')
        CustomStatFrame.Add('ReplaceableTextures\\CommandButtons\\BTNDeath Coil.blp', '', 'Deaths')
        CustomStatFrame.Add('ReplaceableTextures\\CommandButtons\\BTNHealingWave.tga', '', 'Streak')
        CustomStatFrame.Add('ReplaceableTextures\\CommandButtons\\BTNGoldCoin.blp', '', 'Gold')
        CustomStatFrame.Add('ReplaceableTextures\\CommandButtons\\BTNBootsOfSpeed.blp', '', 'Speed')

        CustomStatFrame.t = Timer.create()
        CustomStatFrame.t.start(0.1, true, () => CustomStatFrame.Update())
    }

    private static HandleFrameText(selectedUnit: Unit) {
        if (selectedUnit.typeId === Constants.UNIT_CUSTOM_DOG || selectedUnit.typeId === Constants.UNIT_NITRO_PACER)
            CustomStatFrame.SetWolfFrameText(selectedUnit)
        else if (selectedUnit.typeId === Constants.UNIT_KITTY) {
            CustomStatFrame.SetCommonFrameText(selectedUnit)
            CustomStatFrame.SetGamemodeFrameText(selectedUnit)
        } else if (CustomStatFrame.SetChampionFrameText(selectedUnit)) {
        } else {
            // do nothing, particularly buildings and w/e else isnt listed to avoid dictionary errors.
        }
    }

    private static SetChampionFrameText(selectedUnit: Unit) {
        // GetUnitName is an async function, may have been prone to desync, now just reference if its the same unit in memory.
        if (selectedUnit === SpawnChampions.Fieryfox2023) {
            CustomStatFrame.Stats[1].Text.text = '|cffff0000Fieryfox|r'
            CustomStatFrame.Stats[2].Text.text = '|cffffff00Region: EU|r'
            CustomStatFrame.Stats[0].Text.text = '|cffffff00Time: 13:25|r'
            CustomStatFrame.Stats[4].Text.text = '|cffffff00Qoz|r'
            CustomStatFrame.Stats[5].Text.text = '|cffffff00Region: US|r'
            CustomStatFrame.Stats[3].Text.text = '|cffffff00Time: 15:36|r'
        } else if (selectedUnit === SpawnChampions.FandF2023) {
            CustomStatFrame.Stats[2].Text.text = '|cffffff00Region: US|r'
            CustomStatFrame.Stats[1].Text.text = '|cff00fffAches|r'
            CustomStatFrame.Stats[3].Text.text = '|cff00fffBranFlake|r'
            CustomStatFrame.Stats[5].Text.text = '|cffffff00Time: 23:12|r'
            CustomStatFrame.Stats[4].Text.text = '|cff00fffBalmydrop|r'
            CustomStatFrame.Stats[0].Text.text = '|cff00fffUdo|r'
        } else if (selectedUnit === SpawnChampions.Fieryfox2024) {
            CustomStatFrame.Stats[1].Text.text = '|cffff0000Fieryfox|r'
            CustomStatFrame.Stats[2].Text.text = '|cffffff00Region: EU|r'
            CustomStatFrame.Stats[0].Text.text = '|cffffff00Time: 13:23|r'
            CustomStatFrame.Stats[4].Text.text = '|cff964bc8MrGheed|r'
            CustomStatFrame.Stats[5].Text.text = '|cffffff00Region: US|r'
            CustomStatFrame.Stats[3].Text.text = '|cffffff00Time: 16:31|r'
        } else if (selectedUnit === SpawnChampions.Stan2025) {
            CustomStatFrame.Stats[0].Text.text = '|cffffff00Time: 14:25|r'
            CustomStatFrame.Stats[1].Text.text = '|cffa471e3Stan|r'
            CustomStatFrame.Stats[2].Text.text = '|cffffff00Region: EU|r'
            CustomStatFrame.Stats[3].Text.text = '|cffffff00Time: 14:56|r'
            CustomStatFrame.Stats[4].Text.text = '|cff964bc8Balmydrop|r'
            CustomStatFrame.Stats[5].Text.text = '|cffffff00Region: US|r'
        } else return false
        return true
    }

    private static SetWolfFrameText(selectedUnit: Unit) {
        CustomStatFrame.Stats[0].Text.text = ''
        CustomStatFrame.Stats[1].Text.text = ''
        CustomStatFrame.Stats[2].Text.text = ''
        CustomStatFrame.Stats[3].Text.text = ''
        //Stats[4].Text.text = "";
        if (selectedUnit.typeId === Constants.UNIT_CUSTOM_DOG) CustomStatFrame.SetWolfAffixTexts(selectedUnit)
        if (!PROD && selectedUnit.typeId === Constants.UNIT_CUSTOM_DOG)
            CustomStatFrame.Stats[4].Text.text = `Walk: ${Globals.ALL_WOLVES.get(selectedUnit)!.IsWalking}`
        CustomStatFrame.Stats[5].Text.text = `${CustomStatFrame.MoveSpeed} ${selectedUnit.moveSpeed}`
    }

    private static SetWolfAffixTexts(selectedUnit: Unit) {
        if (CurrentGameMode.active === GameMode.SoloTournament) return
        let wolf
        if (!(wolf = Globals.ALL_WOLVES.get(selectedUnit)) /* TODO; Prepend: let */) return

        const affixes = wolf.Affixes

        for (let i = 0; i < affixes.length; i++) {
            CustomStatFrame.Stats[i].Text.text = affixes[i].name
        }
    }

    private static SetGamemodeFrameText(selectedUnit: Unit) {
        if (CurrentGameMode.active === GameMode.Standard) {
            // Standard
            CustomStatFrame.Stats[3].Text.setText(
                `${CustomStatFrame.Streak} ${CustomStatFrame.GetPlayerSaveStreak(selectedUnit)}`
            )
            CustomStatFrame.Stats[0].Text.setText(
                `${CustomStatFrame.Ratio} ${Colors.COLOR_GREEN}${CustomStatFrame.GetCurrentRoundSaves(selectedUnit)}|r/${Colors.COLOR_RED}${CustomStatFrame.GetCurrentRoundDeaths(selectedUnit)}|r`
            )
            CustomStatFrame.Stats[1].Text.setText(
                `${CustomStatFrame.Saves} ${Colors.COLOR_GREEN}${CustomStatFrame.GetPlayerSaves(selectedUnit)}|r`
            )
        } else if (CurrentGameMode.active === GameMode.SoloTournament) {
            // Solo
            CustomStatFrame.Stats[0].Text.setText(
                `${CustomStatFrame.Time} ${CustomStatFrame.GetPlayerTime(selectedUnit)}`
            )
            CustomStatFrame.Stats[1].Text.setText(
                `${CustomStatFrame.Progress} ${CustomStatFrame.GetPlayerProgress(selectedUnit)}%`
            )
            CustomStatFrame.Stats[2].Text.setText(
                `${CustomStatFrame.Deaths} ${CustomStatFrame.GetGameTotalDeaths(selectedUnit)}`
            )
        } else if (CurrentGameMode.active === GameMode.TeamTournament) {
            // Team
            CustomStatFrame.Stats[0].Text.setText(`${CustomStatFrame.GetPlayerTeamName(selectedUnit)}`)
            CustomStatFrame.Stats[4].Text.setText(`${CustomStatFrame.GetPlayerProgress(selectedUnit)}%`)
            CustomStatFrame.Stats[1].Text.setText(
                `${CustomStatFrame.Saves} ${CustomStatFrame.GetGameTotalSaves(selectedUnit)}`
            )
            CustomStatFrame.Stats[2].Text.setText(
                `${CustomStatFrame.Deaths} ${CustomStatFrame.GetGameTotalDeaths(selectedUnit)}`
            )
        }
    }

    private static SetCommonFrameText(selectedUnit: Unit) {
        CustomStatFrame.Stats[4].Text.setText(`${CustomStatFrame.Gold} ${CustomStatFrame.GetPlayerGold(selectedUnit)}`)
        CustomStatFrame.Stats[5].Text.setText(`${CustomStatFrame.MoveSpeed} ${selectedUnit.moveSpeed}`)
        CustomStatFrame.Stats[2].Text.setText(
            `${CustomStatFrame.Deaths} ${Colors.COLOR_RED}${CustomStatFrame.GetPlayerDeaths(selectedUnit)}|r`
        )
    }

    private static GetPlayerTeamName(u: Unit) {
        let team: any
        return (team = Globals.PLAYERS_TEAMS.get(u.owner) /* TODO; Prepend: Team */
            ? team.TeamColor
            : `${Colors.COLOR_YELLOW_ORANGE}Team: Aches${Colors.COLOR_RESET}`)
    }

    private static GetPlayerGold(u: Unit) {
        return u.owner.getGold()
    }

    private static GetPlayerProgress(u: Unit) {
        return Globals.ALL_KITTIES.get(u.owner)!.TimeProg.GetRoundProgress(Globals.ROUND).toFixed(2)
    }

    private static GetPlayerSaves(u: Unit) {
        return Globals.ALL_KITTIES.get(u.owner)!.SaveData.GameStats.Saves
    }

    private static GetPlayerDeaths(u: Unit) {
        return Globals.ALL_KITTIES.get(u.owner)!.SaveData.GameStats.Deaths
    }

    private static GetPlayerSaveStreak(u: Unit) {
        return Globals.ALL_KITTIES.get(u.owner)!.SaveData.GameStats.SaveStreak
    }

    private static GetPlayerTime(u: Unit) {
        return Utility.ConvertFloatToTime(Globals.ALL_KITTIES.get(u.owner)!.TimeProg.GetRoundTime(Globals.ROUND))
    }

    private static GetCurrentRoundSaves(u: Unit) {
        return Globals.ALL_KITTIES.get(u.owner)!.CurrentStats.RoundSaves
    }

    private static GetCurrentRoundDeaths(u: Unit) {
        return Globals.ALL_KITTIES.get(u.owner)!.CurrentStats.RoundDeaths
    }

    private static GetGameTotalSaves(u: Unit) {
        return Globals.ALL_KITTIES.get(u.owner)!.CurrentStats.TotalSaves
    }

    private static GetGameTotalDeaths(u: Unit) {
        return Globals.ALL_KITTIES.get(u.owner)!.CurrentStats.TotalDeaths
    }
}
