import { Constants } from 'src/AutoGenerated/Constants'
import { Logger } from 'src/Events/Logger/Logger'
import { Utility } from 'src/Utility/Utility'
import { getManipulatedItem, getTriggerUnit } from 'src/Utility/w3tsUtils'
import { Trigger } from 'w3ts'

export class ItemStacker {
    private static PickupTrigger: Trigger
    private static StackableItemIDs: number[]

    public static Initialize() {
        this.RegisterItemList()
        this.RegisterEvents()
    }

    /// <summary>
    /// List of all the stackable items... Easy way to add more if needed.
    /// </summary>
    /// <returns></returns>
    private static RegisterItemList(): number[] {
        if (this.StackableItemIDs != null) return this.StackableItemIDs
        this.StackableItemIDs = [
            Constants.ITEM_ADRENALINE_POTION,
            Constants.ITEM_HEALING_WATER,
            Constants.ITEM_ELIXIR,
            Constants.ITEM_ANTI_BLOCK_WAND,
        ]
        return this.StackableItemIDs
    }

    private static RegisterEvents(): Trigger {
        let PickupTrigger = Trigger.create()!
        PickupTrigger.registerAnyUnitEvent(EVENT_PLAYER_UNIT_PICKUP_ITEM)
        PickupTrigger.addAction(this.StackActions)
        return PickupTrigger
    }

    private static StackActions() {
        try {
            let item = getManipulatedItem()
            let itemID = item.typeId
            if (!this.StackableItem(itemID)) return
            let unit = getTriggerUnit()
            let heldItem = Utility.UnitGetItem(unit, itemID)
            item.setOwner(unit.owner, false)
            if (heldItem == item) return
            if (heldItem == null) return
            let itemCharges = item.charges
            if (itemCharges > 1) heldItem.charges += itemCharges
            else heldItem.charges += 1
            item.destroy()
        } catch (e: any) {
            Logger.Critical(e.Message)
            throw e
        }
    }

    private static StackableItem(itemID: number) {
        return this.StackableItemIDs.includes(itemID)
    }
}
