import { Constants } from 'src/AutoGenerated/Constants'
import { Timer } from 'w3ts'

export class ItemSpawner {
    public static TrackKibbles: Kibble[]
    public static TrackItems: item[]

    private static SpawnableItems: number[]
    private static SpawnTimer = Timer.create()
    private static ITEM_SPAWN_INTERVAL: number = 45.0
    public static NUMBER_OF_ITEMS: number = 15

    public static Initialize() {
        if (Gamemode.CurrentGameMode != GameMode.Standard) return
        SpawnableItems = StandardItems()
        TrackItems = []
        TrackKibbles = []
        RegisterEvent()
        SpawnItems()
    }

    private static RegisterEvent() {
        SpawnTimer.start(ITEM_SPAWN_INTERVAL, true, SpawnItems)
    }

    private static SpawnItems() {
        try {
            RemoveSpawnedItems()
            for (let i = 0; i < NUMBER_OF_ITEMS; i++) {
                SpawnRegularItems()
            }
            SpawnKibble(NUMBER_OF_ITEMS)
        } catch (e: any) {
            Logger.Critical('ItemSpawner: SpawnItems: {e.Message}')
        }
    }

    private static RemoveSpawnedItems() {
        for (let i: number = 0; i < TrackItems.length; i++) {
            let item = TrackItems[i]
            ItemSpatialGrid.UnregisterItem(item)
            if (item.IsOwned) continue
            item.destroy()
        }

        TrackItems.clear()

        if (KibbleEvent.IsEventActive()) return

        for (let i: number = 0; i < TrackKibbles.length; i++) {
            let kibble = TrackKibbles[i]
            ItemSpatialGrid.UnregisterKibble(kibble)
            if (kibble.Item == null) continue // Already been __destroyed.
            kibble.dispose()
        }

        TrackKibbles.clear()
    }

    public static SpawnKibble(numberOfItems: number) {
        if (Gamemode.CurrentGameMode != GameMode.Standard) return
        if (!Kibble.SpawningKibble) return
        if (KibbleEvent.IsEventActive()) return

        for (let i: number = 0; i < numberOfItems; i++) {
            let kibble = MemoryHandler.getEmptyObject<Kibble>()
            kibble.SpawnKibble()
            TrackKibbles.push(kibble)
        }
    }

    private static SpawnRegularItems() {
        let random = GetRandomInt(0, SpawnableItems.length - 1)
        let item = SpawnableItems[random]
        let regionNumber = GetRandomInt(0, RegionList.WolfRegions.length - 1)
        let region = RegionList.WolfRegions[regionNumber]
        let x = GetRandomReal(region.Rect.minX, region.Rect.maxX)
        let y = GetRandomReal(region.Rect.minY, region.Rect.maxY)
        let i = Item.create(item, x, y)!
        TrackItems.push(i)
        ItemSpatialGrid.RegisterItem(i)
    }

    private static StandardItems() {
        return [Constants.ITEM_ADRENALINE_POTION, Constants.ITEM_HEALING_WATER, Constants.ITEM_ELIXIR]
    }
}
