import { Constants } from 'src/AutoGenerated/Constants'
import { Logger } from 'src/Events/Logger/Logger'
import { Globals } from 'src/Global/Globals'
import { RegionList } from 'src/Global/RegionList'
import { KibbleEvent } from 'src/Rewards/EasterEggs/KibbleEvent'
import { HolidaySeasons, Seasons } from 'src/Seasonal/Seasons'
import { SoundManager } from 'src/Sounds/SoundManager'
import { Colors } from 'src/Utility/Colors/Colors'
import { ColorUtils } from 'src/Utility/Colors/ColorUtils'
import { IDisposable } from 'src/Utility/CSUtils'
import { GC } from 'src/Utility/GC'
import { MemoryHandler } from 'src/Utility/MemoryHandler/MemoryHandler'
import { PositionWithPolarOffsetRadX, PositionWithPolarOffsetRadY, Utility } from 'src/Utility/Utility'
import { getManipulatedItem, getTriggerUnit } from 'src/Utility/w3tsUtils'
import { Effect, Item, MapPlayer, Trigger } from 'w3ts'
import { Kitty } from '../Entities/Kitty/Kitty'
import { ItemSpatialGrid } from './ItemSpatialGrid'
import { ItemSpawnerTrackKibbles } from './ItemSpawnerTrackKibbles'

export class Kibble extends IDisposable {
    public static SpawningKibble = true
    public static KibbleCollectionBeatenList: MapPlayer[] = []

    private static KibblesColors: number[] = Kibble.KibbleList()
    private static StarfallEffect = 'Abilities\\Spells\\NightElf\\Starfall\\StarfallTarget.mdl'
    private static TextTagHeight = 0.018
    private static XPMax = 350
    private static GoldMax = 150
    private static JackpotMin = 600
    private static JackpotMax = 1500

    public Item: Item
    private Type = 0
    private JackPotIndex = 0
    private StarFallEffect: Effect

    public constructor() {
        super()
        Kibble.KibblePickupEvents()
        this.Type = Kibble.RandomKibbleType()
    }

    public dispose = () => {
        this.Item?.destroy()
        MemoryHandler.destroyObject(this)
    }

    public SpawnKibble = () => {
        const regionNumber = GetRandomInt(0, RegionList.WolfRegions.length - 1)
        const region = RegionList.WolfRegions[regionNumber]
        const x = GetRandomReal(region.minX, region.maxX)
        const y = GetRandomReal(region.minY, region.maxY)
        this.StarFallEffect ??= Effect.fromHandle(AddSpecialEffect(Kibble.StarfallEffect, x, y))!
        this.StarFallEffect.setPosition(x, y, 0)
        this.StarFallEffect.playAnimation(ANIM_TYPE_BIRTH)
        this.JackPotIndex = 1
        if (!this.Type) this.Type = Kibble.RandomKibbleType()
        this.Item = Item.create(this.Type, x, y)!
        ItemSpatialGrid.RegisterKibble(this)
    }

    // #region Kibble Initialization

    private static RandomKibbleType(): number {
        return Kibble.KibblesColors[GetRandomInt(0, Kibble.KibblesColors.length - 1)]
    }

    private static KibblePickupEvents = () => {
        const trig = Trigger.create()!
        trig.registerAnyUnitEvent(EVENT_PLAYER_UNIT_PICKUP_ITEM)
        trig.addCondition(() => {
            const item = getManipulatedItem()
            if (!item) return false
            return Kibble.KibblesColors.includes(item.typeId)
        })
        trig.addAction(() => {
            Kibble.KibblePickup(getManipulatedItem())
        })
    }

    // #endregion Kibble Initialization

    // #region Kibble Pickup Logic

    private static KibblePickup = (item: Item) => {
        try {
            if (!item) return

            const unit = getTriggerUnit()
            const player = unit.owner
            const kitty = Globals.ALL_KITTIES.get(player)!
            let effect: Effect | undefined = undefined
            const randomChance = GetRandomReal(0, 100)
            const kib = ItemSpawnerTrackKibbles.active.find(k => k.Item?.handle === item?.handle)

            if (!kib) return

            if (randomChance <= 30) Kibble.KibbleGoldReward(kitty, kib)
            else if (randomChance <= 60) Kibble.KibbleXP(kitty)
            else Kibble.KibbleNothing(kitty)

            if (randomChance <= 30)
                effect = Effect.fromHandle(
                    AddSpecialEffect('Abilities\\Spells\\Other\\Transmute\\PileofGold.mdl', kitty.Unit.x, kitty.Unit.y)
                )
            GC.RemoveEffect(effect) // TODO; Cleanup:             GC.RemoveEffect(ref effect);

            KibbleEvent.StartKibbleEvent(randomChance)
            KibbleEvent.CollectEventKibble()

            Kibble.IncrementKibble(kitty)
            Kibble.BeatKibbleCollection(kitty)

            if (!!kib.Item) {
                kib.dispose()
            }
        } catch (e) {
            Logger.Warning(`Kibble.Error KibblePickup: ${e}`)
            throw e
        }
    }

    private static KibbleGoldReward = (kitty: Kitty, kib: Kibble) => {
        const jackPotChance = GetRandomInt(0, 100)
        let goldAmount: number
        if (jackPotChance <= 3) {
            Kibble.JackpotEffect(kitty, kib)
            return
        } else goldAmount = GetRandomInt(1, Kibble.GoldMax)
        kitty.Player.addGold(goldAmount)
        Utility.CreateSimpleTextTag(`+${goldAmount} Gold`, 2.0, kitty.Unit, Kibble.TextTagHeight, 255, 215, 0) // ?????? what.
    }

    private static KibbleXP = (kitty: Kitty) => {
        const xpAmount = GetRandomInt(50, Kibble.XPMax)
        kitty.Unit.experience += xpAmount
        SoundManager.PlayKibbleTomeSound(kitty.Unit)
    }

    private static KibbleNothing = (kitty: Kitty) => {
        Utility.CreateSimpleTextTag('Nothing!', 2.0, kitty.Unit, Kibble.TextTagHeight, 50, 150, 150)
    }

    private static JackpotEffect = (kitty: Kitty, kibble: Kibble) => {
        const unitX = kitty.Unit.x
        const unitY = kitty.Unit.y
        const newX = PositionWithPolarOffsetRadX(unitX, 150.0, kibble.JackPotIndex * 36.0)
        const newY = PositionWithPolarOffsetRadY(unitY, 150.0, kibble.JackPotIndex * 36.0)

        const effect = Effect.fromHandle(
            AddSpecialEffect('Abilities\\Spells\\Other\\Transmute\\PileofGold.mdl', newX, newY)
        )!
        GC.RemoveEffect(effect) // TODO; Cleanup:         GC.RemoveEffect(ref effect);
        kibble.JackPotIndex += 1

        if (kibble.JackPotIndex >= 20) {
            let goldAmount = GetRandomInt(Kibble.JackpotMin, Kibble.JackpotMax)
            const isSuperJackpot = GetRandomInt(1, 10) === 1
            if (isSuperJackpot) goldAmount *= 10

            kitty.Player.addGold(goldAmount)

            const jackpotString = isSuperJackpot ? `${Colors.COLOR_RED}Super Jackpot${Colors.COLOR_RESET}` : 'jackpot'
            const msg = `${ColorUtils.PlayerNameColored(kitty.Player)}${ColorUtils.HighlightString(` has won the ${jackpotString}`)} ${ColorUtils.HighlightString('for')} ${Colors.COLOR_YELLOW_ORANGE}${goldAmount} Gold|r`

            Utility.TimedTextToAllPlayers(3.0, msg) // was too long previously.
            Utility.CreateSimpleTextTag(`+${goldAmount} Gold`, 2.0, kitty.Unit, Kibble.TextTagHeight, 255, 215, 0)
            if (isSuperJackpot) {
                kitty.SaveData.KibbleCurrency.SuperJackpots += 1
                kitty.CurrentStats.CollectedSuperJackpots += 1
            } else {
                kitty.SaveData.KibbleCurrency.Jackpots += 1
                kitty.CurrentStats.CollectedJackpots += 1
            }
        } else Utility.SimpleTimer(0.15, () => Kibble.JackpotEffect(kitty, kibble))
    }

    // #endregion Kibble Pickup Logic

    // #region Utility Methods

    private static IncrementKibble = (kibblePicker: Kitty) => {
        kibblePicker.CurrentStats.CollectedKibble += 1

        for (const player of Globals.ALL_PLAYERS) player.addLumber(1)

        kibblePicker.SaveData.KibbleCurrency.Collected += 1
    }

    /// <summary>
    /// Checks if your kibble collection is higher than your personal best and updates it if so. Also notifies all players.
    /// </summary>
    /// <param name="k"></param>
    public static BeatKibbleCollection = (k: Kitty) => {
        const currentKibble = k.CurrentStats.CollectedKibble
        const bestKibble = k.SaveData.PersonalBests.KibbleCollected
        if (currentKibble < 10) return // avoid the spam for 1st timers.
        if (currentKibble > bestKibble) {
            k.SaveData.PersonalBests.KibbleCollected = currentKibble

            if (Kibble.KibbleCollectionBeatenList.includes(k.Player)) return
            Utility.TimedTextToAllPlayers(
                3.0,
                `${ColorUtils.PlayerNameColored(k.Player)} has set a new personal best by collecting ${Colors.COLOR_YELLOW}${currentKibble} kibbles!|r`
            )
            Kibble.KibbleCollectionBeatenList.push(k.Player)
        }
    }

    private static KibbleList(): number[] {
        switch (Seasons.getCurrentSeason()) {
            case HolidaySeasons.Christmas: {
                return [Constants.ITEM_PRESENT]
            }

            // case HolidaySeasons.Easter: {
            //     return [Constants.ITEM_EASTER_EGG]
            // }

            case HolidaySeasons.Valentines: {
                return [Constants.ITEM_HEART]
            }

            default: {
                return [
                    // Default case
                    Constants.ITEM_KIBBLE,
                    Constants.ITEM_KIBBLE_TEAL,
                    Constants.ITEM_KIBBLE_GREEN,
                    Constants.ITEM_KIBBLE_PURPLE,
                    Constants.ITEM_KIBBLE_RED,
                    Constants.ITEM_KIBBLE_YELLOW,
                ]
            }
        }
    }

    // #endregion Utility Methods
}
