import { Constants } from 'src/AutoGenerated/Constants'
import { Logger } from 'src/Events/Logger/Logger'
import { Utility } from 'src/Utility/Utility'
import { getManipulatedItem, getTriggerPlayer, getTriggerUnit } from 'src/Utility/w3tsUtils'
import { Trigger } from 'w3ts'

export class UniqueItems {
    private static Trigger: Trigger = Trigger.create()!
    private static UniqueList: Uniques[] = []

    public static Initialize() {
        try {
            this.UniqueList = this.UniqueItemList()
            this.RegisterEvents()
        } catch (e: any) {
            Logger.Critical('Error in UniqueItems.Initialize. {e.Message}')
            throw e
        }
    }

    private static UniqueItemList(): Uniques[] {
        return [
            new Uniques(Constants.ITEM_ENERGY_STONE, 200),
            new Uniques(Constants.ITEM_PEGASUS_BOOTS, 175),
            new Uniques(Constants.ITEM_RITUAL_MASK, 400),
            new Uniques(Constants.ITEM_MEDITATION_CLOAK, 375),
        ]
    }

    private static RegisterEvents() {
        this.Trigger.registerAnyUnitEvent(EVENT_PLAYER_UNIT_PICKUP_ITEM)
        this.Trigger.addAction(this.ItemPickup)
    }

    private static ItemPickup() {
        try {
            let item = getManipulatedItem()
            let player = getTriggerPlayer()
            let kitty = getTriggerUnit()

            if (item.typeId === 0) Logger.Warning('item: bug: Unique, ID: item is 0')

            if (!Uniques.UniqueIDs.includes(item.typeId)) return
            let uniqueItem = this.UniqueList.find(u => u.ItemID === item.typeId)
            if (!uniqueItem) return
            if (Utility.UnitHasItemCount(kitty, item.typeId) <= 1) return

            player.DisplayTimedTextTo(3.0, '{Colors.COLOR_RED}may: only: carry: one: You of unique: item: each.|r')
            player.addGold(uniqueItem.GoldCost)
            RemoveItem(item.handle)
        } catch (e: any) {
            Logger.Warning('Error in UniqueItems.ItemPickup: {e.Message}')
        }
    }
}

export class Uniques {
    public static UniqueIDs: number[] = []
    public ItemID: number
    public GoldCost: number

    public constructor(itemID: number, goldCost: number) {
        this.ItemID = itemID
        this.GoldCost = goldCost
        Uniques.UniqueIDs.push(itemID)
    }
}
