import { Constants } from 'src/AutoGenerated/Constants'
import { Logger } from 'src/Events/Logger/Logger'
import { Colors } from 'src/Utility/Colors/Colors'
import { Utility } from 'src/Utility/Utility'
import { getManipulatedItem, getTriggerPlayer, getTriggerUnit } from 'src/Utility/w3tsUtils'
import { Trigger } from 'w3ts'

export class UniqueItems {
    private static Trigger: Trigger = Trigger.create()!
    private static UniqueList: Uniques[] = []

    public static Initialize = () => {
        try {
            UniqueItems.UniqueList = UniqueItems.UniqueItemList()
            UniqueItems.RegisterEvents()
        } catch (e) {
            Logger.Critical(`Error in UniqueItems.Initialize. ${e}`)
            throw e
        }
    }

    private static UniqueItemList(): Uniques[] {
        return [
            new Uniques(Constants.ITEM_ENERGY_STONE, 200),
            new Uniques(Constants.ITEM_PEGASUS_BOOTS, 175),
            new Uniques(Constants.ITEM_RITUAL_MASK, 400),
            new Uniques(Constants.ITEM_MEDITATION_CLOAK, 375),
        ]
    }

    private static RegisterEvents = () => {
        UniqueItems.Trigger.registerAnyUnitEvent(EVENT_PLAYER_UNIT_PICKUP_ITEM)
        UniqueItems.Trigger.addAction(() => UniqueItems.ItemPickup())
    }

    private static ItemPickup = () => {
        try {
            const item = getManipulatedItem()
            const player = getTriggerPlayer()
            const kitty = getTriggerUnit()

            if (item.typeId === 0) Logger.Warning('Unique item bug, item ID is 0')

            if (!Uniques.UniqueIDs.includes(item.typeId)) return
            const uniqueItem = UniqueItems.UniqueList.find(u => u.ItemID === item.typeId)
            if (!uniqueItem) return
            if (Utility.UnitHasItemCount(kitty, item.typeId) <= 1) return

            player.DisplayTimedTextTo(3.0, `${Colors.COLOR_RED}You may only carry one of each unique item.|r`)
            player.addGold(uniqueItem.GoldCost)
            RemoveItem(item.handle)
        } catch (e) {
            Logger.Warning(`Error in UniqueItems.ItemPickup: ${e}`)
        }
    }
}

export class Uniques {
    public static UniqueIDs: number[] = []
    public ItemID = 0
    public GoldCost = 0

    public constructor(itemID: number, goldCost: number) {
        this.ItemID = itemID
        this.GoldCost = goldCost
        Uniques.UniqueIDs.push(itemID)
    }
}
