export class Colors {
    public static COLOR_GOLD: string = '|c00FFCC00'
    public static COLOR_YELLOW_ORANGE: string = '|c00FF9900'
    public static COLOR_RED: string = '|c00FF0000'
    public static COLOR_GREEN: string = '|c0000FF00'
    public static COLOR_BLUE: string = '|c000000FF'
    public static COLOR_PURPLE: string = '|c00CC00FF'
    public static COLOR_CYAN: string = '|c000FFFFF'
    public static COLOR_ORANGE: string = '|c00FF9900'
    public static COLOR_VIOLET: string = '|c00EE82EE'
    public static COLOR_PINK: string = '|c00FFC0CB'
    public static COLOR_LAVENDER: string = '|cffdbb8eb'
    public static COLOR_BLACK: string = '|c00000000'
    public static COLOR_WHITE: string = '|c00FFFFFF'
    public static COLOR_GREY: string = '|c00808080'
    public static COLOR_BROWN: string = '|c008B4513'
    public static COLOR_LIME: string = '|c0000FF00'
    public static COLOR_TURQUOISE: string = '|cff00ebff'
    public static COLOR_YELLOW: string = '|c00FFFF00'
    public static COLOR_DARK_RED: string = '|c008B0000'
    public static COLOR_LIGHTBLUE: string = '|c006969FF'
    public static COLOR_RESET: string = '|r'
}
