import { Constants } from 'src/AutoGenerated/Constants'
import { Wolf } from 'src/Game/Entities/Wolf'
import { CurrentGameMode } from 'src/Gamemodes/CurrentGameMode'
import { GameMode } from 'src/Gamemodes/GameModeEnum'
import { Globals } from 'src/Global/Globals'
import { GC } from 'src/Utility/GC'
import { Group, Trigger } from 'w3ts'

export class AntiblockWand {
    private static AbilityID: number
    private static Radius: number

    /// <summary>
    /// Register's antiblock wand cast's. Only works in standard mode.
    /// </summary>
    public static Initialize = () => {
        if (CurrentGameMode.active !== GameMode.Standard) return
        AntiblockWand.AbilityID = Constants.ABILITY_ANTI_BLOCK_WAND_ITEM
        AntiblockWand.Radius = 250.0
        AntiblockWand.RegisterCastEvents()
    }

    private static RegisterCastEvents = () => {
        const triggerHandle = Trigger.create()!
        for (const player of Globals.ALL_PLAYERS)
            triggerHandle.registerPlayerUnitEvent(player, EVENT_PLAYER_UNIT_SPELL_CAST, undefined)
        triggerHandle.addAction(AntiblockWand.SpellActions)
    }

    private static SpellActions = () => {
        if (GetSpellAbilityId() !== AntiblockWand.AbilityID) return
        const wolvesInArea = Group.create()!
        wolvesInArea.enumUnitsInRange(GetSpellTargetX(), GetSpellTargetY(), AntiblockWand.Radius, () => true)
        const list = []
        while (wolvesInArea.size > 0) {
            const wolf = wolvesInArea.first
            if (!wolf) return
            wolvesInArea.removeUnit(wolf)
            list.push(wolf)
        }
        for (const wolf of list) {
            if (wolf.typeId !== Wolf.WOLF_MODEL) continue
            if (Globals.DNTNamedWolves.includes(Globals.ALL_WOLVES.get(wolf)!)) continue
            const wolfUnit = Globals.ALL_WOLVES.get(wolf)!
            wolfUnit.StartWandering(true)
        }

        GC.RemoveGroup(wolvesInArea) // TODO; Cleanup:         GC.RemoveGroup(ref wolvesInArea);
        GC.RemoveList(list) // TODO; Cleanup:         GC.RemoveList(ref list);
    }
}
