import { Constants } from "src/AutoGenerated/Constants"
import { NamedWolves } from "src/Game/Entities/NamedWolves"
import { Wolf } from "src/Game/Entities/Wolf"
import { Gamemode } from "src/Gamemodes/Gamemode"
import { GameMode } from "src/Gamemodes/GameModeEnum"
import { Globals } from "src/Global/Globals"
import { GC } from "src/Utility/GC"
import { Trigger, Group } from "w3ts"

export class AntiblockWand {
    private static CastEvent: Trigger
    private static AbilityID: number
    private static Radius: number

    /// <summary>
    /// Register's antiblock wand cast's. Only works in standard mode.
    /// </summary>
    public static Initialize() {
        if (Gamemode.CurrentGameMode != GameMode.Standard) return
        this.AbilityID = Constants.ABILITY_ANTI_BLOCK_WAND_ITEM
        this.Radius = 250.0
        this.CastEvent = this.RegisterCastEvents()
    }

    private static RegisterCastEvents(): Trigger {
        let triggerHandle = Trigger.create()!
        for (let player of Globals.ALL_PLAYERS) triggerHandle.registerPlayerUnitEvent(player, EVENT_PLAYER_UNIT_SPELL_CAST, undefined)
        triggerHandle.addAction(this.SpellActions)
        return triggerHandle
    }

    private static SpellActions() {
        if (GetSpellAbilityId() != this.AbilityID) return
        let location = GetSpellTargetLoc()
        let wolvesInArea = Group.create()!
        wolvesInArea.enumUnitsInRange(location.x, location.y, this.Radius, null)
        let list = wolvesInArea.ToList()
        for (let wolf in list) {
            if (wolf.typeId != Wolf.WOLF_MODEL) continue
            if (NamedWolves.DNTNamedWolves.includes(Globals.ALL_WOLVES[wolf])) continue
            let wolfUnit = Globals.ALL_WOLVES[wolf]
            wolfUnit.StartWandering(true)
        }

        GC.RemoveGroup(wolvesInArea) // TODO; Cleanup:         GC.RemoveGroup(ref wolvesInArea);
        GC.RemoveList(list) // TODO; Cleanup:         GC.RemoveList(ref list);
        location.dispose()
    }
}
