import { Regions } from 'src/AutoGenerated/Regions'

class PodiumManager {
    public static PodiumSpots: Point[]

    public static Initialize() {
        PodiumManager.SetPodiumPositions()
    }

    public static BeginPodiumEvents() {
        switch (Gamemode.CurrentGameMode) {
            case GameMode.Standard:
                StandardPodium.BeginPodiumActions()
                break

            case GameMode.SoloTournament:
                SoloPodium.BeginPodiumActions()
                break

            case GameMode.TeamTournament:
                TeamPodium.BeginPodiumActions()
                break
        }
    }

    private static SetPodiumPositions() {
        PodiumManager.PodiumSpots = [Regions.Podium_1.Center, Regions.Podium_2.Center, Regions.Podium_3.Center]
    }
}
