import { Constants } from 'src/AutoGenerated/Constants'
import { Regions } from 'src/AutoGenerated/Regions'
import { RoundManager } from 'src/Game/Rounds/RoundManager'
import { RoundUtilities } from 'src/Game/Rounds/RoundUtilities'
import { CurrentGameMode } from 'src/Gamemodes/CurrentGameMode'
import { GameMode } from 'src/Gamemodes/GameModeEnum'
import { Globals } from 'src/Global/Globals'
import { BarrierSetup } from 'src/Init/BarrierSetup'
import { MultiboardUtil } from 'src/UI/Multiboard/MultiboardUtil'
import { ErrorHandler } from 'src/Utility/ErrorHandler'
import { getFilterUnit, getTriggerUnit } from 'src/Utility/w3tsUtils'
import { Trigger, Unit } from 'w3ts'

export class VictoryZone {
    private static InVictoryArea: Trigger

    public static Initialize() {
        VictoryZone.InVictoryArea = Trigger.create()!
        VictoryZone.VictoryAreaTrigger()
    }

    private static VictoryAreaConditions(u: Unit) {
        return (
            VictoryZone.VictoryAreaConditionsStandard(u) ||
            VictoryZone.VictoryAreaConditionsTeam(u) ||
            VictoryZone.VictoryAreaConditionsSolo(u)
        )
    }

    private static VictoryAreaTrigger() {
        const VictoryArea = Regions.Victory_Area.region()
        VictoryZone.InVictoryArea.registerEnterRegion(
            VictoryArea,
            Filter(() => VictoryZone.VictoryAreaConditions(getFilterUnit()))
        )
        VictoryZone.InVictoryArea.addAction(ErrorHandler.Wrap(() => VictoryZone.VictoryAreaActions()))
    }

    private static VictoryAreaActions() {
        const u = getTriggerUnit()
        const player = u.owner
        if (u.typeId !== Constants.UNIT_KITTY) return
        if (!Globals.GAME_ACTIVE) return
        if (CurrentGameMode.active === GameMode.Standard) {
            // Standard
            if (Globals.ROUND === Globals.NumberOfRounds) Globals.WinGame = true
            RoundManager.RoundEnd()
        } else if (CurrentGameMode.active === GameMode.SoloTournament) {
            // Solo
            // Move player to start, save their time. Wait for everyone to finish.
            //MoveAndFinish(player);
            RoundManager.RoundEndCheck()
        } else if (CurrentGameMode.active === GameMode.TeamTournament) {
            // Team
            const kitty = Globals.ALL_KITTIES.get(player)!
            kitty.Finished = true

            if (RoundManager.DidTeamEnd(kitty.TeamID)) {
                Globals.ALL_TEAMS.get(kitty.TeamID)!.Finished = true
                if (RoundManager.RoundEndCheck()) return
            }
            RoundUtilities.MoveTeamToStart(Globals.ALL_TEAMS.get(kitty.TeamID)!)
            if (RoundManager.RoundEndCheck()) return
            BarrierSetup.ActivateBarrier()

            // // Move all team members to the start, save their time. Wait for all teams to finish.
            // for (let teamMember in Globals.ALL_TEAMS.get(Globals.ALL_KITTIES.get(player)!.TeamID)!.Teammembers)
            // {
            //     MoveAndFinish(teamMember);
            // }
            // Globals.ALL_TEAMS.get(Globals.ALL_KITTIES.get(player)!.TeamID)!.Finished = true;
            // RoundManager.RoundEndCheck();
        }
        MultiboardUtil.RefreshMultiboards()
    }

    private static VictoryAreaConditionsStandard(u: Unit) {
        return CurrentGameMode.active === GameMode.Standard
    }

    private static VictoryAreaConditionsSolo(u: Unit) {
        return CurrentGameMode.active === GameMode.SoloTournament
    }

    private static VictoryAreaConditionsTeam(u: Unit) {
        // If a team enters the area, check if all the members of the team are in the area.
        if (CurrentGameMode.active !== GameMode.TeamTournament) return false
        const team = Globals.ALL_KITTIES.get(u.owner)!.TeamID
        for (const player of Globals.ALL_TEAMS.get(team)!.Teammembers) {
            if (!VictoryZone.VictoryContainerConditions(Globals.ALL_KITTIES.get(player)!.Unit)) return false
        }
        return true
    }

    private static VictoryContainerConditions(u: Unit) {
        return Regions.Victory_Area.includes(u.x, u.y) || Regions.safe_Area_14.includes(u.x, u.y)
    }
}
