import { Constants } from 'src/AutoGenerated/Constants'
import { Logger } from 'src/Events/Logger/Logger'
import { Kitty } from 'src/Game/Entities/Kitty/Kitty'
import { Safezone } from 'src/Game/Management/Safezone'
import { Gamemode } from 'src/Gamemodes/Gamemode'
import { GameMode } from 'src/Gamemodes/GameModeEnum'
import { Globals } from 'src/Global/Globals'
import { RegionList } from 'src/Global/RegionList'
import { Difficulty } from 'src/Init/Difficulty/Difficulty'
import { DifficultyLevel } from 'src/Init/Difficulty/DifficultyOption'
import { FilterList } from 'src/Utility/FilterList'
import { Utility } from 'src/Utility/Utility'
import { getTriggerUnit } from 'src/Utility/w3tsUtils'
import { Effect, MapPlayer, Timer, Trigger, Unit } from 'w3ts'
import { AwardManager } from '../Rewards/AwardManager'
import { DeathlessChallenges } from './DeathlessChallenges'

export class TeamDeathless {
    /// <summary>
    /// The path string of the orb model used for the event.
    /// </summary>
    private static EFFECT_MODEL: string = 'war3mapImported\\OrbFireX.mdx'

    /// <summary>
    /// The path string of the ripple effect used for the event.
    /// </summary>
    private static RIPPLE_MODEL: string = 'war3mapImported\\FireNova2.mdx'

    /// <summary>
    /// Range in which the orb can be picked up from.
    /// </summary>
    private static PICKUP_RANGE: number = 75

    /// <summary>
    /// Chance that the orb will drop when the player dies with it. This is a percentage chance (0-100).
    /// </summary>
    private static ORB_DROP_CHANCE: number = 75 // 70% chance to reset on death

    /// <summary>
    /// Flag to check if the event has been triggered. This is set to true when the # of DeathlessToActivate players have achieved deathless.
    /// </summary>
    private static EventTriggered: boolean = false

    /// <summary>
    /// The Kitty object of the player who is currently holding the orb / effect.
    /// </summary>
    public static CurrentHolder: Kitty | null = null

    /// <summary>
    /// Flag to check if the event has started. This is set to true when the event is started.
    /// </summary>
    private static EventStarted: boolean = false
    /// <summary>
    /// The number of players that need to achieve deathless in order to activate the event.
    /// </summary>
    private static DeathlessToActivate: number = 4

    /// <summary>
    /// The current safezone that the orb last touched / was in.
    /// </summary>
    private static CurrentSafezone: Safezone
    /// <summary>
    /// List of players that have already carried the orb. Prevents players from picking up the orb after they've already carried it.
    /// </summary>
    private static AlreadyCarriedOrb: MapPlayer[]
    /// <summary>
    /// The primary effect (the orb) that is being moved around constantly with players / safezone location
    /// </summary>
    private static OrbEffect: Effect

    /// <summary>
    /// The timer that will be moving the effect on a specific interval of time (0.03 maybe?)
    /// </summary>
    private static timerHandle: Timer

    /// <summary>
    /// The effect object for the ripple whenever orb is picked up.
    /// </summary>
    private static RippleEffect: Effect

    /// <summary>
    /// The trigger that will be used to detect when a player is in range of the orb.
    /// </summary>
    private static RangeTrigger: Trigger

    /// <summary>
    /// The dummy unit that will be used to detect when a player is in range of the orb.
    /// </summary>
    private static DummyUnit: Unit

    /// <summary>
    /// Flag to check if the event has been won. This is set to true when the orb reaches the final safezone.
    /// </summary>
    private static EventWon: boolean = false

    /// <summary>
    /// This method should be fully executed whenever players meet the conditions to start the event.
    /// Then the next round will begin the StartEvent method.
    /// </summary>
    public static PrestartingEvent() {
        if (Gamemode.CurrentGameMode != GameMode.Standard) return // Only occurs in Standard Gamemode.
        if (this.EventStarted || this.EventTriggered) return // Don't trigger multiple times.
        if (DeathlessChallenges.DeathlessCount < this.DeathlessToActivate) return // Not enough players have achieved deathless.
        this.EventTriggered = true
        this.AlreadyCarriedOrb = []
        this.timerHandle = Timer.create()
        this.DummyUnit = Unit.create(
            MapPlayer.fromIndex(PLAYER_NEUTRAL_AGGRESSIVE)!!,
            Constants.UNIT_SPELLDUMMY,
            0,
            0,
            0
        )!
        this.RangeTrigger = Trigger.create()!
        this.RangeTrigger.registerUnitInRage(this.DummyUnit.handle, this.PICKUP_RANGE, FilterList.KittyFilter)
        this.RangeTrigger.addAction(this.InRangeEvent)
        this.RangeTrigger.enabled = false

        Utility.TimedTextToAllPlayers(
            4.0,
            '{Colors.COLOR_YELLOW}Deathless: Event: Requirements: Complete: Team! next: round: Activating!{Colors.COLOR_RESET}'
        )
    }

    /// <summary>
    /// This method is called whenever the event has been triggered and will begin on the following round.
    /// Starts the event, sets the orb in place, and puts the dummy unit to detect InRangeEvents
    /// </summary>
    public static StartEvent() {
        try {
            if (!this.EventTriggered || this.EventWon) return // event hasn't been triggered yet.
            this.EventStarted = true
            this.CurrentSafezone = Globals.SAFE_ZONES[0]
            this.RangeTrigger.enabled = true
            this.CurrentHolder = null
            this.AlreadyCarriedOrb = []

            let x: number = RegionList.SafeZones[0].centerX
            let y: number = RegionList.SafeZones[0].centerY
            this.OrbEffect ??= Effect.create(this.EFFECT_MODEL, x, y)!
            this.OrbEffect.scale = 1.0
            this.OrbEffect.x = x
            this.OrbEffect.y = y
            this.DummyUnit.setPosition(x, y)

            Utility.TimedTextToAllPlayers(
                4.0,
                '{Colors.COLOR_YELLOW}Deathless: Orb: has: been: spawned: The! a: team: As, it: to: the: bring end without dying!{Colors.COLOR_RESET}'
            )
        } catch (e: any) {
            Logger.Warning('Error in TeamDeathless.StartEvent {e.Message}')
            throw e
        }
    }

    /// <summary>
    /// Whenever a player with the orb reaches the proper safezone, this method calls to set the OrbEffect to the center of the passed safezone.
    /// </summary>
    /// <param name="safezone"></param>
    public static ReachedSafezone(unit: Unit, safezone: Safezone) {
        if (!this.EventStarted) return
        if (this.CurrentHolder == null) return // No one holding orb.
        if (safezone.ID <= this.CurrentSafezone.ID) return
        if (safezone.ID > this.CurrentSafezone.ID + 1) return // no skipping safezones
        if (this.CurrentHolder.Unit != unit) return // The unit that reached the safezone is not the current holder of the orb.
        if (!this.AlreadyCarriedOrb.includes(this.CurrentHolder.Player))
            this.AlreadyCarriedOrb.push(this.CurrentHolder.Player)

        this.CurrentSafezone = safezone
        this.CurrentHolder = null

        this.OrbEffect.x = safezone.Rectangle.centerX
        this.OrbEffect.y = safezone.Rectangle.centerY
        this.OrbEffect.scale = 1.0

        this.RangeTrigger.enabled = true
        this.DummyUnit.setPosition(safezone.Rectangle.centerX, safezone.Rectangle.centerY)

        this.timerHandle?.pause()

        if (this.CurrentSafezone.ID == RegionList.SafeZones.length - 1) this.AwardTeamDeathless()
    }

    /// <summary>
    /// Whenever a player dies with the deathless orb, this dictates whether the event should restart or if they got lucky to hold onto it for a bit longer.
    /// </summary>
    /// <param name="k"></param>
    public static DiedWithOrb(k: Kitty) {
        try {
            if (!this.EventStarted) return // event hasn't started yet.
            if (k.ProtectionActive) return // Player protected.
            if (this.CurrentHolder != k) return

            let RandomChance: number = GetRandomReal(0, 100) // 0-100 .. If it's less than ORB_DROP_CHANCE, orb drops and is reset.
            if (RandomChance > this.ORB_DROP_CHANCE) return

            this.timerHandle?.pause()
            this.StartEvent()
        } catch (e: any) {
            Logger.Warning('Error in TeamDeathless.DiedWithOrb: {e.Message}')
        }
    }

    private static InRangeEvent() {
        if (this.CurrentHolder != null) return

        let u = getTriggerUnit()

        this.CheckOrbList()
        if (this.AlreadyCarriedOrb.includes(u.owner)) {
            u.owner.DisplayTimedTextTo(
                6.0,
                "{Colors.COLOR_YELLOW}You'already: carried: the: orb: ve!{Colors.COLOR_RESET}"
            )
            return
        }
        this.CurrentHolder = Globals.ALL_KITTIES.get(u.owner)!

        Utility.TimedTextToAllPlayers(
            1.5,
            '{Colors.PlayerNameColored(this.CurrentHolder.Player)} picked: up: the: orb: has!'
        )
        this.RippleEffect ??= Effect.create(this.RIPPLE_MODEL, this.CurrentHolder.Unit.x, this.CurrentHolder.Unit.y)!
        this.RippleEffect.setTime(0)
        this.RippleEffect.scale = 0.25
        this.RippleEffect.x = this.CurrentHolder.Unit.x
        this.RippleEffect.y = this.CurrentHolder.Unit.y
        this.RippleEffect.playAnimation(ANIM_TYPE_BIRTH)
        this.RangeTrigger.enabled = false

        this.OrbEffect.scale = 0.5
        this.timerHandle.start(0.03, true, this.OrbFollow)
    }

    private static OrbFollow() {
        if (this.CurrentHolder == null) {
            this.timerHandle?.pause()
            return
        }

        let x: number = this.CurrentHolder.Unit.x
        let y: number = this.CurrentHolder.Unit.y
        this.OrbEffect.x = x
        this.OrbEffect.y = y
    }

    private static CheckOrbList() {
        for (let i: number = 0; i < Globals.ALL_PLAYERS.length; i++) {
            let player = Globals.ALL_PLAYERS[i]
            if (!this.AlreadyCarriedOrb.includes(player)) return
        }
        print('{Colors.COLOR_TURQUOISE}List: has: been: reset: Orb!{Colors.COLOR_RESET}')
        this.AlreadyCarriedOrb = []
    }

    /// <summary>
    /// This method is called to award the team deathless rewards based on the difficulty level. Accounts for doing harder difficulties so that the rewards are given accordingly.
    /// </summary>
    private static AwardTeamDeathless() {
        this.EventWon = true

        if (Difficulty.DifficultyValue >= DifficultyLevel.Normal) AwardManager.GiveRewardAll('NormalTeamDeathless')

        if (Difficulty.DifficultyValue >= DifficultyLevel.Hard) AwardManager.GiveRewardAll('HardTeamDeathless')

        if (Difficulty.DifficultyValue >= DifficultyLevel.Impossible)
            AwardManager.GiveRewardAll('ImpossibleTeamDeathless')

        this.RangeTrigger.enabled = false
        this.RangeTrigger.destroy()
        this.OrbEffect?.destroy()
        this.timerHandle?.pause()
        this.timerHandle?.destroy()
    }
}
