import { Constants } from 'src/AutoGenerated/Constants'
import { Globals } from 'src/Global/Globals'
import { GC } from 'src/Utility/GC'
import { getTriggerUnit } from 'src/Utility/w3tsUtils'
import { Trigger, Unit } from 'w3ts'
import { GameSelectedData } from '../../SaveSystem2.0/MAKE REWARDS HERE/SaveObjects/GameSelectedData'
import { Reward, RewardType } from './Reward'

/// <summary>
/// This class handles:
/// * Activation / Deactivation of Rewards (Based on Spell Cast Event)
/// * Any activated reward including the Reset ability so long as it's added within the RewardCreation class.
/// </summary>
export class RewardsManager {
    private static Trigger: Trigger = Trigger.create()!
    private static RewardAbilities: number[] = []
    public static Rewards: Reward[] = []

    public static RewardAbilitiesList() {
        for (const reward of RewardsManager.Rewards) RewardsManager.RewardAbilities.push(reward.AbilityID)
    }

    public static RegisterTrigger() {
        for (const player of Globals.ALL_PLAYERS) {
            RewardsManager.Trigger.registerPlayerUnitEvent(player, EVENT_PLAYER_UNIT_SPELL_CAST, undefined)
        }
        RewardsManager.Trigger.addAction(() => RewardsManager.CastedReward())
    }

    private static CastedReward() {
        const spellID = GetSpellAbilityId()
        const unit = getTriggerUnit()
        if (RewardsManager.IsResetSpell(spellID)) {
            RewardsManager.ResetRewardSettings(unit)
            Globals.ALL_KITTIES.get(unit.owner)!.KittyMorphosis.ScaleUnit() // changes scale of unit if they have amulet.
            return
        }
    }

    private static IsRewardAbility(spellID: number) {
        return RewardsManager.RewardAbilities.includes(spellID)
    }

    private static IsResetSpell(spellID: number) {
        return spellID === Constants.ABILITY_RESET
    }

    private static ResetRewardSettings(Unit: Unit) {
        const player = Unit.owner
        const kitty = Globals.ALL_KITTIES.get(player)!
        const activeRewards = kitty.ActiveAwards

        const wings = activeRewards.ActiveWings
        GC.RemoveEffect(wings) // TODO; Cleanup:         GC.RemoveEffect(ref wings);

        const auras = activeRewards.ActiveAura
        GC.RemoveEffect(auras) // TODO; Cleanup:         GC.RemoveEffect(ref auras);

        const hats = activeRewards.ActiveHats
        GC.RemoveEffect(hats) // TODO; Cleanup:         GC.RemoveEffect(ref hats);

        const trails = activeRewards.ActiveTrail
        GC.RemoveEffect(trails) // TODO; Cleanup:         GC.RemoveEffect(ref trails);

        kitty.Unit.skin = Constants.UNIT_KITTY
        kitty.Unit.setVertexColor(255, 255, 255, 255)

        for (const property of Object.keys(kitty.SaveData.SelectedData)) {
            kitty.SaveData.SelectedData[property as keyof GameSelectedData] = ''
        }

        if (kitty.SaveData.SelectedData.SelectedWindwalk === '') kitty.ActiveAwards.WindwalkID = 0
    }

    public static AddReward(reward: Reward): Reward {
        RewardsManager.Rewards.push(reward)
        reward.TypeSorted = reward.SetRewardTypeSorted()
        return reward
    }

    /**
     * Creates and adds a reward with model path and origin point (for effects like auras, trails, wings, hats)
     */
    public static AddRewardFromModel(
        name: string,
        abilityID: number,
        originPoint: string,
        modelPath: string,
        rewardType: RewardType
    ): Reward {
        const reward = Reward.createRewardFromModel(name, abilityID, originPoint, modelPath, rewardType)
        return RewardsManager.AddReward(reward)
    }

    /**
     * Creates and adds a reward with model path, origin point, and game stat tracking
     */
    public static AddRewardFromModelWithStats(
        name: string,
        abilityID: number,
        originPoint: string,
        modelPath: string,
        rewardType: RewardType,
        gameStat: string,
        gameStatValue: number
    ): Reward {
        const reward = Reward.createRewardFromModelWithStats(
            name,
            abilityID,
            originPoint,
            modelPath,
            rewardType,
            gameStat,
            gameStatValue
        )
        return RewardsManager.AddReward(reward)
    }

    /**
     * Creates and adds a reward with skin ID (for skin rewards)
     */
    public static AddRewardFromSkin(name: string, abilityID: number, skinID: number, rewardType: RewardType): Reward {
        const reward = Reward.createRewardFromSkin(name, abilityID, skinID, rewardType)
        return RewardsManager.AddReward(reward)
    }

    /**
     * Creates and adds a reward with skin ID and game stat tracking
     */
    public static AddRewardFromSkinWithStats(
        name: string,
        abilityID: number,
        skinID: number,
        rewardType: RewardType,
        gameStat: string,
        gameStatValue: number
    ): Reward {
        const reward = Reward.createRewardFromSkinWithStats(
            name,
            abilityID,
            skinID,
            rewardType,
            gameStat,
            gameStatValue
        )
        return RewardsManager.AddReward(reward)
    }

    public static SetupRewards() {
        const awardsSorted = Globals.GAME_AWARDS_SORTED
        const stats = Globals.GAME_STATS

        // Hats
        RewardsManager.AddRewardFromModelWithStats(
            'Bandana',
            Constants.ABILITY_HAT_BANDANA,
            'head',
            'war3mapImported\\Bandana2.MDX',
            RewardType.Hats,
            'Saves',
            200
        )
        RewardsManager.AddRewardFromModelWithStats(
            'PirateHat',
            Constants.ABILITY_HAT_PIRATE,
            'head',
            'war3mapImported\\PirateHat.MDX',
            RewardType.Hats,
            'Saves',
            250
        )
        RewardsManager.AddRewardFromModelWithStats(
            'ChefHat',
            Constants.ABILITY_HAT_CHEF,
            'head',
            'war3mapImported\\ChefsHat.mdx',
            RewardType.Hats,
            'Saves',
            300
        )
        RewardsManager.AddRewardFromModelWithStats(
            'TikiMask',
            Constants.ABILITY_HAT_TIKI,
            'head',
            'war3mapImported\\TikiMask.mdx',
            RewardType.Hats,
            'Saves',
            350
        )
        RewardsManager.AddRewardFromModelWithStats(
            'SamuraiHelm',
            Constants.ABILITY_HAT_SAMURAI,
            'head',
            'war3mapImported\\SamuraiHelmet2.mdx',
            RewardType.Hats,
            'Saves',
            400
        )
        RewardsManager.AddRewardFromModelWithStats(
            'SantaHat',
            Constants.ABILITY_HAT_SANTA,
            'head',
            'war3mapImported\\SantaHat.mdx',
            RewardType.Hats,
            'Saves',
            800
        )

        // Auras
        RewardsManager.AddRewardFromModelWithStats(
            'SpecialAura',
            Constants.ABILITY_AURA_SPECIAL,
            'origin',
            'war3mapImported\\SoulArmor.mdx',
            RewardType.Auras,
            'HardWins',
            5
        )
        RewardsManager.AddRewardFromModelWithStats(
            'StarlightAura',
            Constants.ABILITY_AURA_STARLIGHT,
            'origin',
            'war3mapImported\\StarlightAura.mdx',
            RewardType.Auras,
            'NormalGames',
            65
        )
        RewardsManager.AddRewardFromModelWithStats(
            'SpectacularAura',
            Constants.ABILITY_AURA_SPECTACULAR,
            'origin',
            'war3mapImported\\ChillingAura.mdx',
            RewardType.Auras,
            'NormalWins',
            30
        )
        RewardsManager.AddRewardFromModelWithStats(
            'ManaAura',
            Constants.ABILITY_AURA_MANATAP,
            'origin',
            'war3mapImported\\ManaTapAura.MDX',
            RewardType.Auras,
            'NormalWins',
            20
        )
        RewardsManager.AddRewardFromModel(
            'ButterflyAura',
            Constants.ABILITY_AURA_BUTTERFLY,
            'origin',
            'war3mapImported\\ButterflyAura.mdx',
            RewardType.Auras
        )
        RewardsManager.AddRewardFromModel(
            'FreezeAura',
            Constants.ABILITY_AURA_FREEZE,
            'origin',
            'war3mapImported\\HolyFreezeAuraD2.mdx',
            RewardType.Auras
        )
        RewardsManager.AddRewardFromModel(
            'VioletAura',
            Constants.ABILITY_CHAMPION_AURAPURPLERUNIC,
            'origin',
            'war3mapImported\\GlaciarAuraPurple.mdx',
            RewardType.Tournament
        )
        // Chained Together Awards
        RewardsManager.AddRewardFromModel(
            'ChainedNormalAura',
            Constants.ABILITY_AURA_CHAINEDNORMAL,
            'origin',
            'war3mapImported\\ChainedNormalAura.mdx',
            RewardType.Auras
        )
        RewardsManager.AddRewardFromModel(
            'ChainedHardAura',
            Constants.ABILITY_AURA_CHAINEDHARD,
            'origin',
            'war3mapImported\\ChainedHardAura.mdx',
            RewardType.Auras
        )
        RewardsManager.AddRewardFromModel(
            'ChainedImpossibleAura',
            Constants.ABILITY_AURA_CHAINEDIMPOSSIBLE,
            'origin',
            'war3mapImported\\ChainedImpossibleAura.mdx',
            RewardType.Auras
        )
        RewardsManager.AddRewardFromModel(
            'ChainedNightmareAura',
            Constants.ABILITY_AURA_CHAINEDNIGHTMARE,
            'origin',
            'war3mapImported\\ChainedNightmareAura.mdx',
            RewardType.Auras
        )

        // Wings
        RewardsManager.AddRewardFromModelWithStats(
            'PhoenixWings',
            Constants.ABILITY_WINGS_PHOENIX,
            'chest',
            'war3mapImported\\PhoenixWing2.mdx',
            RewardType.Wings,
            'Saves',
            375
        )
        RewardsManager.AddRewardFromModelWithStats(
            'FairyWings',
            Constants.ABILITY_WINGS_FAIRY,
            'chest',
            'war3mapImported\\fairywing.mdx',
            RewardType.Wings,
            'Saves',
            275
        )
        RewardsManager.AddRewardFromModelWithStats(
            'NightmareWings',
            Constants.ABILITY_WINGS_NIGHTMARE,
            'chest',
            'war3mapImported\\WingsoftheNightmare2.mdx',
            RewardType.Wings,
            'Saves',
            325
        )
        RewardsManager.AddRewardFromModelWithStats(
            'ArchangelWings',
            Constants.ABILITY_WINGS_ARCHANGEL,
            'chest',
            'war3mapImported\\ArchangelWings2.mdx',
            RewardType.Wings,
            'Saves',
            425
        )
        RewardsManager.AddRewardFromModelWithStats(
            'CosmicWings',
            Constants.ABILITY_WINGS_COSMIC,
            'chest',
            'war3mapImported\\Wings: Void.mdx',
            RewardType.Wings,
            'Saves',
            550
        )
        RewardsManager.AddRewardFromModelWithStats(
            'VoidWings',
            Constants.ABILITY_WINGS_VOID,
            'chest',
            'war3mapImported\\Wings: Cosmic.mdx',
            RewardType.Wings,
            'Saves',
            500
        )
        RewardsManager.AddRewardFromModelWithStats(
            'ChaosWings',
            Constants.ABILITY_WINGS_CHAOS,
            'chest',
            'war3mapImported\\ChaosWingsResized2.mdx',
            RewardType.Wings,
            'Saves',
            450
        )
        RewardsManager.AddRewardFromModelWithStats(
            'PinkWings',
            Constants.ABILITY_WINGS_PINK,
            'chest',
            'war3mapImported\\PinkyWings2.mdx',
            RewardType.Wings,
            'Saves',
            600
        )
        RewardsManager.AddRewardFromModelWithStats(
            'NatureWings',
            Constants.ABILITY_WINGS_NATURE,
            'chest',
            'war3mapImported\\Wings2: Nature.mdx',
            RewardType.Wings,
            'Saves',
            750
        )

        // Tendrils
        RewardsManager.AddRewardFromModel(
            'RedTendrils',
            Constants.ABILITY_WINGS_TRED,
            'chest',
            'war3mapImported\\RedTendrils.mdx',
            RewardType.Wings
        )
        RewardsManager.AddRewardFromModel(
            'WhiteTendrils',
            Constants.ABILITY_WINGS_TWHITE,
            'chest',
            'war3mapImported\\WhiteTendrils.mdx',
            RewardType.Wings
        )
        RewardsManager.AddRewardFromModel(
            'DivinityTendrils',
            Constants.ABILITY_WINGS_TYELLOW,
            'chest',
            'war3mapImported\\YellowTendrils.mdx',
            RewardType.Wings
        )
        RewardsManager.AddRewardFromModel(
            'GreenTendrils',
            Constants.ABILITY_WINGS_TGREEN,
            'chest',
            'war3mapImported\\GreenTendrils.mdx',
            RewardType.Wings
        )
        RewardsManager.AddRewardFromModelWithStats(
            'PatrioticTendrils',
            Constants.ABILITY_WINGS_PATRIOTIC,
            'chest',
            'RedWhiteBlueTendrilsTest.mdx',
            RewardType.Wings,
            'SaveStreak',
            50
        )
        RewardsManager.AddRewardFromModel(
            'VioletWings',
            Constants.ABILITY_CHAMPION_WINGSTVIOLET,
            'chest',
            'war3mapImported\\VoidTendrilsWings.mdx',
            RewardType.Tournament
        )
        RewardsManager.AddRewardFromModel(
            'TurquoiseWings',
            Constants.ABILITY_CHAMPION_WINGSTURQUOISE,
            'chest',
            'war3mapImported\\TurquoiseWings.mdx',
            RewardType.Tournament
        )

        // Fires
        RewardsManager.AddRewardFromModel(
            'PurpleFire',
            Constants.ABILITY_TRAIL_FIREPURPLE,
            'origin',
            'war3mapImported\\PurpleFire.mdx',
            RewardType.Trails
        )
        RewardsManager.AddRewardFromModel(
            'BlueFire',
            Constants.ABILITY_TRAIL_FIREBLUE,
            'origin',
            'war3mapImported\\BlueFire.mdx',
            RewardType.Trails
        )
        RewardsManager.AddRewardFromModel(
            'TurquoiseFire',
            Constants.ABILITY_TRAIL_FIRETURQUOISE,
            'origin',
            'war3mapImported\\TurquoiseFire.mdx',
            RewardType.Trails
        )
        RewardsManager.AddRewardFromModel(
            'PinkFire',
            Constants.ABILITY_TRAIL_FIREPINK,
            'origin',
            'war3mapImported\\PinkFire.mdx',
            RewardType.Trails
        )
        RewardsManager.AddRewardFromModel(
            'WhiteFire',
            Constants.ABILITY_TRAIL_FIREWHITE,
            'origin',
            'war3mapImported\\WhiteFire.mdx',
            RewardType.Trails
        )

        // Nitros
        RewardsManager.AddRewardFromModel(
            'Nitro',
            Constants.ABILITY_NITRO,
            'origin',
            'war3mapImported\\Nitro.mdx',
            RewardType.Nitros
        )
        RewardsManager.AddRewardFromModel(
            'NitroBlue',
            Constants.ABILITY_NITROBLUE,
            'origin',
            'war3mapImported\\NitroBlue.mdx',
            RewardType.Nitros
        )
        RewardsManager.AddRewardFromModel(
            'NitroRed',
            Constants.ABILITY_NITRORED,
            'origin',
            'war3mapImported\\NitroRed.mdx',
            RewardType.Nitros
        )
        RewardsManager.AddRewardFromModel(
            'NitroGreen',
            Constants.ABILITY_NITROGREEN,
            'origin',
            'war3mapImported\\NitroGreen.mdx',
            RewardType.Nitros
        )
        RewardsManager.AddRewardFromModel(
            'NitroPurple',
            Constants.ABILITY_NITROPURPLE,
            'origin',
            'war3mapImported\\NitroPurple.mdx',
            RewardType.Nitros
        )
        RewardsManager.AddRewardFromModel(
            'TurquoiseNitro',
            Constants.ABILITY_CHAMION_NITROTURQUOISE,
            'origin',
            'war3mapImported\\NitroTurquoise.mdx',
            RewardType.Tournament
        )

        // Divine Lights
        RewardsManager.AddRewardFromModel(
            'DivineLight',
            Constants.ABILITY_TRAIL_DIVINELIGHT,
            'origin',
            'DivineLight.mdx',
            RewardType.Nitros
        )
        RewardsManager.AddRewardFromModel(
            'AzureLight',
            Constants.ABILITY_TRAIL_AZURELIGHT,
            'origin',
            'AzureLight.mdx',
            RewardType.Nitros
        )
        RewardsManager.AddRewardFromModel(
            'CrimsonLight',
            Constants.ABILITY_TRAIL_CRIMSONLIGHT,
            'origin',
            'CrimsonLight.mdx',
            RewardType.Nitros
        )
        RewardsManager.AddRewardFromModel(
            'EmeraldLight',
            Constants.ABILITY_TRAIL_EMERALDLIGHT,
            'origin',
            'EmeraldLight.mdx',
            RewardType.Nitros
        )
        RewardsManager.AddRewardFromModel(
            'VioletLight',
            Constants.ABILITY_TRAIL_VIOLETLIGHT,
            'origin',
            'VioletLight.mdx',
            RewardType.Nitros
        )
        RewardsManager.AddRewardFromModel(
            'PatrioticLight',
            Constants.ABILITY_TRAIL_PATRIOTICLIGHT,
            'origin',
            'PatrioticLight.mdx',
            RewardType.Nitros
        )

        // Lightning
        RewardsManager.AddRewardFromModelWithStats(
            'BlueLightning',
            Constants.ABILITY_TRAIL_LIGHTNINGBLUE,
            'origin',
            'war3mapImported\\GreatElderHydraLightningOrbV3.mdx',
            RewardType.Trails,
            'Saves',
            2000
        )
        RewardsManager.AddRewardFromModelWithStats(
            'RedLightning',
            Constants.ABILITY_TRAIL_LIGHTNINGRED,
            'origin',
            'war3mapImported\\RedLightning.mdx',
            RewardType.Trails,
            'SaveStreak',
            15
        )
        RewardsManager.AddRewardFromModel(
            'PurpleLightning',
            Constants.ABILITY_TRAIL_LIGHTNINGPURPLE,
            'origin',
            'war3mapImported\\PurpleLightning.mdx',
            RewardType.Trails
        )
        RewardsManager.AddRewardFromModel(
            'YellowLightning',
            Constants.ABILITY_TRAIL_LIGHTNINGYELLOW,
            'origin',
            'war3mapImported\\YellowLightning.mdx',
            RewardType.Trails
        )
        RewardsManager.AddRewardFromModel(
            'GreenLightning',
            Constants.ABILITY_TRAIL_LIGHTNINGGREEN,
            'origin',
            'war3mapImported\\GreenLightning.mdx',
            RewardType.Trails
        )
        // AddReward("LightningSpeed", Constants.ABILITY_AURA_BUTTERFLY, "origin", "lightning_shield.mdx", RewardType.Tournament);

        // WindWalks
        RewardsManager.AddRewardFromModel(
            'WWBlood',
            Constants.ABILITY_WW_BLOOD,
            'chest',
            'war3mapImported\\Blood: Windwalk.mdx',
            RewardType.Windwalks
        )
        RewardsManager.AddRewardFromModel(
            'WWBlue',
            Constants.ABILITY_WW_BLUE,
            'chest',
            'war3mapImported\\BlueWindwalk.mdx',
            RewardType.Windwalks
        )
        RewardsManager.AddRewardFromModel(
            'WWFire',
            Constants.ABILITY_WW_FIRE,
            'chest',
            'war3mapImported\\Fire: Windwalk.mdx',
            RewardType.Windwalks
        )
        RewardsManager.AddRewardFromModel(
            'WWNecro',
            Constants.ABILITY_WW_NECRO,
            'chest',
            'war3mapImported\\NecroWindwalk.mdx',
            RewardType.Windwalks
        )
        RewardsManager.AddRewardFromModel(
            'WWSwift',
            Constants.ABILITY_WW_SWIFT,
            'chest',
            'war3mapImported\\Windwalk.mdx',
            RewardType.Windwalks
        )
        RewardsManager.AddRewardFromModel(
            'WWDivine',
            Constants.ABILITY_WW_DIVINE,
            'chest',
            'war3mapImported\\WindwalkDivine.mdx',
            RewardType.Windwalks
        )
        RewardsManager.AddRewardFromModel(
            'WWViolet',
            Constants.ABILITY_WW_VIOLET,
            'chest',
            'war3mapImported\\Violet: Windwalk.mdx',
            RewardType.Windwalks
        )
        // Deathless
        RewardsManager.AddRewardFromModel(
            'NormalDeathless1',
            Constants.ABILITY_DEATHLESS_FIRE_1_01,
            'origin',
            'Doodads\\Cinematic\\FireRockSmall\\FireRockSmall.mdl',
            RewardType.Deathless
        )
        RewardsManager.AddRewardFromModel(
            'NormalDeathless2',
            Constants.ABILITY_DEATHLESS_FIRE_1_02,
            'origin',
            'war3mapImported\\Deathless2.mdx',
            RewardType.Deathless
        )
        RewardsManager.AddRewardFromModel(
            'NormalDeathless3',
            Constants.ABILITY_DEATHLESS_FIRE_1_03,
            'origin',
            'war3mapImported\\Deathless3.mdx',
            RewardType.Deathless
        )
        RewardsManager.AddRewardFromModel(
            'NormalDeathless4',
            Constants.ABILITY_DEATHLESS_FIRE_1_04,
            'origin',
            'war3mapImported\\Deathless4.mdx',
            RewardType.Deathless
        )
        RewardsManager.AddRewardFromModel(
            'NormalDeathless5',
            Constants.ABILITY_DEATHLESS_FIRE_1_05,
            'origin',
            'war3mapImported\\Deathless5.mdx',
            RewardType.Deathless
        )

        // Team Deathless
        RewardsManager.AddRewardFromModel(
            'NormalTeamDeathless',
            Constants.ABILITY_NORMAL_TEAM_DEATHLESS,
            'origin',
            'war3mapImported\\NormalTeamDeathless.mdx',
            RewardType.Deathless
        )
        RewardsManager.AddRewardFromModel(
            'HardTeamDeathless',
            Constants.ABILITY_HARD_TEAM_DEATHLESS,
            'origin',
            'war3mapImported\\HardTeamDeathless.mdx',
            RewardType.Deathless
        )
        RewardsManager.AddRewardFromModel(
            'ImpossibleTeamDeathless',
            Constants.ABILITY_IMPOSSIBLE_TEAM_DEATHLESS,
            'origin',
            'war3mapImported\\ImpossibleTeamDeathless.mdx',
            RewardType.Deathless
        )

        // Skins
        RewardsManager.AddRewardFromSkinWithStats(
            'UndeadKitty',
            Constants.ABILITY_SKIN_KITTYUNDEAD,
            Constants.UNIT_UNDEAD_KITTY,
            RewardType.Skins,
            'NormalWins',
            30
        )
        RewardsManager.AddRewardFromSkinWithStats(
            'HighelfKitty',
            Constants.ABILITY_SKIN_KITTYHIGHELF,
            Constants.UNIT_HIGHELF_KITTY,
            RewardType.Skins,
            'NormalGames',
            40
        )
        RewardsManager.AddRewardFromSkinWithStats(
            'AncientKitty',
            Constants.ABILITY_SKIN_KITTYANCIENT,
            Constants.UNIT_ANCIENT_KITTY,
            RewardType.Skins,
            'NormalWins',
            40
        )
        RewardsManager.AddRewardFromSkinWithStats(
            'SatyrKitty',
            Constants.ABILITY_SKIN_KITTYSATYR,
            Constants.UNIT_SATYR_KITTY,
            RewardType.Skins,
            'NormalWins',
            25
        )
        RewardsManager.AddRewardFromSkinWithStats(
            'AstralKitty',
            Constants.ABILITY_SKIN_KITTYASTRAL,
            Constants.UNIT_ASTRAL_KITTY,
            RewardType.Skins,
            'NormalGames',
            55
        )
        RewardsManager.AddRewardFromSkin(
            'ZandalariKitty',
            Constants.ABILITY_SKIN_KITTYZANDALARI,
            Constants.UNIT_ZANDALARI_KITTY,
            RewardType.Skins
        )
        RewardsManager.AddRewardFromSkin(
            'HuntressKitty',
            Constants.ABILITY_SKIN_KITTYHUNTRESS,
            Constants.UNIT_HUNTRESS_KITTY,
            RewardType.Skins
        )
        RewardsManager.AddRewardFromSkin(
            'PenguinSkin',
            Constants.ABILITY_CHAMPION_SKINPENGUIN,
            Constants.UNIT_PENGUIN,
            RewardType.Tournament
        )

        // Holiday
        RewardsManager.AddRewardFromModel(
            'SnowWings2023',
            Constants.ABILITY_HOLIDAY_WINGS_C2023,
            'chest',
            'war3mapImported\\SnowflakeWings.mdx',
            RewardType.Wings
        )
        RewardsManager.AddRewardFromModel(
            'SnowTrail2023',
            Constants.ABILITY_HOLIDAY_TRAIL_C2023,
            'origin',
            'war3mapImported\\snowtrail.mdx',
            RewardType.Trails
        )
    }
}
