using System.Collections.Generic;

public static class DecodeOldsave
{
    public static List<KeyValuePair<object, int>> decodeValues = new List<KeyValuePair<object, int>>
    {
        new KeyValuePair<object, int>(Awards.Butterfly_Aura, 1),
        new KeyValuePair<object, int>(Awards.Divinity_Tendrils, 1),
        new KeyValuePair<object, int>(Awards.Green_Tendrils, 1),
        new KeyValuePair<object, int>(Awards.Red_Tendrils, 1),
        new KeyValuePair<object, int>(Awards.White_Tendrils, 1),
        new KeyValuePair<object, int>(Awards.Green_Lightning, 1),
        new KeyValuePair<object, int>(Awards.Yellow_Lightning, 1),
        new KeyValuePair<object, int>(Awards.Purple_Lightning, 1),
        new KeyValuePair<object, int>(Awards.Red_Lightning, 1),
        new KeyValuePair<object, int>(Awards.WW_Swift, 1),
        new KeyValuePair<object, int>(Awards.WW_Necro, 1),
        new KeyValuePair<object, int>(Awards.WW_Fire, 1),
        new KeyValuePair<object, int>(Awards.WW_Blue, 1),
        new KeyValuePair<object, int>(Awards.WW_Blood, 1),
        new KeyValuePair<object, int>(Awards.Deathless_5, 1),
        new KeyValuePair<object, int>(Awards.Deathless_4, 1),
        new KeyValuePair<object, int>(Awards.Deathless_3, 1),
        new KeyValuePair<object, int>(Awards.Deathless_2, 1),
        new KeyValuePair<object, int>(Awards.Deathless_1, 1),
        new KeyValuePair<object, int>(Awards.White_Fire, 1),
        new KeyValuePair<object, int>(Awards.Pink_Fire, 1),
        new KeyValuePair<object, int>(Awards.Blue_Fire, 1),
        new KeyValuePair<object, int>(Awards.Turquoise_Fire, 1),
        new KeyValuePair<object, int>(Awards.Nitro_Purple, 1),
        new KeyValuePair<object, int>(Awards.Nitro_Green, 1),
        new KeyValuePair<object, int>(Awards.Nitro_Red, 1),
        new KeyValuePair<object, int>(Awards.Nitro_Blue, 1),
        new KeyValuePair<object, int>(Awards.Nitro, 1),
        new KeyValuePair<object, int>("RoundFiveNormal", 420),
        new KeyValuePair<object, int>("RoundFourNormal", 300),
        new KeyValuePair<object, int>("RoundThreeNormal", 300),
        new KeyValuePair<object, int>("RoundTwoNormal", 300),
        new KeyValuePair<object, int>("RoundOneNormal", 300),
        new KeyValuePair<object, int>("WinStreak", 100),
        new KeyValuePair<object, int>("NormalWins", 999),
        new KeyValuePair<object, int>("NormalGames", 9999),
        new KeyValuePair<object, int>("Saves", 99999),
        new KeyValuePair<object, int>("Deaths", 99999),
        new KeyValuePair<object, int>(Awards.Purple_Fire, 1),
        new KeyValuePair<object, int>(Awards.Patriotic_Tendrils, 1),
        new KeyValuePair<object, int>(Awards.Divine_Light, 1),
        new KeyValuePair<object, int>(Awards.Zandalari_Kitty, 1),
    };
}