import { Constants } from 'src/AutoGenerated/Constants'
import { Logger } from 'src/Events/Logger/Logger'
import { CurrentGameMode } from 'src/Gamemodes/CurrentGameMode'
import { GameMode } from 'src/Gamemodes/GameModeEnum'
import { GC } from 'src/Utility/GC'
import { Utility } from 'src/Utility/Utility'
import { getFilterUnit } from 'src/Utility/w3tsUtils'
import { Group, Item, Rectangle, Trigger, Unit } from 'w3ts'

export class Shops {
    private static KittyVendors: Group
    private static KittyVendorsList: Unit[]
    private static KittyVendorItemList: number[]
    private static VendorsItemList: Map<Unit, VendorItem[]>
    private static trigger: Trigger

    public static Initialize() {
        this.KittyVendors = Group.create()!
        this.trigger = Trigger.create()!
        this.KittyVendorsList = []
        this.KittyVendorItemList = []
        this.VendorsItemList = new Map()
        this.CollectAllVendors()
        this.SetupAllItems()
        this.ApplyItemListToVendor()
    }

    private static SetupAllItems() {
        this.ConstantItems()

        if (CurrentGameMode.active !== GameMode.Standard) return

        this.StandardModeItems()
    }

    private static ApplyItemListToVendor() {
        for (let vendor of this.KittyVendorsList) this.AddRegularItemsToVendor(vendor, this.KittyVendorItemList)
    }

    private static RefreshItemsOnVendor(vendor: Unit) {
        let vendorItems = this.VendorsItemList.get(vendor)!
        for (let item of vendorItems) vendor.addItemToStock(item.Item, item.Stock, item.Stock)
    }

    private static AddRegularItemsToVendor(vendor: Unit, items: number[]) {
        let vendorList: VendorItem[] = []
        for (let item of items) {
            vendorList.push(new VendorItem(vendor, item, 2, 60))
        }
        this.VendorsItemList.set(vendor, vendorList)
        this.RefreshItemsOnVendor(vendor)
    }

    /// <summary>
    /// No longer has use. Constant items will just remain in the editor.
    /// </summary>
    private static ConstantItems() {
        // Items for all modes
        /*        KittyVendorItemList.push(Constants.ITEM_ADRENALINE_POTION);
                KittyVendorItemList.push(Constants.ITEM_HEALING_WATER);
                KittyVendorItemList.push(Constants.ITEM_PEGASUS_BOOTS);
                KittyVendorItemList.push(Constants.ITEM_ENERGY_STONE);
                KittyVendorItemList.push(Constants.ITEM_MEDITATION_CLOAK);
                KittyVendorItemList.push(Constants.ITEM_RITUAL_MASK);
                KittyVendorItemList.push(Constants.ITEM_ELIXIR);
                KittyVendorItemList.push(Constants.ITEM_ANCIENT_TOME);*/
    }

    /// <summary>
    /// These items can go to the misc shop if we want space for constant items.
    /// </summary>
    private static StandardModeItems() {
        // Kitty Vendor
        this.KittyVendorItemList.push(Constants.ITEM_EASTER_EGG_EMPTY_VIAL)
        this.KittyVendorItemList.push(Constants.ITEM_EASTER_EGG_URN_OF_A_BROKEN_SOUL)
        this.KittyVendorItemList.push(Constants.ITEM_EASTER_EGG_CAT_FIGURINE)
    }

    private static CollectAllVendors() {
        let filter = Utility.CreateFilterFunc(() => getFilterUnit().typeId === Constants.UNIT_KITTY_VENDOR)
        this.KittyVendors.enumUnitsInRect(Rectangle.getWorldBounds()!, filter)
        this.KittyVendorsList = this.KittyVendors.getUnits()

        this.RegisterVendorSellingEvent()

        GC.RemoveFilterFunc(filter) // TODO; Cleanup:         GC.RemoveFilterFunc(ref filter);
    }

    private static RegisterVendorSellingEvent() {
        // Registers all Kitty Vendors and Panda Vendor for on sell event.
        for (let vendor of Shops.KittyVendorsList) this.trigger.registerUnitEvent(vendor, EVENT_UNIT_SELL_ITEM)
        this.trigger.addAction(() => Shops.OnVendorSell())
    }

    private static OnVendorSell() {
        try {
            let item = Item.fromHandle(GetSoldItem())!
            let vendor = Unit.fromHandle(GetSellingUnit())!
            const u = GetBuyingUnit()
            if (!u) return
            let player = GetOwningPlayer(u)
            let itemID = item.typeId

            let vendorItems = Shops.VendorsItemList.get(vendor)!
            let vendorItem = vendorItems.find(vi => vi.Item === itemID)
            if (vendorItem === null) return

            this.RefreshItemsOnVendor(vendor)
        } catch (e: any) {
            Logger.Warning(`Error in OnVendorSell: ${e}`)
        }
    }
}

export class VendorItem {
    public Vendor: Unit
    public Item = 0
    public Stock = 0
    public RestockTime = 0

    public constructor(vendor: Unit, item: number, stock: number, restockTime: number) {
        this.Vendor = vendor
        this.Item = item
        this.Stock = stock
        this.RestockTime = restockTime // May implement later? unsure.
    }
}
