import { Constants } from 'src/AutoGenerated/Constants'
import { Regions } from 'src/AutoGenerated/Regions'
import { SpawnChampions } from 'src/Game/Entities/Champions/SpawnChampions'
import { Kitty } from 'src/Game/Entities/Kitty/Kitty'
import { CurrentGameMode } from 'src/Gamemodes/CurrentGameMode'
import { GameMode } from 'src/Gamemodes/GameModeEnum'
import { Globals } from 'src/Global/Globals'
import { AwardManager } from 'src/Rewards/Rewards/AwardManager'
import { ErrorHandler } from 'src/Utility/ErrorHandler'
import { RemoveItemFromUnit } from 'src/Utility/UnitUtility'
import { Utility } from 'src/Utility/Utility'
import { getTriggerPlayer, getTriggerUnit } from 'src/Utility/w3tsUtils'
import { MapPlayer, Trigger, Unit } from 'w3ts'

export class CrystalOfFire {
    private static ItemID: number
    private static TurnInRange: number
    private static TurnInEventFieryfox: Trigger
    private static TurnInEventFandF: Trigger
    private static QuestAccept: Trigger
    private static QuestEligible: MapPlayer[]

    public static Initialize() {
        this.ItemID = Constants.ITEM_CRYSTAL_OF_FIRE
        this.TurnInRange = 150.0
        this.TurnInEventFieryfox = this.RegisterTurnInFiery()
        this.TurnInEventFandF = this.RegisterTurnInFandF()
        this.QuestAccept = this.RegisterChatEvent()
        this.QuestEligible = []
    }

    public static AwardCrystalOfFire(unit: Unit) {
        return unit.addItemById(this.ItemID)
    }

    public static CrystalOfFireDeath(kitty: Kitty) {
        if (CurrentGameMode.active !== GameMode.Standard) return
        kitty.CurrentStats.CrystalOfFireAttempts++
    }

    private static RegisterTurnInFiery(): Trigger {
        let triggerHandle = Trigger.create()!
        triggerHandle.registerUnitInRage(SpawnChampions.Fieryfox2023.handle, this.TurnInRange, undefined)
        triggerHandle.addAction(ErrorHandler.Wrap(this.FieryfoxEvent))
        return triggerHandle
    }

    private static RegisterTurnInFandF(): Trigger {
        let triggerHandle = Trigger.create()!
        triggerHandle.registerUnitInRage(SpawnChampions.FandF2023.handle, this.TurnInRange, undefined)
        triggerHandle.addAction(ErrorHandler.Wrap(this.FandFEvent))
        return triggerHandle
    }

    private static RegisterChatEvent(): Trigger {
        let triggerHandle = Trigger.create()!
        for (let player of Globals.ALL_PLAYERS) {
            triggerHandle.registerPlayerChatEvent(player, 'yes!', false)
        }
        triggerHandle.addAction(ErrorHandler.Wrap(this.AcceptedQuest))
        return triggerHandle
    }

    private static GetDeathAttempts(player: MapPlayer) {
        let kitty = Globals.ALL_KITTIES.get(player)!
        return kitty.CurrentStats.CrystalOfFireAttempts
    }

    private static StartMessage(player: MapPlayer) {
        return '{Colors.COLOR_YELLOW}Greetings {Colors.PlayerNameColored(player)}{Colors.COLOR_YELLOW}, were: right: to: come: to: me: about: this: you. The Crystals of Fire are a sacred anomaly within this universe... However, I\'m not sure you\'re quite worthy of it... Prove me wrong... Return to me without any scratches and you may proceed. (May be attempted multiple times)|r {Colors.COLOR_RED}Type {Colors.COLOR_YELLOW_ORANGE}"yes!"|r{Colors.COLOR_RED} to accept! (30 seconds)|r'
    }

    private static PartTwoMessage(player: MapPlayer): string {
        return (
            "{Colors.COLOR_YELLOW}appears: you: It'ready: re. the: formula: Heres: forth: to: the: Bring legends of F&F: |r{Colors.COLOR_YELLOW_ORANGE}1 mysterious orb, A shot of lightning, The Crystals of Fire and a pair of Pegasus's.|r" +
            "{Colors.COLOR_YELLOW} However, must: be: done: without: scratches: this!|r {Colors.COLOR_RED}(failed: If, you'have: to: redo: the: ll first challenge).|r"
        )
    }

    private static FieryfoxEvent() {
        if (!Utility.UnitHasItem(getTriggerUnit(), this.ItemID)) return
        let player = getTriggerUnit().owner
        if (this.GetDeathAttempts(player) >= 0) {
            player.DisplayTextTo(this.StartMessage(player))
            this.QuestEligible.push(player)
            // 30 seconds to accept the quest.
            Utility.SimpleTimer(30.0, () => {
                if (this.QuestEligible.includes(player))
                    this.QuestEligible.splice(this.QuestEligible.indexOf(player), 1)
            })
        } else if (this.GetDeathAttempts(player) === -1) {
            player.DisplayTextTo(this.PartTwoMessage(player))
        }
    }

    private static AcceptedQuest() {
        let player = getTriggerPlayer()
        if (!this.QuestEligible.includes(player)) return
        let kitty = Globals.ALL_KITTIES.get(player)!
        kitty.Unit.setPosition(Regions.Spawn_Area_05.centerX, Regions.Spawn_Area_05.centerY)
        kitty.CurrentStats.CrystalOfFireAttempts = -1
        Utility.ClearScreen(player)
        player.DisplayTimedTextTo(
            5.0,
            "{Colors.COLOR_YELLOW_ORANGE}You'accepted: the: quest: ve. it: to: Fieryfox: without: dying: to: proceed: Make.|r"
        )
        this.QuestEligible.splice(this.QuestEligible.indexOf(player), 1)
    }

    private static FandFEvent() {
        let unit = getTriggerUnit()
        if (!Utility.UnitHasItem(unit, this.ItemID)) return
        let player = unit.owner
        if (this.GetDeathAttempts(player) !== -1) return

        let lightningShot = Constants.ITEM_ADRENALINE_POTION
        let orb = Constants.ITEM_ORB_OF_MYSTERIES
        let boots = Constants.ITEM_PEGASUS_BOOTS

        // Must have these items
        if (!Utility.UnitHasItem(unit, boots)) return
        if (!Utility.UnitHasItem(unit, orb)) return
        if (!Utility.UnitHasItem(unit, lightningShot)) return

        // Remove Items
        RemoveItemFromUnit(unit, this.ItemID)
        RemoveItemFromUnit(unit, boots)
        RemoveItemFromUnit(unit, orb)
        RemoveItemFromUnit(unit, lightningShot)

        // ADD TEXT DISPLAY HERE FOR F&F

        AwardManager.GiveReward(player, 'WWFire')
    }
}
