import { Constants } from 'src/AutoGenerated/Constants'
import { Regions } from 'src/AutoGenerated/Regions'
import { Destructable, MapPlayer, Unit } from 'w3ts'

export class BarrierSetup {
    private static BARRIERID: number = FourCC('YTpb') // changed to call native only once
    private static BarrierActive: boolean
    private static DummyUnitOne: Unit
    private static DummyUnitTwo: Unit
    private static DummyUnitThree: Unit
    public static destructables: Destructable[] = []

    public static Initialize = () => {
        BarrierSetup.ActivateBarrier()
    }

    private static CreateDummyUnits = () => {
        const neutralPassive = MapPlayer.fromIndex(PLAYER_NEUTRAL_PASSIVE)!
        BarrierSetup.DummyUnitOne = Unit.create(
            neutralPassive,
            Constants.UNIT_DUMMY_1,
            Regions.Dummy1Region.centerX,
            Regions.Dummy1Region.centerY,
            360
        )!
        BarrierSetup.DummyUnitTwo = Unit.create(
            neutralPassive,
            Constants.UNIT_DUMMY_2,
            Regions.Dummy2Region.centerX,
            Regions.Dummy2Region.centerY,
            360
        )!
        BarrierSetup.DummyUnitThree = Unit.create(
            neutralPassive,
            Constants.UNIT_DUMMY_3,
            Regions.Dummy3Region.centerX,
            Regions.Dummy3Region.centerY,
            360
        )!
    }

    private static CreateBarrier = () => {
        const barrierRegion = Regions.BarrierRegion
        const centerX = barrierRegion.centerX
        const minY = barrierRegion.minY
        const maxY = barrierRegion.maxY

        const distanceY: number = maxY - minY
        const intervalY: number = distanceY / 13
        for (let i = 1; i < 13; i++) {
            const currentY: number = minY + i * intervalY
            const des = Destructable.create(BarrierSetup.BARRIERID, centerX, currentY)
            if (des) BarrierSetup.destructables.push(des)
        }
    }

    public static ActivateBarrier = () => {
        if (BarrierSetup.BarrierActive) return
        BarrierSetup.CreateDummyUnits()
        BarrierSetup.CreateBarrier()
        BarrierSetup.BarrierActive = true
    }

    public static DeactivateBarrier = () => {
        if (!BarrierSetup.BarrierActive) return
        BarrierSetup.DummyUnitOne.destroy()
        BarrierSetup.DummyUnitTwo.destroy()
        BarrierSetup.DummyUnitThree.destroy()
        for (const des of BarrierSetup.destructables) {
            des.destroy()
        }
        BarrierSetup.destructables = []
        BarrierSetup.BarrierActive = false
    }
}
