import { Constants } from 'src/AutoGenerated/Constants'
import { Kitty } from 'src/Game/Entities/Kitty/Kitty'
import { CurrentGameMode } from 'src/Gamemodes/CurrentGameMode'
import { GameMode } from 'src/Gamemodes/GameModeEnum'
import { Globals } from 'src/Global/Globals'

export class Resources {
    private static StartingGold: number = 100
    public static SaveExperience: number = 80
    public static SaveGold: number = 30
    public static SaveStreakMultiplier: number = 0.1
    public static SafezoneExperience: number = 100
    public static SafezoneGold: number = 20
    private static EndRoundBonusGold: number = 150 + 50 * Globals.ROUND
    private static EndRoundBonusXP: number = 550 * Globals.ROUND

    public static Initialize() {
        this.SetResourcesForGamemode()
        this.AdjustStartingGold()
    }

    public static BonusResources() {
        this.EndRoundBonusXP = 750 * Globals.ROUND
        this.EndRoundBonusGold = 150 + 50 * Globals.ROUND
        for (let player of Globals.ALL_PLAYERS) player.addGold(this.EndRoundBonusGold) // May or may not work.. We'll see.
        for (let [_, kitty] of Globals.ALL_KITTIES) kitty.Unit.experience += this.EndRoundBonusXP
    }

    public static StartingItems(kitty: Kitty) {
        let unit = kitty.Unit
        unit.addItemById(Constants.ITEM_ADRENALINE_POTION)
    }

    public static SaveGoldBonus(streak: number) {
        return this.SaveGold + this.SaveGold * (this.SaveStreakMultiplier * streak)
    }

    private static AdjustStartingGold() {
        for (let player of Globals.ALL_PLAYERS) {
            player.addGold(this.StartingGold)
        }
    }

    private static SetResourcesForGamemode() {
        if (CurrentGameMode.active === GameMode.Standard) this.StandardResources()
        else if (CurrentGameMode.active === GameMode.SoloTournament) this.SoloResources()
        else if (CurrentGameMode.active === GameMode.TeamTournament) this.TeamResources()
    }

    private static StandardResources() {
        this.StartingGold = 200
        this.SaveExperience = 80
        this.SaveGold = 25
    }

    private static SoloResources() {
        this.SaveExperience = 0
        this.SaveGold = 0
        this.EndRoundBonusXP = 0
    }

    private static TeamResources() {
        this.SaveExperience = 15
        this.SaveGold = 5
        this.EndRoundBonusXP = 0
    }
}
