class DecodeOldsave {
    private static awards: GameAwardsDataSorted = Globals.GAME_AWARDS_SORTED
    private static times: RoundTimesData = Globals.GAME_TIMES
    private static stats: GameStatsData = Globals.GAME_STATS

    public static decodeValues: { key: string; value: number }[] = [
        { key: 'ButterflyAura', value: 1 },
        { key: 'DivinityTendrils', value: 1 },
        { key: 'GreenTendrils', value: 1 },
        { key: 'RedTendrils', value: 1 },
        { key: 'WhiteTendrils', value: 1 },
        { key: 'GreenLightning', value: 1 },
        { key: 'YellowLightning', value: 1 },
        { key: 'PurpleLightning', value: 1 },
        { key: 'RedLightning', value: 1 },
        { key: 'WWSwift', value: 1 },
        { key: 'WWNecro', value: 1 },
        { key: 'WWFire', value: 1 },
        { key: 'WWBlue', value: 1 },
        { key: 'WWBlood', value: 1 },
        { key: 'NormalDeathless5', value: 1 },
        { key: 'NormalDeathless4', value: 1 },
        { key: 'NormalDeathless3', value: 1 },
        { key: 'NormalDeathless2', value: 1 },
        { key: 'NormalDeathless1', value: 1 },
        { key: 'WhiteFire', value: 1 },
        { key: 'PinkFire', value: 1 },
        { key: 'BlueFire', value: 1 },
        { key: 'TurquoiseFire', value: 1 },
        { key: 'NitroPurple', value: 1 },
        { key: 'NitroGreen', value: 1 },
        { key: 'NitroRed', value: 1 },
        { key: 'NitroBlue', value: 1 },
        { key: 'Nitro', value: 1 },
        { key: 'RoundFiveNormal', value: 420 },
        { key: 'RoundFourNormal', value: 300 },
        { key: 'RoundThreeNormal', value: 300 },
        { key: 'RoundTwoNormal', value: 300 },
        { key: 'RoundOneNormal', value: 300 },
        { key: 'WinStreak', value: 100 },
        { key: 'NormalWins', value: 999 },
        { key: 'NormalGames', value: 9999 },
        { key: 'Saves', value: 99999 },
        { key: 'Deaths', value: 99999 },
        { key: 'PurpleFire', value: 1 },
        { key: 'PatrioticTendrils', value: 1 },
        { key: 'DivineLight', value: 1 },
        { key: 'ZandalariKitty', value: 1 },
    ]
}
