import { Constants } from 'src/AutoGenerated/Constants'
import { Kitty } from 'src/Game/Entities/Kitty/Kitty'
import { Globals } from 'src/Global/Globals'
import { Colors } from 'src/Utility/Colors/Colors'
import { ColorUtils } from 'src/Utility/Colors/ColorUtils'
import { Utility } from 'src/Utility/Utility'
import { MapPlayer, Unit } from 'w3ts'
import { PlayerUpgrades } from '../PlayerUpgrades'
import { Relic } from '../Relic'
import { RelicUpgrade } from '../RelicUpgrade'

export class BeaconOfUnitedLifeforce extends Relic {
    public static RelicItemID: number = Constants.ITEM_BEACON_OF_UNITED_LIFEFORCE
    private static INVULNERABILITY_DURATION = 1.0
    private static EXTRA_REVIVE_CHANCE_SINGLE = 0.125 // 12.5%
    private static EXTRA_REVIVE_CHANCE_ALL = 0.0175 // 1.75%
    private static EXTRA_REVIVE_CHANCE_SINGLE_UPGRADE = 0.01 // 1%
    private static IconPath: string = 'war3mapImported\\BTNTicTac.blp'
    private static RelicCost = 650
    private static ReviveChance: number = BeaconOfUnitedLifeforce.EXTRA_REVIVE_CHANCE_SINGLE

    private Owner: MapPlayer | null

    public constructor() {
        super(
            '|cff1e90ffBeacon of United Lifeforce|r',
            `Gives the owner a chance to revive an extra Kitty whenever they revive someone. ${Colors.COLOR_LIGHTBLUE}(Passive)|r`,
            0,
            BeaconOfUnitedLifeforce.RelicItemID,
            BeaconOfUnitedLifeforce.RelicCost,
            BeaconOfUnitedLifeforce.IconPath
        )

        this.Upgrades.push(
            new RelicUpgrade(
                0,
                `Your extra revive chance is increased by ${Math.ceil(BeaconOfUnitedLifeforce.EXTRA_REVIVE_CHANCE_SINGLE_UPGRADE * 100)}%.`,
                15,
                800
            )
        )
        this.Upgrades.push(
            new RelicUpgrade(1, 'Each revive has a VERY small chance to simply revive all dead players.', 20, 1000)
        )
    }

    public override ApplyEffect(Unit: Unit) {
        this.Owner = Unit.owner
        Utility.SimpleTimer(0.1, this.UpgradeReviveChance)
    }

    public override RemoveEffect(Unit: Unit) {
        this.Owner = null
    }

    public BeaconOfUnitedLifeforceEffect(player: MapPlayer) {
        // Make sure person has the relic
        if (player !== this.Owner) return
        let kitty = Globals.ALL_KITTIES.get(player)!
        if (!Utility.UnitHasItem(kitty.Unit, Constants.ITEM_BEACON_OF_UNITED_LIFEFORCE)) return

        let upgradeLevel = PlayerUpgrades.GetPlayerUpgrades(kitty.Player).GetUpgradeLevel(
            typeof BeaconOfUnitedLifeforce
        )

        let chance = GetRandomReal(0.0, 1.0)

        if (chance > BeaconOfUnitedLifeforce.ReviveChance) return

        // Revive all kitties if chance <= EXTRA_REVIVE_CHANCE_ALL, otherwise revive one kitty
        let reviveAll: boolean = chance <= BeaconOfUnitedLifeforce.EXTRA_REVIVE_CHANCE_ALL
        if (upgradeLevel < 2) reviveAll = false

        let color = Colors.COLOR_YELLOW_ORANGE
        let msgSent = false
        for (let [_, k] of Globals.ALL_KITTIES) {
            if (k.isAlive()) continue

            k.ReviveKitty(kitty)
            this.Invulnerability(kitty, k)

            if (!reviveAll)
                Utility.TimedTextToAllPlayers(
                    3.0,
                    `${ColorUtils.PlayerNameColored(k.Player)}${color} has been extra revived by ${ColorUtils.PlayerNameColored(kitty.Player)}!|r`
                )
            if (!reviveAll) break
            if (!msgSent)
                Utility.TimedTextToAllPlayers(
                    3.0,
                    `${ColorUtils.PlayerNameColored(kitty.Player)}${color} has extra revived all dead players!|r`
                )
            msgSent = true
        }
    }

    /// <summary>
    /// Gives the revived kitty invulnerability for a short duration.
    /// </summary>
    /// <param name="beaconHolder"></param>
    /// <param name="extraRevivedKitty"></param>
    private Invulnerability(beaconHolder: Kitty, extraRevivedKitty: Kitty) {
        extraRevivedKitty.Invulnerable = true
        Utility.SimpleTimer(
            BeaconOfUnitedLifeforce.INVULNERABILITY_DURATION,
            () => (extraRevivedKitty.Invulnerable = false)
        )
    }

    /// <summary>
    /// Upgrade Level 1: Increases the revive chance of the relic.
    /// </summary>
    private UpgradeReviveChance() {
        let upgradeLevel = PlayerUpgrades.GetPlayerUpgrades(this.Owner!).GetUpgradeLevel(typeof BeaconOfUnitedLifeforce)
        if (upgradeLevel >= 1)
            BeaconOfUnitedLifeforce.ReviveChance =
                BeaconOfUnitedLifeforce.EXTRA_REVIVE_CHANCE_SINGLE +
                BeaconOfUnitedLifeforce.EXTRA_REVIVE_CHANCE_SINGLE_UPGRADE
    }
}
