import { Constants } from 'src/AutoGenerated/Constants'
import { Kitty } from 'src/Game/Entities/Kitty/Kitty'
import { ProtectionOfAncients } from 'src/Game/ProtectionOfAncients'
import { Globals } from 'src/Global/Globals'
import { Colors } from 'src/Utility/Colors/Colors'
import { Utility } from 'src/Utility/Utility'
import { MapPlayer, Unit } from 'w3ts'
import { PlayerUpgrades } from '../PlayerUpgrades'
import { Relic } from '../Relic'
import { RelicUpgrade } from '../RelicUpgrade'

export class OneOfNine extends Relic {
    public static RelicItemID: number = Constants.ITEM_ONE_OF_NINE
    public static RelicAbilityID: number = Constants.ABILITY_PROTECTION_OF_THE_ANCIENTS_WITH_RELIC

    private PreviousAbilityID = Constants.ABILITY_PROTECTION_OF_THE_ANCIENTS
    private static RelicCost = 650
    private static IconPath: string = 'war3mapImported\\BTNSpell_Holy_BlessingOfProtection.blp'

    public constructor() {
        super(
            `${Colors.COLOR_RED}One of Nine`,
            `Autocasts Protection of the Ancients if it is available. ${Colors.COLOR_LIGHTBLUE}(Passive)|r`,
            OneOfNine.RelicAbilityID,
            OneOfNine.RelicItemID,
            OneOfNine.RelicCost,
            OneOfNine.IconPath
        )

        this.Upgrades.push(
            new RelicUpgrade(
                0,
                'Cooldown of your ultimate is reduced by an additional 3 seconds per upgrade level.',
                15,
                800
            )
        )

        this.Upgrades.push(new RelicUpgrade(1, 'Your ultimate no longer costs mana.', 20, 1000))
    }
    public override ApplyEffect(Unit: Unit) {
        const player: MapPlayer = Unit.owner
        const cooldown: number = OneOfNine.GetOneOfNineCooldown(player)
        Unit.removeAbility(this.PreviousAbilityID)
        Unit.addAbility(OneOfNine.RelicAbilityID)
        const abilityLevel: number = ProtectionOfAncients.SetProtectionOfAncientsLevel(Unit)
        BlzStartUnitAbilityCooldown(Unit.handle, OneOfNine.RelicAbilityID, cooldown)
        this.RemoveManaCost(Unit, abilityLevel)
    }

    public override RemoveEffect(Unit: Unit) {
        const player: MapPlayer = Unit.owner
        const cooldown: number = OneOfNine.GetOneOfNineCooldown(player)
        Unit.removeAbility(OneOfNine.RelicAbilityID)
        Unit.addAbility(this.PreviousAbilityID)
        ProtectionOfAncients.SetProtectionOfAncientsLevel(Unit)
        BlzStartUnitAbilityCooldown(Unit.handle, this.PreviousAbilityID, cooldown)
    }

    public static GetOneOfNineCooldown = (Player: MapPlayer) => {
        const kitty: Unit = Globals.ALL_KITTIES.get(Player)!.Unit
        const noRelic = Constants.ABILITY_PROTECTION_OF_THE_ANCIENTS
        const relic = Constants.ABILITY_PROTECTION_OF_THE_ANCIENTS_WITH_RELIC
        const reduction = OneOfNine.GetOneOfNineReduction(Player)

        // remaining cooldown depending on relic or no relic
        let cooldown: number =
            kitty.getAbilityCooldownRemaining(noRelic) > 0.0
                ? kitty.getAbilityCooldownRemaining(noRelic)
                : kitty.getAbilityCooldownRemaining(relic)

        cooldown -= reduction

        return Math.max(0.0, cooldown) // gotta make sure its not negative
    }

    public static GetOneOfNineReduction = (Player: MapPlayer) => {
        return PlayerUpgrades.GetPlayerUpgrades(Player).GetUpgradeLevel(OneOfNine.name) * 3.0
    }

    /// <summary>
    /// Upgrade Level 2: Removes mana cost from the ability.
    /// </summary>
    /// <param name="Unit"></param>
    /// <param name="abilityLevel"></param>
    private RemoveManaCost = (Unit: Unit, abilityLevel: number) => {
        const upgradeLevel = PlayerUpgrades.GetPlayerUpgrades(Unit.owner).GetUpgradeLevel(OneOfNine.name)
        if (upgradeLevel < 2) return
        Unit.getAbility(OneOfNine.RelicAbilityID)
        Unit.setAbilityManaCost(OneOfNine.RelicAbilityID, abilityLevel - 1, 0)
    }

    public static OneOfNineEffect = (kitty: Kitty) => {
        if (!Utility.UnitHasItem(kitty.Unit, Constants.ITEM_ONE_OF_NINE)) return false
        if (kitty.Unit.getAbilityCooldownRemaining(Constants.ABILITY_PROTECTION_OF_THE_ANCIENTS_WITH_RELIC) <= 0.0) {
            kitty.Unit.issueImmediateOrder('divineshield')
            return true
        }
        return false
    }
}
