declare var gg_rct_Bronze_medal: rect
declare var gg_rct_Circle_Area: rect
declare var gg_rct_Deaths: rect
declare var gg_rct_Gold_Medal: rect
declare var gg_rct_Podium_1: rect
declare var gg_rct_Podium_2: rect
declare var gg_rct_Podium_3: rect
declare var gg_rct_Podium_4: rect
declare var gg_rct_Podium_5: rect
declare var gg_rct_Podium_cinematic: rect
declare var gg_rct_safe_Area_01: rect
declare var gg_rct_safe_Area_02: rect
declare var gg_rct_safe_Area_03: rect
declare var gg_rct_safe_Area_04: rect
declare var gg_rct_safe_Area_05: rect
declare var gg_rct_safe_Area_06: rect
declare var gg_rct_safe_Area_07: rect
declare var gg_rct_safe_Area_08: rect
declare var gg_rct_safe_Area_09: rect
declare var gg_rct_safe_Area_10: rect
declare var gg_rct_safe_Area_11: rect
declare var gg_rct_safe_Area_12: rect
declare var gg_rct_safe_Area_13: rect
declare var gg_rct_safe_Area_14: rect
declare var gg_rct_Saves: rect
declare var gg_rct_Savior_Medal: rect
declare var gg_rct_Score_1: rect
declare var gg_rct_Score_2: rect
declare var gg_rct_Score_3: rect
declare var gg_rct_Silver_medal: rect
declare var gg_rct_Spawn_Area_01: rect
declare var gg_rct_Spawn_Area_02: rect
declare var gg_rct_Spawn_Area_03: rect
declare var gg_rct_Spawn_Area_04: rect
declare var gg_rct_Spawn_Area_05: rect
declare var gg_rct_Spawn_Area_06: rect
declare var gg_rct_Spawn_Area_07: rect
declare var gg_rct_Spawn_Area_08: rect
declare var gg_rct_Spawn_Area_09: rect
declare var gg_rct_Spawn_Area_10: rect
declare var gg_rct_Spawn_Area_11: rect
declare var gg_rct_Spawn_Camera: rect
declare var gg_rct_Survivor_Medal: rect
declare var gg_rct_Victory_Area: rect
declare var gg_rct_Wolf_Area_01: rect
declare var gg_rct_Wolf_Area_02: rect
declare var gg_rct_Wolf_Area_03: rect
declare var gg_rct_Wolf_Area_04: rect
declare var gg_rct_Wolf_Area_05: rect
declare var gg_rct_Wolf_Area_06: rect
declare var gg_rct_Wolf_Area_07: rect
declare var gg_rct_Wolf_Area_08: rect
declare var gg_rct_Wolf_Area_09: rect
declare var gg_rct_Wolf_Area_10: rect
declare var gg_rct_Wolf_Area_11: rect
declare var gg_rct_Wolf_Area_12: rect
declare var gg_rct_Wolf_Area_13: rect
declare var gg_rct_Wolf_Area_14: rect
declare var gg_rct_Wolf_Area_15: rect
declare var gg_rct_Wolf_Area_16: rect
declare var gg_rct_Wolf_Area_17: rect
declare var gg_rct_ProgressPoint1: rect
declare var gg_rct_ProgressPoint2: rect
declare var gg_rct_Urn_Soul_Region: rect
declare var gg_rct_UrnSoulRegion1: rect
declare var gg_rct_UrnSoulRegion2: rect
declare var gg_rct_UrnSoulRegion3: rect
declare var gg_rct_UrnSoulRegion4: rect
declare var gg_rct_safe_Area_00: rect
declare var gg_rct_PandaRelicText: rect
declare var gg_rct_ProgressPoint3: rect
declare var gg_rct_Dummy1Region: rect
declare var gg_rct_Dummy2Region: rect
declare var gg_rct_Dummy3Region: rect
declare var gg_rct_BarrierRegion: rect
declare var gg_rct_Solo2023: rect
declare var gg_rct_Team2023: rect
declare var gg_rct_Solo2024: rect
declare var gg_rct_Team2024: rect
declare var gg_snd_Human1: string
declare var gg_snd_Human2: string
declare var gg_snd_Human3: string
declare var gg_snd_Orc1: string
declare var gg_snd_Orc2: string
declare var gg_snd_Orc3: string
declare var gg_snd_Undead1: string
declare var gg_snd_Undead3: string
declare var gg_snd_Undead2: string
