import { Regions } from 'src/AutoGenerated/Regions'
import { Kitty } from 'src/Game/Entities/Kitty/Kitty'
import { ItemSpatialGrid } from 'src/Game/Items/ItemSpatialGrid'
import { Globals } from 'src/Global/Globals'
import { getTriggerPlayer } from 'src/Utility/w3tsUtils'
import { MapPlayer, Timer, Trigger, Unit } from 'w3ts'

export class FirstPersonCamera {
    private timerPeriod = 0.001
    private FIRSTPERSON_ANGLE_PER_PERIOD = 0.3

    private forceCamTimer: Timer | undefined
    private hero: Unit
    private player: MapPlayer
    private keyDownState: Map<string, boolean>
    private lastUnitAnimation: string | undefined

    public constructor(hero: Unit, player: MapPlayer) {
        this.hero = hero
        this.player = player
        this.keyDownState = new Map<string, boolean>([
            ['UP', false],
            ['DOWN', false],
            ['LEFT', false],
            ['RIGHT', false],
        ])
    }

    public IsFirstPerson() {
        return !!this.forceCamTimer
    }

    public ToggleFirstPerson = (active: boolean) => {
        if (active) {
            if (!this.forceCamTimer) {
                this.forceCamTimer = Timer.create()
                this.forceCamTimer.start(this.timerPeriod, true, this.UpdateCamera)
            }
        } else {
            if (!!this.forceCamTimer) {
                this.forceCamTimer.pause()
                this.forceCamTimer.destroy()
                this.ResetCamera()
            }
        }
    }

    private UpdateCamera = () => {
        if (!this.hero || !this.hero.isAlive()) return

        let fwd = 0

        if (
            !(this.keyDownState.get('LEFT') && this.keyDownState.get('RIGHT')) &&
            (this.keyDownState.get('LEFT') || this.keyDownState.get('RIGHT'))
        ) {
            let angle = this.hero.facing
            if (this.keyDownState.get('LEFT')) angle += this.FIRSTPERSON_ANGLE_PER_PERIOD
            if (this.keyDownState.get('RIGHT')) angle -= this.FIRSTPERSON_ANGLE_PER_PERIOD
            this.hero.setFacingEx(angle)
        }

        if (
            !(this.keyDownState.get('UP') && this.keyDownState.get('DOWN')) &&
            (this.keyDownState.get('UP') || this.keyDownState.get('DOWN'))
        ) {
            const moveSpeed = this.hero.moveSpeed
            let movePerTick = moveSpeed * this.timerPeriod

            const kitty: Kitty = Globals.ALL_KITTIES.get(this.player)!

            if (kitty.Slider.IsEnabled()) {
                movePerTick = 0.2
            }

            const angle = Rad2Deg(this.hero.facing)
            if (this.keyDownState.get('UP')) fwd += movePerTick
            if (this.keyDownState.get('DOWN')) fwd -= movePerTick

            const oldX = this.hero.x
            const oldY = this.hero.y

            let newX = oldX + fwd * Cos(angle)
            let newY = oldY + fwd * Sin(angle)

            if (!Globals.GAME_ACTIVE && Regions.BarrierRegion.includes(newX, newY)) {
                return
            }

            if (IsTerrainPathable(newX, oldY, PATHING_TYPE_WALKABILITY)) {
                newX = oldX
            }

            if (IsTerrainPathable(oldX, newY, PATHING_TYPE_WALKABILITY)) {
                newY = oldY
            }

            this.hero.setPathing(false)
            this.hero.setPosition(newX, newY)
            this.hero.setPathing(true)
        }

        if (fwd === 0) {
            if (this.lastUnitAnimation !== 'stand') {
                this.lastUnitAnimation = 'stand'
                this.hero.setAnimation(0) // 0 is stand for most units
            }
        } else {
            if (this.lastUnitAnimation !== 'walk') {
                this.lastUnitAnimation = 'walk'
                this.hero.setAnimation(6) // POTM is 6 for walk
            }
        }

        SetCameraTargetControllerNoZForPlayer(this.player.handle, this.hero.handle, 0, 0, true)
        SetCameraFieldForPlayer(this.player.handle, CAMERA_FIELD_ANGLE_OF_ATTACK, 310, 0)
        SetCameraFieldForPlayer(this.player.handle, CAMERA_FIELD_FIELD_OF_VIEW, 1500, 0)
        SetCameraFieldForPlayer(this.player.handle, CAMERA_FIELD_ROTATION, this.hero.facing, 0)
        SetCameraFieldForPlayer(this.player.handle, CAMERA_FIELD_ZOFFSET, 100, 0)

        this.ItemPickup()
    }

    public SetKeyDownState = (key: string, state: boolean) => {
        if (this.keyDownState.has(key)) {
            this.keyDownState.set(key, state)
        }
    }

    private ResetCamera = () => {
        if (!this.player.isLocal()) return
        SetCameraTargetControllerNoZForPlayer(this.player.handle, this.hero.handle, 0, 0, false)
        ResetToGameCamera(0)
        SetCameraField(CAMERA_FIELD_TARGET_DISTANCE, 2400.0, 0.0)
    }

    private ItemPickup = () => {
        const kitty: Kitty = Globals.ALL_KITTIES.get(this.player)!
        ItemSpatialGrid.KittyItemPickup(kitty)
    }
}

export class FirstPersonCameraManager {
    private static cameras: Map<MapPlayer, FirstPersonCamera> = new Map()

    public static Initialize = () => {
        for (const player of Globals.ALL_PLAYERS) {
            const hero = FirstPersonCameraManager.GetHeroForPlayer(player)
            if (!!hero) {
                FirstPersonCameraManager.cameras.set(player, new FirstPersonCamera(hero, player))
            }
        }

        FirstPersonCameraManager.RegisterKeyEvents()
    }

    private static RegisterKeyEvents = () => {
        const keyStates: Map<boolean, number> = new Map([
            [true, bj_KEYEVENTTYPE_DEPRESS],
            [false, bj_KEYEVENTTYPE_RELEASE],
        ])

        const keys: Map<string, number> = new Map([
            ['UP', bj_KEYEVENTKEY_UP],
            ['DOWN', bj_KEYEVENTKEY_DOWN],
            ['LEFT', bj_KEYEVENTKEY_LEFT],
            ['RIGHT', bj_KEYEVENTKEY_RIGHT],
        ])

        for (const [k, v] of keyStates) {
            for (const [k2, v2] of keys) {
                for (const p of Globals.ALL_PLAYERS) {
                    const keyTrigger = Trigger.create()!
                    const localKey = k2 // Create a local copy of the key
                    const localValue = k // Create a local copy of the value
                    TriggerRegisterPlayerKeyEventBJ(keyTrigger.handle, p.handle, v, v2)
                    keyTrigger.addAction(() => FirstPersonCameraManager.OnKeyEvent(localKey, localValue))
                }
            }
        }
    }

    private static OnKeyEvent = (key: string, isDown: boolean) => {
        if (FirstPersonCameraManager.cameras.has(getTriggerPlayer())) {
            FirstPersonCameraManager.cameras.get(getTriggerPlayer())!.SetKeyDownState(key, isDown)
        }
    }

    private static GetHeroForPlayer(player: MapPlayer): Unit {
        return Globals.ALL_KITTIES.has(player) ? Globals.ALL_KITTIES.get(player)!.Unit : (null as never)
    }

    public static ToggleFirstPerson = (player: MapPlayer) => {
        if (FirstPersonCameraManager.cameras.has(player)) {
            FirstPersonCameraManager.cameras
                .get(player)!
                .ToggleFirstPerson(!FirstPersonCameraManager.cameras.get(player)!.IsFirstPerson())
        }
    }

    public static SetFirstPerson = (player: MapPlayer, active: boolean) => {
        if (FirstPersonCameraManager.cameras.has(player)) {
            FirstPersonCameraManager.cameras.get(player)!.ToggleFirstPerson(active)
        }
    }
}
