udg_UnitStatIcon = __jarray("")
gg_rct_BoA_Revive_Area = nil
gg_rct_Bronze_medal = nil
gg_rct_Circle_Area = nil
gg_rct_Clan_RD = nil
gg_rct_Clan_RD2 = nil
gg_rct_PodiumDeathsScore = nil
gg_rct_Gold_Medal = nil
gg_rct_InitialSpawn = nil
gg_rct_PandaArea = nil
gg_rct_PandaText = nil
gg_rct_PoA2_ReviveArea = nil
gg_rct_PoA3_Revive_Area = nil
gg_rct_Podium_1 = nil
gg_rct_PodiumDeaths = nil
gg_rct_PodiumMVP = nil
gg_rct_PodiumSabotages = nil
gg_rct_PodiumSaves = nil
gg_rct_Podium_cinematic = nil
gg_rct_safe_Area_01 = nil
gg_rct_safe_Area_02 = nil
gg_rct_safe_Area_03 = nil
gg_rct_safe_Area_04 = nil
gg_rct_safe_Area_05 = nil
gg_rct_safe_Area_06 = nil
gg_rct_safe_Area_07 = nil
gg_rct_safe_Area_08 = nil
gg_rct_safe_Area_09 = nil
gg_rct_safe_Area_10 = nil
gg_rct_safe_Area_11 = nil
gg_rct_safe_Area_12 = nil
gg_rct_safe_Area_13 = nil
gg_rct_safe_Area_14 = nil
gg_rct_Saves = nil
gg_rct_MVPTAG = nil
gg_rct_PodiumMVPScore = nil
gg_rct_PodiumSabotageScore = nil
gg_rct_PodiumSavesScore = nil
gg_rct_MostSavesTag = nil
gg_rct_Spawn_Area_01 = nil
gg_rct_Spawn_Area_02 = nil
gg_rct_Spawn_Area_03 = nil
gg_rct_Spawn_Area_04 = nil
gg_rct_Spawn_Area_05 = nil
gg_rct_Spawn_Area_06 = nil
gg_rct_Spawn_Area_07 = nil
gg_rct_Spawn_Area_08 = nil
gg_rct_Spawn_Area_09 = nil
gg_rct_Spawn_Area_10 = nil
gg_rct_Spawn_Area_11 = nil
gg_rct_Spawn_Camera = nil
gg_rct_LeastDeathsTag = nil
gg_rct_Victory_Area = nil
gg_rct_Wolf_Area_01 = nil
gg_rct_Wolf_Area_02 = nil
gg_rct_Wolf_Area_03 = nil
gg_rct_Wolf_Area_04 = nil
gg_rct_Wolf_Area_05 = nil
gg_rct_Wolf_Area_06 = nil
gg_rct_Wolf_Area_07 = nil
gg_rct_Wolf_Area_08 = nil
gg_rct_Wolf_Area_09 = nil
gg_rct_Wolf_Area_10 = nil
gg_rct_Wolf_Area_11 = nil
gg_rct_Wolf_Area_12 = nil
gg_rct_Wolf_Area_13 = nil
gg_rct_Wolf_Area_14 = nil
gg_rct_Wolf_Area_15 = nil
gg_rct_Wolf_Area_16 = nil
gg_rct_Wolf_Area_17 = nil
gg_rct_ClearLaneArea12 = nil
gg_rct_Region_050 = nil
gg_rct_safe_Area_00 = nil
gg_rct_Fieryfox = nil
gg_rct_FinishZone = nil
gg_rct_TeamRed = nil
gg_rct_TeamBlue = nil
gg_rct_TeamTeal = nil
gg_rct_P1 = nil
gg_rct_P2 = nil
gg_rct_P3 = nil
gg_rct_P4 = nil
gg_rct_P5 = nil
gg_rct_P6 = nil
gg_rct_P7 = nil
gg_rct_P8 = nil
gg_rct_P9 = nil
gg_rct_P10 = nil
gg_rct_P11 = nil
gg_rct_P12 = nil
gg_rct_SabotageTag = nil
gg_rct_LightningTLeft = nil
gg_rct_LightningTRight = nil
gg_rct_LightningBLeft = nil
gg_rct_LightningBRight = nil
gg_rct_TRegion1 = nil
gg_rct_TRegion2 = nil
gg_rct_TRegion3 = nil
gg_snd_Round01 = nil
gg_snd_Round02 = nil
gg_snd_Round03 = nil
gg_snd_Round04 = nil
gg_snd_Vitality = nil
gg_snd_Brutality = nil
gg_snd_FinalRound = nil
gg_snd_TestYourLuck = nil
gg_snd_FirstBlood = nil
gg_snd_Announcer_kill_godlike_01 = nil
gg_snd_Announcer_kill_holy_01 = nil
gg_snd_wicked_sick_unreal_sound_effect = nil
gg_snd_unstoppable_quake_3_arena_sound_effect = nil
gg_snd_last_man_standing = nil
gg_snd_Speed = nil
gg_snd_Invulnerable = nil
gg_snd_Victory_fanfare = ""
gg_snd_Numb_compress = nil
gg_snd_basshunter_dota_hq = nil
gg_snd_In_The_End__Official_Video____Linkin_Park2 = nil
gg_snd_NumbNC = nil
gg_snd_NEFFEX_Cold = nil
gg_snd_K_391__Alan_Walker___Ahrix___End_of_Time = nil
gg_snd_R3hab_You_Could_Be = nil
gg_snd_Halsey___Without_Me__Illenium_Remix_u = nil
gg_snd_R3HAB_Lullaby = nil
gg_snd_KSHMR___Hard_Lights___Over_and_Out = nil
gg_snd_KSHMR___7_Skies___Neverland = nil
gg_snd_In_The_End__MG_TP_u = nil
gg_snd_nightcore_tonight_dj_gollum_feat_dj_cap_remix_edit_tomtrax_orca = nil
gg_snd_Breaking_Benjamin___Diary_Of_Jane = nil
gg_snd_Remember_The_Name___Fort_Minor = nil
gg_snd_linkin_park_numb = nil
gg_snd_linkin_park_numb01 = ""
gg_snd_Mix = nil
gg_trg_Start = nil
gg_rct_BarrierRegion = nil
gg_rct_Dummy1Region = nil
gg_rct_Dummy2Region = nil
gg_rct_Dummy3Region = nil
function InitGlobals()
local i = 0

i = 0
while (true) do
if ((i > 1)) then break end
udg_UnitStatIcon[i] = ""
i = i + 1
end
end

--[[
CustomStatFrame 1.3
By Tasyen
That are the stuff one uses to access the customstat frames.
	CustomStatFrames.BoxS a parent for simpleframes hide it to easyly hide all of them
	CustomStatFrames.BoxF parent of the frames
	CustomStatFrames[index].Frame
	CustomStatFrames[index].FrameIcon = The icon of that CustomStat
	CustomStatFrames[index].FrameText = The Text of that CustomStat
	CustomStatFrames[index].FrameHover = Handle the mousehovering
	CustomStatFrames[index].ToolTipBox = The box of the tooltip
	CustomStatFrames[index].ToolTipTitle = The Title of the tooltip
	CustomStatFrames[index].ToolTipText = The text of the tooltip

--]]

CustomStatFrames = {Count = 0}
CustomStatSelectedUnit = {}
function CustomStatAdd(icon, text)
	CustomStatFrames.Count = CustomStatFrames.Count + 1
	
	local fh = BlzCreateSimpleFrame("CustomStat", CustomStatFrames.BoxS, CustomStatFrames.Count)
	local tooltipBox = BlzCreateFrame("BoxedText", CustomStatFrames.BoxF,0, CustomStatFrames.Count)
	local fhHover = BlzGetFrameByName("CustomStatToolTip", CustomStatFrames.Count)
	BlzFrameSetTooltip(fh, fhHover)
	BlzFrameSetVisible(fhHover, false)
	
	BlzFrameSetAbsPoint(tooltipBox, FRAMEPOINT_BOTTOM, 0.6, 0.2)
	BlzFrameSetSize(tooltipBox, 0.15, 0.08)

	BlzFrameSetText(BlzGetFrameByName("CustomStatText", CustomStatFrames.Count), text)
	BlzFrameSetText(BlzGetFrameByName("BoxedTextTitle", CustomStatFrames.Count), "TooltipTitle")
	BlzFrameSetText(BlzGetFrameByName("BoxedTextValue", CustomStatFrames.Count), text)
	BlzFrameSetTexture(BlzGetFrameByName("CustomStatIcon", CustomStatFrames.Count), icon, 0, true)
	
	
	--Dissallow having the TEXT-Tooltip-Frames gaining mouse control. This might produce problems, if the TEXT Frame has an disabled Color.
	BlzFrameSetEnable(BlzGetFrameByName("BoxedTextValue", CustomStatFrames.Count), false)
	BlzFrameSetEnable(BlzGetFrameByName("BoxedTextTitle", CustomStatFrames.Count), false)

	--[[ 4x3
	if CustomStatFrames.Count == 1 then
		BlzFrameSetAbsPoint(fh, FRAMEPOINT_TOPLEFT, 0.31, 0.08)
	elseif CustomStatFrames.Count == 5 then
		BlzFrameSetAbsPoint(fh, FRAMEPOINT_TOPLEFT, 0.375, 0.08)
	elseif CustomStatFrames.Count == 9 then
		BlzFrameSetAbsPoint(fh, FRAMEPOINT_TOPLEFT, 0.435, 0.08)
	else
		BlzFrameSetPoint(fh, FRAMEPOINT_TOPLEFT, BlzGetFrameByName("CustomStat", CustomStatFrames.Count - 1), FRAMEPOINT_BOTTOMLEFT, 0, 0)
	end
	--]]
	--[[ 4x4
	if CustomStatFrames.Count == 1 then
		BlzFrameSetAbsPoint(fh, FRAMEPOINT_TOPLEFT, 0.31, 0.08)
	elseif CustomStatFrames.Count == 5 then
		BlzFrameSetAbsPoint(fh, FRAMEPOINT_TOPLEFT, 0.36, 0.08)
	elseif CustomStatFrames.Count == 9 then
		BlzFrameSetAbsPoint(fh, FRAMEPOINT_TOPLEFT, 0.41, 0.08)
	elseif CustomStatFrames.Count == 13 then
		BlzFrameSetAbsPoint(fh, FRAMEPOINT_TOPLEFT, 0.46, 0.08)
	else
		BlzFrameSetPoint(fh, FRAMEPOINT_TOPLEFT, BlzGetFrameByName("CustomStat", CustomStatFrames.Count - 1), FRAMEPOINT_BOTTOMLEFT, 0, 0)
	end
	--]]

	--3x3
	if CustomStatFrames.Count == 1 then
		BlzFrameSetAbsPoint(fh, FRAMEPOINT_TOPLEFT, 0.31, 0.08)
	elseif CustomStatFrames.Count == 4 then
		BlzFrameSetAbsPoint(fh, FRAMEPOINT_TOPLEFT, 0.375, 0.08)
	elseif CustomStatFrames.Count == 7 then
		BlzFrameSetAbsPoint(fh, FRAMEPOINT_TOPLEFT, 0.435, 0.08)
	else
		BlzFrameSetPoint(fh, FRAMEPOINT_TOPLEFT, BlzGetFrameByName("CustomStat", CustomStatFrames.Count - 1), FRAMEPOINT_BOTTOMLEFT, 0, -0.005)
	end
	
	--save into table
	CustomStatFrames[CustomStatFrames.Count] = {}
	CustomStatFrames[CustomStatFrames.Count].Frame = fh
	CustomStatFrames[CustomStatFrames.Count].FrameIcon = BlzGetFrameByName("CustomStatIcon", CustomStatFrames.Count)
	CustomStatFrames[CustomStatFrames.Count].FrameText = BlzGetFrameByName("CustomStatText", CustomStatFrames.Count)
	CustomStatFrames[CustomStatFrames.Count].FrameHover = fhHover
	CustomStatFrames[CustomStatFrames.Count].ToolTipBox = tooltipBox
	CustomStatFrames[CustomStatFrames.Count].ToolTipTitle = BlzGetFrameByName("BoxedTextTitle", CustomStatFrames.Count)
	CustomStatFrames[CustomStatFrames.Count].ToolTipText = BlzGetFrameByName("BoxedTextValue", CustomStatFrames.Count)
end

function CustomStatUpdate()
	local isVisible = BlzFrameIsVisible(CustomStatFrames.BoxS)
	
	BlzFrameSetText(CustomStatFrames[1].FrameText, BlzFrameGetText(BlzGetFrameByName("InfoPanelIconValue", 0))) --copy normal damage text
	BlzFrameSetText(CustomStatFrames[2].FrameText, BlzFrameGetText(BlzGetFrameByName("InfoPanelIconValue", 2))) --copy normal armor field
	
	BlzFrameSetText(CustomStatFrames[6].FrameText, GetUnitMoveSpeed(CustomStatSelectedUnit[GetLocalPlayer()]))
	BlzFrameSetVisible(CustomStatFrames.BoxF, BlzFrameIsVisible(CustomStatFrames.BoxS))
	-- show the current hovered
	for i = 1, CustomStatFrames.Count do
		BlzFrameSetVisible(CustomStatFrames[i].ToolTipBox, BlzFrameIsVisible(CustomStatFrames[i].FrameHover))
	end
end

function CustomStatInit()

    --move the default unit infos out of the screen and scale it down
    local function CustomStatMoveOutOfScreen(frame)
        BlzFrameClearAllPoints(frame)
        BlzFrameSetAbsPoint(frame, FRAMEPOINT_CENTER, 3, 0)
    end
    for index = 0, 5, 1 do
        CustomStatMoveOutOfScreen(BlzGetFrameByName("InfoPanelIconBackdrop", index))		
    end
    CustomStatMoveOutOfScreen(BlzGetFrameByName("InfoPanelIconHeroIcon", 6))
	CustomStatMoveOutOfScreen(BlzGetFrameByName("InfoPanelIconAllyTitle", 7))
	CustomStatMoveOutOfScreen(BlzGetFrameByName("InfoPanelIconAllyGoldIcon", 7))

	--Create a Selection Trigger thats a pretty naive approach.
	local trig = CreateTrigger()
	TriggerAddAction(trig, function () CustomStatSelectedUnit[GetTriggerPlayer()] = GetTriggerUnit() end)
	
	local index = 0
	repeat
		TriggerRegisterPlayerSelectionEventBJ(trig, Player(index), true)
		--TriggerRegisterPlayerSelectionEventBJ(trig, Player(index), false)
		index = index + 1
	until index == bj_MAX_PLAYER_SLOTS


	--create a Parent for the Stats so you can easyly hide/show them-
	--Stats use SimpleUnitStatsPanel as parent that way they are only shown when an unit is selected which does not build.
	CustomStatFrames.BoxS = BlzCreateFrameByType("SIMPLEFRAME", "CustomStatFrames.BoxSBoss", BlzGetFrameByName("SimpleUnitStatsPanel",0), "", 0) 
	CustomStatFrames.BoxF = BlzCreateFrameByType("FRAME", "CustomStatFrames.BoxFBoss", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0) 
	
	
	BlzLoadTOCFile("war3mapimported\\CustomStat.toc")
	
	CustomStatAdd(udg_UnitStatIcon[CustomStatFrames.Count + 1],"Test1")
	CustomStatAdd(udg_UnitStatIcon[CustomStatFrames.Count + 1],"Test2")
	CustomStatAdd(udg_UnitStatIcon[CustomStatFrames.Count + 1],"Test3")
	CustomStatAdd(udg_UnitStatIcon[CustomStatFrames.Count + 1],"Test4")
	CustomStatAdd(udg_UnitStatIcon[CustomStatFrames.Count + 1],"Test5")
	CustomStatAdd(udg_UnitStatIcon[CustomStatFrames.Count + 1],"Test6")
	CustomStatAdd(udg_UnitStatIcon[CustomStatFrames.Count + 1],"Test7")
	CustomStatAdd(udg_UnitStatIcon[CustomStatFrames.Count + 1],"Test8")
	CustomStatAdd(udg_UnitStatIcon[CustomStatFrames.Count + 1],"Test9")
	--[[
	CustomStatAdd(udg_UnitStatIcon[CustomStatFrames.Count + 1],"Test10")
	CustomStatAdd(udg_UnitStatIcon[CustomStatFrames.Count + 1],"Test11")
	CustomStatAdd(udg_UnitStatIcon[CustomStatFrames.Count + 1],"Test12")
	CustomStatAdd(udg_UnitStatIcon[CustomStatFrames.Count + 1],"Test13")
	CustomStatAdd(udg_UnitStatIcon[CustomStatFrames.Count + 1],"Test14")
	CustomStatAdd(udg_UnitStatIcon[CustomStatFrames.Count + 1],"Test15")
	CustomStatAdd(udg_UnitStatIcon[CustomStatFrames.Count + 1],"Test16")
	--]]
	TimerStart(CreateTimer(), 0.1, true, CustomStatUpdate)
	print("Done")
end
function InitSounds()
gg_snd_Round01 = CreateSound("war3mapImported\\Round01.mp3", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_Round01, 2063)
SetSoundChannel(gg_snd_Round01, 0)
SetSoundVolume(gg_snd_Round01, 127)
SetSoundPitch(gg_snd_Round01, 1.0)
gg_snd_Round02 = CreateSound("war3mapImported\\Round02.mp3", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_Round02, 1802)
SetSoundChannel(gg_snd_Round02, 0)
SetSoundVolume(gg_snd_Round02, 127)
SetSoundPitch(gg_snd_Round02, 1.0)
gg_snd_Round03 = CreateSound("war3mapImported\\Round03.mp3", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_Round03, 1933)
SetSoundChannel(gg_snd_Round03, 0)
SetSoundVolume(gg_snd_Round03, 127)
SetSoundPitch(gg_snd_Round03, 1.0)
gg_snd_Round04 = CreateSound("war3mapImported\\Round04.mp3", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_Round04, 2011)
SetSoundChannel(gg_snd_Round04, 0)
SetSoundVolume(gg_snd_Round04, 127)
SetSoundPitch(gg_snd_Round04, 1.0)
gg_snd_Vitality = CreateSound("war3mapImported\\Vitality.mp3", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_Vitality, 2351)
SetSoundChannel(gg_snd_Vitality, 0)
SetSoundVolume(gg_snd_Vitality, 127)
SetSoundPitch(gg_snd_Vitality, 1.0)
gg_snd_Brutality = CreateSound("war3mapImported\\Brutality.mp3", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_Brutality, 1671)
SetSoundChannel(gg_snd_Brutality, 0)
SetSoundVolume(gg_snd_Brutality, 127)
SetSoundPitch(gg_snd_Brutality, 1.0)
gg_snd_FinalRound = CreateSound("war3mapImported\\FinalRound.mp3", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_FinalRound, 1410)
SetSoundChannel(gg_snd_FinalRound, 0)
SetSoundVolume(gg_snd_FinalRound, 127)
SetSoundPitch(gg_snd_FinalRound, 1.0)
gg_snd_TestYourLuck = CreateSound("war3mapImported\\TestYourLuck.mp3", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_TestYourLuck, 4702)
SetSoundChannel(gg_snd_TestYourLuck, 0)
SetSoundVolume(gg_snd_TestYourLuck, 127)
SetSoundPitch(gg_snd_TestYourLuck, 1.0)
gg_snd_FirstBlood = CreateSound("war3mapImported\\Announcer_1stblood_01.mp3", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_FirstBlood, 1724)
SetSoundChannel(gg_snd_FirstBlood, 0)
SetSoundVolume(gg_snd_FirstBlood, 127)
SetSoundPitch(gg_snd_FirstBlood, 1.0)
gg_snd_Announcer_kill_godlike_01 = CreateSound("war3mapImported\\Announcer_kill_godlike_01.mp3", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_Announcer_kill_godlike_01, 1880)
SetSoundChannel(gg_snd_Announcer_kill_godlike_01, 0)
SetSoundVolume(gg_snd_Announcer_kill_godlike_01, 127)
SetSoundPitch(gg_snd_Announcer_kill_godlike_01, 1.0)
gg_snd_Announcer_kill_holy_01 = CreateSound("war3mapImported\\Announcer_kill_holy_01.mp3", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_Announcer_kill_holy_01, 2377)
SetSoundChannel(gg_snd_Announcer_kill_holy_01, 0)
SetSoundVolume(gg_snd_Announcer_kill_holy_01, 127)
SetSoundPitch(gg_snd_Announcer_kill_holy_01, 1.0)
gg_snd_wicked_sick_unreal_sound_effect = CreateSound("war3mapImported\\wicked-sick-unreal-sound-effect.mp3", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_wicked_sick_unreal_sound_effect, 3395)
SetSoundChannel(gg_snd_wicked_sick_unreal_sound_effect, 0)
SetSoundVolume(gg_snd_wicked_sick_unreal_sound_effect, 127)
SetSoundPitch(gg_snd_wicked_sick_unreal_sound_effect, 1.0)
gg_snd_unstoppable_quake_3_arena_sound_effect = CreateSound("war3mapImported\\unstoppable-quake-3-arena-sound-effect.mp3", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_unstoppable_quake_3_arena_sound_effect, 2821)
SetSoundChannel(gg_snd_unstoppable_quake_3_arena_sound_effect, 0)
SetSoundVolume(gg_snd_unstoppable_quake_3_arena_sound_effect, 127)
SetSoundPitch(gg_snd_unstoppable_quake_3_arena_sound_effect, 1.0)
gg_snd_last_man_standing = CreateSound("war3mapImported\\last_man_standing.mp3", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_last_man_standing, 2455)
SetSoundChannel(gg_snd_last_man_standing, 0)
SetSoundVolume(gg_snd_last_man_standing, 127)
SetSoundPitch(gg_snd_last_man_standing, 1.0)
gg_snd_Speed = CreateSound("war3mapImported\\Speed.mp3", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_Speed, 2089)
SetSoundChannel(gg_snd_Speed, 0)
SetSoundVolume(gg_snd_Speed, 127)
SetSoundPitch(gg_snd_Speed, 1.0)
gg_snd_Invulnerable = CreateSound("war3mapImported\\Invulnerable.mp3", false, false, false, 10, 10, "DefaultEAXON")
SetSoundDuration(gg_snd_Invulnerable, 2089)
SetSoundChannel(gg_snd_Invulnerable, 0)
SetSoundVolume(gg_snd_Invulnerable, 127)
SetSoundPitch(gg_snd_Invulnerable, 1.0)
gg_snd_Victory_fanfare = "war3mapImported\\Victory-fanfare.mp3"
gg_snd_Numb_compress = CreateSound("war3mapImported/Numb-compress.mp3", true, false, false, 1, 1, "DoodadsEAX")
SetSoundDuration(gg_snd_Numb_compress, 2089)
SetSoundChannel(gg_snd_Numb_compress, 0)
SetSoundVolume(gg_snd_Numb_compress, 127)
SetSoundPitch(gg_snd_Numb_compress, 1.0)
gg_snd_basshunter_dota_hq = CreateSound("war3mapImported/basshunter-dota-hq.mp3", true, false, false, 1, 1, "DoodadsEAX")
SetSoundDuration(gg_snd_basshunter_dota_hq, 2089)
SetSoundChannel(gg_snd_basshunter_dota_hq, 0)
SetSoundVolume(gg_snd_basshunter_dota_hq, 127)
SetSoundPitch(gg_snd_basshunter_dota_hq, 1.0)
gg_snd_In_The_End__Official_Video____Linkin_Park2 = CreateSound("war3mapImported/In The End (Official Video) - Linkin Park2.mp3", true, false, false, 1, 1, "DoodadsEAX")
SetSoundDuration(gg_snd_In_The_End__Official_Video____Linkin_Park2, 2089)
SetSoundChannel(gg_snd_In_The_End__Official_Video____Linkin_Park2, 0)
SetSoundVolume(gg_snd_In_The_End__Official_Video____Linkin_Park2, 127)
SetSoundPitch(gg_snd_In_The_End__Official_Video____Linkin_Park2, 1.0)
gg_snd_NumbNC = CreateSound("war3mapImported/NumbNC.mp3", true, false, false, 1, 1, "DoodadsEAX")
SetSoundDuration(gg_snd_NumbNC, 2089)
SetSoundChannel(gg_snd_NumbNC, 0)
SetSoundVolume(gg_snd_NumbNC, 127)
SetSoundPitch(gg_snd_NumbNC, 1.0)
gg_snd_NEFFEX_Cold = CreateSound("war3mapImported/NEFFEX Cold.mp3", true, false, false, 1, 1, "DoodadsEAX")
SetSoundDuration(gg_snd_NEFFEX_Cold, 2089)
SetSoundChannel(gg_snd_NEFFEX_Cold, 0)
SetSoundVolume(gg_snd_NEFFEX_Cold, 127)
SetSoundPitch(gg_snd_NEFFEX_Cold, 1.0)
gg_snd_K_391__Alan_Walker___Ahrix___End_of_Time = CreateSound("war3mapImported/K-391, Alan Walker & Ahrix - End of Time.mp3", true, false, false, 1, 1, "DoodadsEAX")
SetSoundDuration(gg_snd_K_391__Alan_Walker___Ahrix___End_of_Time, 2089)
SetSoundChannel(gg_snd_K_391__Alan_Walker___Ahrix___End_of_Time, 0)
SetSoundVolume(gg_snd_K_391__Alan_Walker___Ahrix___End_of_Time, 127)
SetSoundPitch(gg_snd_K_391__Alan_Walker___Ahrix___End_of_Time, 1.0)
gg_snd_R3hab_You_Could_Be = CreateSound("war3mapImported/R3hab You Could Be.mp3", true, false, false, 1, 1, "DoodadsEAX")
SetSoundDuration(gg_snd_R3hab_You_Could_Be, 2089)
SetSoundChannel(gg_snd_R3hab_You_Could_Be, 0)
SetSoundVolume(gg_snd_R3hab_You_Could_Be, 127)
SetSoundPitch(gg_snd_R3hab_You_Could_Be, 1.0)
gg_snd_Halsey___Without_Me__Illenium_Remix_u = CreateSound("war3mapImported/Halsey - Without Me (Illenium Remix).mp3", true, false, false, 1, 1, "DoodadsEAX")
SetSoundDuration(gg_snd_Halsey___Without_Me__Illenium_Remix_u, 2089)
SetSoundChannel(gg_snd_Halsey___Without_Me__Illenium_Remix_u, 0)
SetSoundVolume(gg_snd_Halsey___Without_Me__Illenium_Remix_u, 127)
SetSoundPitch(gg_snd_Halsey___Without_Me__Illenium_Remix_u, 1.0)
gg_snd_R3HAB_Lullaby = CreateSound("war3mapImported/R3HAB Lullaby.mp3", true, false, false, 1, 1, "DoodadsEAX")
SetSoundDuration(gg_snd_R3HAB_Lullaby, 2089)
SetSoundChannel(gg_snd_R3HAB_Lullaby, 0)
SetSoundVolume(gg_snd_R3HAB_Lullaby, 127)
SetSoundPitch(gg_snd_R3HAB_Lullaby, 1.0)
gg_snd_KSHMR___Hard_Lights___Over_and_Out = CreateSound("war3mapImported/KSHMR & Hard Lights - Over and Out.mp3", true, false, false, 1, 1, "DoodadsEAX")
SetSoundDuration(gg_snd_KSHMR___Hard_Lights___Over_and_Out, 2089)
SetSoundChannel(gg_snd_KSHMR___Hard_Lights___Over_and_Out, 0)
SetSoundVolume(gg_snd_KSHMR___Hard_Lights___Over_and_Out, 127)
SetSoundPitch(gg_snd_KSHMR___Hard_Lights___Over_and_Out, 1.0)
gg_snd_KSHMR___7_Skies___Neverland = CreateSound("war3mapImported/KSHMR & 7 Skies - Neverland.mp3", true, false, false, 1, 1, "DoodadsEAX")
SetSoundDuration(gg_snd_KSHMR___7_Skies___Neverland, 2089)
SetSoundChannel(gg_snd_KSHMR___7_Skies___Neverland, 0)
SetSoundVolume(gg_snd_KSHMR___7_Skies___Neverland, 127)
SetSoundPitch(gg_snd_KSHMR___7_Skies___Neverland, 1.0)
gg_snd_In_The_End__MG_TP_u = CreateSound("war3mapImported/In The End (MG&TP).mp3", true, false, false, 1, 1, "DoodadsEAX")
SetSoundDuration(gg_snd_In_The_End__MG_TP_u, 2089)
SetSoundChannel(gg_snd_In_The_End__MG_TP_u, 0)
SetSoundVolume(gg_snd_In_The_End__MG_TP_u, 127)
SetSoundPitch(gg_snd_In_The_End__MG_TP_u, 1.0)
gg_snd_nightcore_tonight_dj_gollum_feat_dj_cap_remix_edit_tomtrax_orca = CreateSound("war3mapImported/nightcore-tonight-dj-gollum-feat-dj-cap-remix-edit-tomtrax-orca.mp3", false, false, false, 0, 0, "DefaultEAXON")
SetSoundDuration(gg_snd_nightcore_tonight_dj_gollum_feat_dj_cap_remix_edit_tomtrax_orca, 2089)
SetSoundChannel(gg_snd_nightcore_tonight_dj_gollum_feat_dj_cap_remix_edit_tomtrax_orca, 0)
SetSoundVolume(gg_snd_nightcore_tonight_dj_gollum_feat_dj_cap_remix_edit_tomtrax_orca, 127)
SetSoundPitch(gg_snd_nightcore_tonight_dj_gollum_feat_dj_cap_remix_edit_tomtrax_orca, 1.0)
gg_snd_Breaking_Benjamin___Diary_Of_Jane = CreateSound("war3mapImported/Breaking Benjamin - Diary Of Jane.mp3", true, false, false, 1, 1, "DoodadsEAX")
SetSoundDuration(gg_snd_Breaking_Benjamin___Diary_Of_Jane, 2089)
SetSoundChannel(gg_snd_Breaking_Benjamin___Diary_Of_Jane, 0)
SetSoundVolume(gg_snd_Breaking_Benjamin___Diary_Of_Jane, 127)
SetSoundPitch(gg_snd_Breaking_Benjamin___Diary_Of_Jane, 1.0)
gg_snd_Remember_The_Name___Fort_Minor = CreateSound("war3mapImported/Remember The Name - Fort Minor.mp3", true, false, false, 1, 1, "DoodadsEAX")
SetSoundDuration(gg_snd_Remember_The_Name___Fort_Minor, 2089)
SetSoundChannel(gg_snd_Remember_The_Name___Fort_Minor, 0)
SetSoundVolume(gg_snd_Remember_The_Name___Fort_Minor, 127)
SetSoundPitch(gg_snd_Remember_The_Name___Fort_Minor, 1.0)
gg_snd_linkin_park_numb = CreateSound("war3mapImported/linkin-park-numb.mp3", false, false, false, 0, 0, "DefaultEAXON")
SetSoundDuration(gg_snd_linkin_park_numb, 2089)
SetSoundChannel(gg_snd_linkin_park_numb, 0)
SetSoundVolume(gg_snd_linkin_park_numb, 127)
SetSoundPitch(gg_snd_linkin_park_numb, 1.0)
gg_snd_linkin_park_numb01 = "war3mapImported/linkin-park-numb.mp3"
gg_snd_Mix = CreateSound("war3mapImported/Mix.mp3", false, false, false, 0, 0, "DefaultEAXON")
SetSoundDuration(gg_snd_Mix, 1297371)
SetSoundChannel(gg_snd_Mix, 0)
SetSoundVolume(gg_snd_Mix, 127)
SetSoundPitch(gg_snd_Mix, 1.0)
end

function CreateNeutralPassiveBuildings()
local p = Player(PLAYER_NEUTRAL_PASSIVE)
local u
local unitID
local t
local life

u = BlzCreateUnitWithSkin(p, FourCC("ngme"), -3136.0, 2432.0, 270.000, FourCC("ngme"))
u = BlzCreateUnitWithSkin(p, FourCC("ngme"), 1600.0, 1216.0, 270.000, FourCC("ngme"))
u = BlzCreateUnitWithSkin(p, FourCC("ngme"), 320.0, -64.0, 270.000, FourCC("ngme"))
u = BlzCreateUnitWithSkin(p, FourCC("ngme"), -2368.0, -2752.0, 270.000, FourCC("ngme"))
end

function CreateNeutralPassive()
local p = Player(PLAYER_NEUTRAL_PASSIVE)
local u
local unitID
local t
local life

u = BlzCreateUnitWithSkin(p, FourCC("npn5"), 3238.5, 2986.5, 230.000, FourCC("npn5"))
u = BlzCreateUnitWithSkin(p, FourCC("h003"), -2947.9, -3277.0, 161.440, FourCC("h003"))
end

function CreatePlayerBuildings()
end

function CreatePlayerUnits()
end

function CreateAllUnits()
CreateNeutralPassiveBuildings()
CreatePlayerBuildings()
CreateNeutralPassive()
CreatePlayerUnits()
end

function CreateRegions()
local we

gg_rct_BoA_Revive_Area = Rect(-3296.0, 2304.0, -2944.0, 2656.0)
gg_rct_Bronze_medal = Rect(-128.0, -896.0, -64.0, -832.0)
gg_rct_Circle_Area = Rect(-1184.0, -1536.0, -992.0, 0.0)
gg_rct_Clan_RD = Rect(-384.0, -896.0, -352.0, -864.0)
gg_rct_Clan_RD2 = Rect(-320.0, -896.0, -288.0, -864.0)
gg_rct_PodiumDeathsScore = Rect(-576.0, -480.0, -512.0, -448.0)
gg_rct_Gold_Medal = Rect(-224.0, -448.0, -192.0, -384.0)
gg_rct_InitialSpawn = Rect(-3328.0, 2720.0, -2816.0, 3072.0)
gg_rct_PandaArea = Rect(3136.0, 2816.0, 3328.0, 3104.0)
gg_rct_PandaText = Rect(3008.0, 3008.0, 3232.0, 3136.0)
gg_rct_PoA2_ReviveArea = Rect(-3232.0, 2368.0, -3008.0, 2592.0)
gg_rct_PoA3_Revive_Area = Rect(-3264.0, 2336.0, -2976.0, 2624.0)
gg_rct_Podium_1 = Rect(-192.0, -512.0, -128.0, -448.0)
gg_rct_PodiumDeaths = Rect(-352.0, -640.0, -288.0, -576.0)
gg_rct_PodiumMVP = Rect(-224.0, -640.0, -160.0, -576.0)
gg_rct_PodiumSabotages = Rect(-352.0, -832.0, -288.0, -768.0)
gg_rct_PodiumSaves = Rect(-224.0, -832.0, -160.0, -768.0)
gg_rct_Podium_cinematic = Rect(-384.0, -896.0, -64.0, -544.0)
gg_rct_safe_Area_01 = Rect(2496.0, 2112.0, 3360.0, 3072.0)
gg_rct_safe_Area_02 = Rect(2528.0, -3616.0, 3296.0, -2912.0)
gg_rct_safe_Area_03 = Rect(-2880.0, -3360.0, -2048.0, -2624.0)
gg_rct_safe_Area_04 = Rect(-3328.0, 1472.0, -2560.0, 2016.0)
gg_rct_safe_Area_05 = Rect(1856.0, 1472.0, 2464.0, 2176.0)
gg_rct_safe_Area_06 = Rect(1856.0, -2848.0, 2464.0, -2240.0)
gg_rct_safe_Area_07 = Rect(-2496.0, -2848.0, -1856.0, -2208.0)
gg_rct_safe_Area_08 = Rect(-2464.0, 864.0, -1856.0, 1280.0)
gg_rct_safe_Area_09 = Rect(1216.0, 832.0, 1696.0, 1280.0)
gg_rct_safe_Area_10 = Rect(1184.0, -2080.0, 1696.0, -1600.0)
gg_rct_safe_Area_11 = Rect(-1696.0, -2144.0, -1216.0, -1568.0)
gg_rct_safe_Area_12 = Rect(-1696.0, 192.0, -1216.0, 640.0)
gg_rct_safe_Area_13 = Rect(576.0, 128.0, 1056.0, 640.0)
gg_rct_safe_Area_14 = Rect(-96.0, -512.0, 416.0, 32.0)
gg_rct_Saves = Rect(-320.0, -416.0, -256.0, -384.0)
gg_rct_MVPTAG = Rect(-256.0, -704.0, -192.0, -672.0)
gg_rct_PodiumMVPScore = Rect(-96.0, -576.0, -32.0, -544.0)
gg_rct_PodiumSabotageScore = Rect(-576.0, -704.0, -512.0, -672.0)
gg_rct_PodiumSavesScore = Rect(-96.0, -736.0, -32.0, -704.0)
gg_rct_MostSavesTag = Rect(-288.0, -896.0, -224.0, -864.0)
gg_rct_Spawn_Area_01 = Rect(-2848.0, 2976.0, -2688.0, 3040.0)
gg_rct_Spawn_Area_02 = Rect(-2848.0, 2912.0, -2688.0, 2976.0)
gg_rct_Spawn_Area_03 = Rect(-2848.0, 2848.0, -2688.0, 2912.0)
gg_rct_Spawn_Area_04 = Rect(-2848.0, 2784.0, -2688.0, 2848.0)
gg_rct_Spawn_Area_05 = Rect(-2848.0, 2720.0, -2688.0, 2784.0)
gg_rct_Spawn_Area_06 = Rect(-2848.0, 2656.0, -2688.0, 2720.0)
gg_rct_Spawn_Area_07 = Rect(-2848.0, 2592.0, -2688.0, 2656.0)
gg_rct_Spawn_Area_08 = Rect(-2848.0, 2528.0, -2688.0, 2592.0)
gg_rct_Spawn_Area_09 = Rect(-2848.0, 2464.0, -2688.0, 2528.0)
gg_rct_Spawn_Area_10 = Rect(-2848.0, 2400.0, -2688.0, 2464.0)
gg_rct_Spawn_Area_11 = Rect(-2848.0, 2336.0, -2688.0, 2400.0)
gg_rct_Spawn_Camera = Rect(-2848.0, 2336.0, -2688.0, 3040.0)
gg_rct_LeastDeathsTag = Rect(-448.0, -672.0, -384.0, -640.0)
gg_rct_Victory_Area = Rect(-32.0, -800.0, 416.0, -480.0)
gg_rct_Wolf_Area_01 = Rect(-2560.0, 2272.0, 2560.0, 3136.0)
gg_rct_Wolf_Area_02 = Rect(2528.0, -2944.0, 3360.0, 2144.0)
gg_rct_Wolf_Area_03 = Rect(-2528.0, -3616.0, 2560.0, -2944.0)
gg_rct_Wolf_Area_04 = Rect(-3392.0, -2912.0, -2560.0, 1472.0)
gg_rct_Wolf_Area_05 = Rect(-2592.0, 1440.0, 1920.0, 2208.0)
gg_rct_Wolf_Area_06 = Rect(1888.0, -2240.0, 2496.0, 1472.0)
gg_rct_Wolf_Area_07 = Rect(-1888.0, -2912.0, 1824.0, -2240.0)
gg_rct_Wolf_Area_08 = Rect(-2496.0, -2240.0, -1856.0, 864.0)
gg_rct_Wolf_Area_09 = Rect(-1856.0, 864.0, 1216.0, 1344.0)
gg_rct_Wolf_Area_10 = Rect(1216.0, -1632.0, 1728.0, 864.0)
gg_rct_Wolf_Area_11 = Rect(-1248.0, -2080.0, 1248.0, -1600.0)
gg_rct_Wolf_Area_12 = Rect(-1696.0, -1600.0, -1216.0, 224.0)
gg_rct_Wolf_Area_13 = Rect(-1216.0, 160.0, 640.0, 640.0)
gg_rct_Wolf_Area_14 = Rect(608.0, -928.0, 1088.0, 160.0)
gg_rct_Wolf_Area_15 = Rect(-928.0, -1440.0, 1056.0, -1024.0)
gg_rct_Wolf_Area_16 = Rect(-928.0, -928.0, -480.0, -480.0)
gg_rct_Wolf_Area_17 = Rect(-928.0, -416.0, -64.0, 32.0)
gg_rct_ClearLaneArea12 = Rect(-1696.0, 288.0, -1312.0, 640.0)
gg_rct_Region_050 = Rect(-1344.0, 2368.0, -1312.0, 2400.0)
gg_rct_safe_Area_00 = Rect(-3200.0, 2464.0, -2656.0, 2976.0)
gg_rct_Fieryfox = Rect(-3424.0, 3104.0, -3200.0, 3296.0)
gg_rct_FinishZone = Rect(-64.0, -832.0, 416.0, 32.0)
gg_rct_TeamRed = Rect(-2784.0, 3648.0, -2144.0, 3840.0)
gg_rct_TeamBlue = Rect(-2016.0, 3648.0, -1376.0, 3808.0)
gg_rct_TeamTeal = Rect(-1248.0, 3648.0, -608.0, 3808.0)
gg_rct_P1 = Rect(-2688.0, 3552.0, -2176.0, 3616.0)
gg_rct_P2 = Rect(-2688.0, 3456.0, -2176.0, 3520.0)
gg_rct_P3 = Rect(-2688.0, 3360.0, -2176.0, 3424.0)
gg_rct_P4 = Rect(-2688.0, 3264.0, -2176.0, 3328.0)
gg_rct_P5 = Rect(-1920.0, 3552.0, -1408.0, 3616.0)
gg_rct_P6 = Rect(-1920.0, 3456.0, -1408.0, 3520.0)
gg_rct_P7 = Rect(-1920.0, 3360.0, -1408.0, 3424.0)
gg_rct_P8 = Rect(-1920.0, 3264.0, -1408.0, 3328.0)
gg_rct_P9 = Rect(-1152.0, 3552.0, -640.0, 3616.0)
gg_rct_P10 = Rect(-1152.0, 3456.0, -640.0, 3520.0)
gg_rct_P11 = Rect(-1152.0, 3360.0, -640.0, 3424.0)
gg_rct_P12 = Rect(-1152.0, 3264.0, -640.0, 3328.0)
gg_rct_SabotageTag = Rect(-480.0, -896.0, -416.0, -864.0)
gg_rct_LightningTLeft = Rect(-480.0, -416.0, -416.0, -352.0)
gg_rct_LightningTRight = Rect(-96.0, -416.0, -64.0, -352.0)
gg_rct_LightningBLeft = Rect(-448.0, -960.0, -416.0, -928.0)
gg_rct_LightningBRight = Rect(-96.0, -960.0, -64.0, -928.0)
gg_rct_TRegion1 = Rect(736.0, -1312.0, 896.0, -1184.0)
gg_rct_TRegion2 = Rect(-800.0, -1312.0, -576.0, -1184.0)
gg_rct_TRegion3 = Rect(-800.0, -288.0, -608.0, -128.0)
gg_rct_BarrierRegion = Rect(-2624.0, 2304.0, -2592.0, 3072.0)
gg_rct_Dummy1Region = Rect(-2624.0, 2880.0, -2592.0, 2912.0)
gg_rct_Dummy2Region = Rect(-2624.0, 2656.0, -2592.0, 2688.0)
gg_rct_Dummy3Region = Rect(-2624.0, 2432.0, -2592.0, 2464.0)
end

function Trig_Start_Actions()
udg_UnitStatIcon[1] = "ReplaceableTextures\\CommandButtons\\BTNSteelMelee.blp"
udg_UnitStatIcon[2] = "ReplaceableTextures\\CommandButtons\\BTNHumanArmorUpOne.blp"
udg_UnitStatIcon[3] = "ReplaceableTextures\\PassiveButtons\\PASBTNThickFur.blp"
udg_UnitStatIcon[4] = "ReplaceableTextures\\CommandButtons\\BTNEvasion.blp"
udg_UnitStatIcon[5] = "ReplaceableTextures\\CommandButtons\\BTNCriticalStrike.blp"
udg_UnitStatIcon[6] = "ReplaceableTextures\\CommandButtons\\BTNBootsOfSpeed.blp"
udg_UnitStatIcon[7] = "ReplaceableTextures\\CommandButtons\\BTNGlove.blp"
udg_UnitStatIcon[8] = "UI\\Widgets\\Console\\Human\\infocard-gold.blp"
udg_UnitStatIcon[9] = "UI\\Widgets\\Console\\Human\\infocard-supply.blp"
udg_UnitStatIcon[10] = "UI\\Widgets\\Console\\Human\\infocard-heroattributes-str.blp"
udg_UnitStatIcon[11] = "UI\\Widgets\\Console\\Human\\infocard-heroattributes-agi.blp"
udg_UnitStatIcon[12] = "UI\\Widgets\\Console\\Human\\infocard-heroattributes-int.blp"
udg_UnitStatIcon[13] = "ReplaceableTextures\\CommandButtons\\BTNSorceressAdept.blp"
udg_UnitStatIcon[14] = "ReplaceableTextures\\CommandButtons\\BTNPriestAdept.blp"
udg_UnitStatIcon[15] = "ReplaceableTextures\\CommandButtons\\BTNCirclet.blp"
udg_UnitStatIcon[16] = "ReplaceableTextures\\CommandButtons\\BTNRingJadeFalcon.blp"
    CustomStatInit()
end

function InitTrig_Start()
gg_trg_Start = CreateTrigger()
TriggerRegisterTimerEventSingle(gg_trg_Start, 0.00)
TriggerAddAction(gg_trg_Start, Trig_Start_Actions)
end

function InitCustomTriggers()
InitTrig_Start()
end

function InitCustomPlayerSlots()
SetPlayerStartLocation(Player(0), 0)
SetPlayerColor(Player(0), ConvertPlayerColor(0))
SetPlayerRacePreference(Player(0), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(0), true)
SetPlayerController(Player(0), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(1), 1)
SetPlayerColor(Player(1), ConvertPlayerColor(1))
SetPlayerRacePreference(Player(1), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(1), true)
SetPlayerController(Player(1), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(2), 2)
SetPlayerColor(Player(2), ConvertPlayerColor(2))
SetPlayerRacePreference(Player(2), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(2), true)
SetPlayerController(Player(2), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(3), 3)
SetPlayerColor(Player(3), ConvertPlayerColor(3))
SetPlayerRacePreference(Player(3), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(3), true)
SetPlayerController(Player(3), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(4), 4)
SetPlayerColor(Player(4), ConvertPlayerColor(4))
SetPlayerRacePreference(Player(4), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(4), true)
SetPlayerController(Player(4), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(5), 5)
SetPlayerColor(Player(5), ConvertPlayerColor(5))
SetPlayerRacePreference(Player(5), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(5), true)
SetPlayerController(Player(5), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(6), 6)
SetPlayerColor(Player(6), ConvertPlayerColor(6))
SetPlayerRacePreference(Player(6), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(6), true)
SetPlayerController(Player(6), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(7), 7)
SetPlayerColor(Player(7), ConvertPlayerColor(7))
SetPlayerRacePreference(Player(7), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(7), true)
SetPlayerController(Player(7), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(8), 8)
SetPlayerColor(Player(8), ConvertPlayerColor(8))
SetPlayerRacePreference(Player(8), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(8), true)
SetPlayerController(Player(8), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(9), 9)
SetPlayerColor(Player(9), ConvertPlayerColor(9))
SetPlayerRacePreference(Player(9), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(9), true)
SetPlayerController(Player(9), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(10), 10)
SetPlayerColor(Player(10), ConvertPlayerColor(10))
SetPlayerRacePreference(Player(10), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(10), true)
SetPlayerController(Player(10), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(11), 11)
SetPlayerColor(Player(11), ConvertPlayerColor(11))
SetPlayerRacePreference(Player(11), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(11), true)
SetPlayerController(Player(11), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(12), 12)
SetPlayerColor(Player(12), ConvertPlayerColor(12))
SetPlayerRacePreference(Player(12), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(12), true)
SetPlayerController(Player(12), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(13), 13)
SetPlayerColor(Player(13), ConvertPlayerColor(13))
SetPlayerRacePreference(Player(13), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(13), true)
SetPlayerController(Player(13), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(14), 14)
SetPlayerColor(Player(14), ConvertPlayerColor(14))
SetPlayerRacePreference(Player(14), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(14), true)
SetPlayerController(Player(14), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(15), 15)
SetPlayerColor(Player(15), ConvertPlayerColor(15))
SetPlayerRacePreference(Player(15), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(15), true)
SetPlayerController(Player(15), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(16), 16)
SetPlayerColor(Player(16), ConvertPlayerColor(16))
SetPlayerRacePreference(Player(16), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(16), true)
SetPlayerController(Player(16), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(17), 17)
SetPlayerColor(Player(17), ConvertPlayerColor(17))
SetPlayerRacePreference(Player(17), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(17), true)
SetPlayerController(Player(17), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(18), 18)
SetPlayerColor(Player(18), ConvertPlayerColor(18))
SetPlayerRacePreference(Player(18), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(18), true)
SetPlayerController(Player(18), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(19), 19)
SetPlayerColor(Player(19), ConvertPlayerColor(19))
SetPlayerRacePreference(Player(19), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(19), true)
SetPlayerController(Player(19), MAP_CONTROL_USER)
end

function InitCustomTeams()
SetPlayerTeam(Player(0), 0)
SetPlayerState(Player(0), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(1), 0)
SetPlayerState(Player(1), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(2), 0)
SetPlayerState(Player(2), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(3), 0)
SetPlayerState(Player(3), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(4), 0)
SetPlayerState(Player(4), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(5), 0)
SetPlayerState(Player(5), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(6), 0)
SetPlayerState(Player(6), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(7), 0)
SetPlayerState(Player(7), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(8), 0)
SetPlayerState(Player(8), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(9), 0)
SetPlayerState(Player(9), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(10), 0)
SetPlayerState(Player(10), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(11), 0)
SetPlayerState(Player(11), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(12), 0)
SetPlayerState(Player(12), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(13), 0)
SetPlayerState(Player(13), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(14), 0)
SetPlayerState(Player(14), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(15), 0)
SetPlayerState(Player(15), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(16), 0)
SetPlayerState(Player(16), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(17), 0)
SetPlayerState(Player(17), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(18), 0)
SetPlayerState(Player(18), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(19), 0)
SetPlayerState(Player(19), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerAllianceStateAllyBJ(Player(0), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(0), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(1), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(2), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(3), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(4), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(5), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(6), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(7), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(8), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(18), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(18), Player(19), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(0), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(1), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(2), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(3), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(4), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(5), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(6), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(7), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(8), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(19), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(0), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(1), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(2), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(3), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(4), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(5), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(6), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(7), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(8), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(18), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(18), Player(19), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(0), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(1), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(2), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(3), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(4), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(5), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(6), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(7), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(8), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(19), Player(18), true)
end

function InitAllyPriorities()
SetStartLocPrioCount(0, 15)
SetStartLocPrio(0, 0, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 1, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 2, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 3, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 5, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 6, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 7, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 8, 9, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 9, 10, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 10, 12, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 11, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 12, 14, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 13, 15, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 14, 17, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(1, 12)
SetStartLocPrio(1, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(1, 1, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(1, 2, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(1, 3, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(1, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(1, 5, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(1, 6, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(1, 7, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(1, 8, 9, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(1, 9, 10, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(1, 10, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(1, 11, 17, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(2, 14)
SetStartLocPrio(2, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(2, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(2, 2, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(2, 3, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(2, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(2, 5, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(2, 6, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(2, 7, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(2, 8, 9, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(2, 9, 10, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(2, 10, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(2, 11, 17, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(2, 12, 18, MAP_LOC_PRIO_LOW)
SetStartLocPrio(2, 13, 19, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(2, 2)
SetEnemyStartLocPrio(2, 0, 18, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(2, 1, 19, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(3, 13)
SetStartLocPrio(3, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 3, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 5, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 6, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 7, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 8, 9, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 9, 10, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 10, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 11, 16, MAP_LOC_PRIO_LOW)
SetStartLocPrio(3, 12, 17, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(4, 13)
SetStartLocPrio(4, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 3, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 5, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 6, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 7, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 8, 9, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 9, 10, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 10, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 11, 17, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 12, 19, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(4, 2)
SetEnemyStartLocPrio(4, 0, 18, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(4, 1, 19, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(5, 14)
SetStartLocPrio(5, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 3, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 4, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 5, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 6, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 7, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 8, 9, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 9, 10, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 10, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 11, 17, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 12, 18, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 13, 19, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(5, 2)
SetEnemyStartLocPrio(5, 0, 18, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(5, 1, 19, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(6, 13)
SetStartLocPrio(6, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(6, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(6, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(6, 3, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(6, 4, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(6, 5, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(6, 6, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(6, 7, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(6, 8, 9, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(6, 9, 10, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(6, 10, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(6, 11, 17, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(6, 12, 19, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(7, 12)
SetStartLocPrio(7, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 3, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 4, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 5, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 6, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 7, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 8, 9, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 9, 10, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 10, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 11, 17, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(7, 1)
SetEnemyStartLocPrio(7, 0, 18, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(8, 12)
SetStartLocPrio(8, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 3, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 4, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 5, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 6, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 7, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 8, 9, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 9, 10, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 10, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 11, 17, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(9, 12)
SetStartLocPrio(9, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(9, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(9, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(9, 3, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(9, 4, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(9, 5, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(9, 6, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(9, 7, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(9, 8, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(9, 9, 10, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(9, 10, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(9, 11, 17, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(10, 12)
SetStartLocPrio(10, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 3, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 4, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 5, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 6, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 7, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 8, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 9, 9, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 10, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 11, 17, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(11, 8)
SetStartLocPrio(11, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(11, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(11, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(11, 3, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrio(11, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(11, 5, 6, MAP_LOC_PRIO_LOW)
SetStartLocPrio(11, 6, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(11, 7, 9, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(11, 3)
SetEnemyStartLocPrio(11, 0, 13, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(11, 1, 14, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(11, 2, 15, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(12, 3)
SetStartLocPrio(12, 0, 14, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(12, 1, 15, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(12, 2, 16, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(13, 12)
SetStartLocPrio(13, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(13, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(13, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(13, 3, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(13, 4, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(13, 5, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(13, 6, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(13, 7, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(13, 8, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(13, 9, 9, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(13, 10, 10, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(13, 11, 17, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(14, 3)
SetStartLocPrio(14, 0, 12, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(14, 1, 15, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(14, 2, 16, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(15, 3)
SetStartLocPrio(15, 0, 12, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(15, 1, 14, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(15, 2, 16, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(15, 2)
SetEnemyStartLocPrio(15, 0, 18, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(15, 1, 19, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(16, 3)
SetStartLocPrio(16, 0, 12, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(16, 1, 14, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(16, 2, 15, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(17, 12)
SetStartLocPrio(17, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(17, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(17, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(17, 3, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(17, 4, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(17, 5, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(17, 6, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(17, 7, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(17, 8, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(17, 9, 9, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(17, 10, 10, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(17, 11, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(19, 14)
SetStartLocPrio(19, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(19, 1, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(19, 2, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(19, 3, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(19, 5, 7, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 6, 8, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 7, 9, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 8, 11, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 9, 12, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 10, 13, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 11, 14, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 12, 15, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 13, 17, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(19, 13)
SetEnemyStartLocPrio(19, 0, 0, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(19, 1, 2, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(19, 2, 3, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(19, 3, 5, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(19, 4, 7, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 5, 8, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 6, 9, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 7, 11, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 8, 12, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 9, 13, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 10, 14, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 11, 15, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 12, 17, MAP_LOC_PRIO_LOW)
end

function main()
SetCameraBounds(-3584.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -3584.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 3456.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -3584.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 3456.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -3584.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
SetDayNightModels("Environment\\DNC\\DNCDalaran\\DNCDalaranTerrain\\DNCDalaranTerrain.mdl", "Environment\\DNC\\DNCDalaran\\DNCDalaranUnit\\DNCDalaranUnit.mdl")
NewSoundEnvironment("Default")
SetAmbientDaySound("DalaranDay")
SetAmbientNightSound("DalaranNight")
SetMapMusic("Music", true, 0)
InitSounds()
CreateRegions()
CreateAllUnits()
InitBlizzard()
InitGlobals()
InitCustomTriggers()
end

function config()
SetMapName("TRIGSTR_001")
SetMapDescription("TRIGSTR_003")
SetPlayers(20)
SetTeams(20)
SetGamePlacement(MAP_PLACEMENT_TEAMS_TOGETHER)
DefineStartLocation(0, -3008.0, 2752.0)
DefineStartLocation(1, -3008.0, 2752.0)
DefineStartLocation(2, -3008.0, 2752.0)
DefineStartLocation(3, -3008.0, 2752.0)
DefineStartLocation(4, -3008.0, 2752.0)
DefineStartLocation(5, -3008.0, 2752.0)
DefineStartLocation(6, -3008.0, 2752.0)
DefineStartLocation(7, -3008.0, 2752.0)
DefineStartLocation(8, -3008.0, 2752.0)
DefineStartLocation(9, -3008.0, 2752.0)
DefineStartLocation(10, -3008.0, 2752.0)
DefineStartLocation(11, -3008.0, 2752.0)
DefineStartLocation(12, -3008.0, 2752.0)
DefineStartLocation(13, -3008.0, 2752.0)
DefineStartLocation(14, -3008.0, 2752.0)
DefineStartLocation(15, -3008.0, 2752.0)
DefineStartLocation(16, -3008.0, 2752.0)
DefineStartLocation(17, -3008.0, 2752.0)
DefineStartLocation(18, -3008.0, 2752.0)
DefineStartLocation(19, -3008.0, 2752.0)
InitCustomPlayerSlots()
InitCustomTeams()
InitAllyPriorities()
end

