import { Constants } from 'src/AutoGenerated/Constants'
import { Logger } from 'src/Events/Logger/Logger'
import { UnitWithinRange } from 'src/Events/WithinRange/UnitWithinRange'
import { Globals } from 'src/Global/Globals'
import { Utility } from 'src/Utility/Utility'
import { MapPlayer, Trigger, Unit } from 'w3ts'
import { CollisionDetection } from '../CollisionDetection'
import { RelicUtil } from '../Items/Relics/RelicUtil'
import { Kitty } from './Kitty/Kitty'

export class ShadowKitty {
    public static ALL_SHADOWKITTIES: Map<MapPlayer, ShadowKitty>
    public Unit: Unit

    public Player: MapPlayer

    public Kitty: Kitty

    public Active = false

    public wCollision: Trigger

    public cCollision: Trigger

    public ID = 0

    constructor(kitty: Kitty) {
        this.Kitty = kitty
        this.Player = kitty.Player
        this.ID = kitty.Player.id
        ShadowKitty.ALL_SHADOWKITTIES.set(this.Player, this)
        this.RegisterTriggers()
    }

    public static Initialize = () => {
        ShadowKitty.ALL_SHADOWKITTIES = new Map()
    }

    /// <summary>
    /// Summons shadow kitty to the position of this player's kitty object.
    /// </summary>
    public SummonShadowKitty = () => {
        const kitty = Globals.ALL_KITTIES.get(this.Player)!.Unit
        this.Unit = Unit.create(this.Player, Constants.UNIT_SHADOWKITTY_RELIC_SUMMON, kitty.x, kitty.y)!
        this.Unit.setVertexColor(0, 0, 0, 255)

        // Unit.addAbility(Constants.ABILITY_APPEAR_AT_SHADOWKITTY);
        this.Unit.addAbility(Constants.ABILITY_WIND_WALK)
        this.Unit.setAbilityLevel(Constants.ABILITY_WIND_WALK, 3)
        Utility.MakeUnitLocust(this.Unit)
        CollisionDetection.ShadowKittyRegisterCollision(this)
        this.Unit.moveSpeed = 522
        RelicUtil.CloseRelicBook(kitty)
        ShadowKitty.PauseKitty(this.Player, true)
        Utility.SelectUnitForPlayer(this.Player, this.Unit)
        this.Active = true
    }

    /// <summary>
    /// Teleports the player's kitty to the shadow kitty's position.
    /// </summary>
    public TeleportToShadowKitty = () => {
        const kitty = Globals.ALL_KITTIES.get(this.Player)!.Unit
        kitty.setPosition(this.Unit.x, this.Unit.y)
    }

    /// <summary>
    /// Kills this shadow kitty object, disposing and deregistering it from collision.
    /// </summary>
    public KillShadowKitty = () => {
        try {
            UnitWithinRange.DeRegisterUnitWithinRangeUnitShadow(this)
            KillUnit(this.Unit.handle)
            this.Unit.destroy()
            this.Active = false
            ShadowKitty.PauseKitty(this.Player, false)
        } catch (e: any) {
            Logger.Warning(`ShadowKitty.KillShadowKitty: ${e}`)
            throw e
        }
    }

    /// <summary>
    /// The game doesnt register the the abilities or movement, so a reselection is required.
    /// </summary>
    /// <param name="player"></param>
    public SelectReselectShadowKitty = () => {
        const kitty = Globals.ALL_KITTIES.get(this.Player)!.Unit
        Utility.SelectUnitForPlayer(this.Player, this.Unit)
    }

    private static PauseKitty(player: MapPlayer, paused: boolean) {
        const kitty = Globals.ALL_KITTIES.get(player)!.Unit
        kitty.paused = paused
    }

    private RegisterTriggers = () => {
        this.wCollision = Trigger.create()!
        this.cCollision = Trigger.create()!
    }
}
