import { Constants } from 'src/AutoGenerated/Constants'
import { Logger } from 'src/Events/Logger/Logger'
import { Wolf } from 'src/Game/Entities/Wolf'
import { AchesTimers } from 'src/Utility/MemoryHandler/AchesTimers'
import { MemoryHandler } from 'src/Utility/MemoryHandler/MemoryHandler'
import { Affix } from './Affix'
import { AffixFactory } from './AffixFactory'

export class Chaos extends Affix {
    private AFFIX_ABILITY: number = Constants.ABILITY_CHAOS
    private RotationTimer: AchesTimers = MemoryHandler.getEmptyObject<AchesTimers>()
    private currentAffix: Affix
    private rotationTime: number = GetRandomReal(25, 45)

    public constructor(unit: Wolf) {
        super(unit)
        this.name = '{Colors.COLOR_GREEN}Chaos|r'
    }

    public override Apply() {
        try {
            this.RegisterTimer()
            this.Unit.Unit.addAbility(this.AFFIX_ABILITY)
            super.Apply()
        } catch (e: any) {
            Logger.Warning('Chaos.Apply: {e.Message}')
            throw e
        }
    }

    public override Remove() {
        try {
            this.Unit.RemoveAffix(this.currentAffix)
            this.RotationTimer?.dispose()
            this.Unit?.Unit?.removeAbility(this.AFFIX_ABILITY)
            super.Remove()
        } catch (e: any) {
            Logger.Warning('Error in Chaos.Remove: {e.Message}')
            super.Remove()
        }
    }

    private RegisterTimer() {
        try {
            this.RotationTimer?.Timer.start(this.rotationTime, true, this.RotateAffix)
            let randomAffix: string = this.GenRandomAffixName()
            this.currentAffix = AffixFactory.CreateAffix(this.Unit, randomAffix)
            this.Unit.AddAffix(this.currentAffix)
        } catch (e: any) {
            Logger.Warning('Error in Chaos.RegisterTimer: {e.Message}')
            this.RotationTimer.dispose()
            this.Unit.RemoveAffix(this.currentAffix)
            this.currentAffix = null as never
        }
    }

    private RotateAffix() {
        try {
            if (this.currentAffix !== null) this.Unit.RemoveAffix(this.currentAffix) // look at later..
            this.currentAffix = null as never
            let randomAffix: string = this.GenRandomAffixName()
            this.currentAffix = AffixFactory.CreateAffix(this.Unit, randomAffix)
            this.Unit.AddAffix(this.currentAffix)
        } catch (e: any) {
            // Handle exceptions gracefully, log if necessary
            Logger.Warning('Error in Chaos.RotateAffix: {e.Message}')
            this.Unit.RemoveAffix(this.currentAffix)
        }
    }

    private GenRandomAffixName(): string {
        let randomAffixName: string =
            AffixFactory.AffixTypes.length > 0
                ? AffixFactory.AffixTypes[GetRandomInt(0, AffixFactory.AffixTypes.length - 1)]
                : 'Speedster'
        if (randomAffixName === 'Chaos') randomAffixName = 'Speedster'
        return randomAffixName
    }

    public override pause(pause: boolean) {
        this.RotationTimer.pause(pause)
        this.currentAffix.pause(pause)
    }
}
