import { Constants } from 'src/AutoGenerated/Constants'

class Howler extends Affix {
    private HOWL_RADIUS: number = 900.0
    private AFFIX_ABILITY: number = Constants.ABILITY_HOWLER
    private ROAR_EFFECT: string = 'Abilities\\Spells\\NightElf\\BattleRoar\\RoarCaster.mdl'
    private MIN_HOWL_TIME: number = 10.0
    private MAX_HOWL_TIME: number = 20.0
    private HowlTimer: AchesTimers
    private NearbyWolves: group = group.Create()

    public constructor(unit: Wolf) {
        super(unit)
        this.Name = '{Colors.COLOR_BLUE}Howler|r'
    }

    public override Apply() {
        this.RegisterTimerEvents()
        this.Unit.Unit.AddAbility(this.AFFIX_ABILITY)
        this.Unit.Unit.SetVertexColor(25, 25, 112)
        base.Apply()
    }

    public override Remove() {
        SetUnitVertexColor(this.Unit.Unit, 150, 120, 255, 255)
        this.Unit.Unit.RemoveAbility(this.AFFIX_ABILITY)
        this.HowlTimer?.Dispose()
        GC.RemoveGroup(this.NearbyWolves) // TODO; Cleanup:         GC.RemoveGroup(ref NearbyWolves);
        base.Remove()
    }

    public override Pause(pause: boolean) {
        this.HowlTimer.Pause(pause)
    }

    private RegisterTimerEvents() {
        this.HowlTimer = ObjectPool.GetEmptyObject<AchesTimers>()
        this.HowlTimer.Timer.Start(Howler.GetRandomHowlTime(), false, this.Howl)
    }

    private Howl() {
        try {
            this.HowlTimer.Timer.Start(Howler.GetRandomHowlTime(), false, this.Howl)
            if (this.Unit.IsPaused) return
            Utility.CreateEffectAndDispose(this.ROAR_EFFECT, this.Unit.Unit, 'origin')
            this.NearbyWolves.EnumUnitsInRange(
                this.Unit.Unit.X,
                this.Unit.GetUnitY(unit),
                this.HOWL_RADIUS,
                FilterList.DogFilter
            )
            while (true) {
                let wolf = this.NearbyWolves.First
                if (wolf == null) break
                this.NearbyWolves.Remove(wolf)
                if (NamedWolves.StanWolf != null && NamedWolves.StanWolf.Unit == wolf) continue
                if (wolf.IsPaused) continue
                if (!(wolfObject = Globals.ALL_WOLVES.TryGetValue(wolf)) /* TODO; Prepend: let */) continue
                if (wolfObject.RegionIndex != this.Unit.RegionIndex) continue
                wolfObject.StartWandering(true) // Start wandering
            }
            this.NearbyWolves.Clear()
        } catch (e: Error) {
            Logger.Warning('Error in Howl: {e.Message}')
            throw e
        }
    }

    private static GetRandomHowlTime(): number {
        return GetRandomReal(MIN_HOWL_TIME, MAX_HOWL_TIME)
    }
}
