import { Constants } from 'src/AutoGenerated/Constants'
import { Wolf } from 'src/Game/Entities/Wolf'
import { Affix } from './Affix'

export class Stealth extends Affix {
    private AFFIX_ABILITY: number = Constants.ABILITY_GHOSTAFFIX

    public constructor(unit: Wolf) {
        super(unit)
        this.name = '{Colors.COLOR_GREY}Stealth|r'
    }

    public override Apply() {
        this.Unit.Unit.addAbility(this.AFFIX_ABILITY)
        this.Unit.Unit.addAbility(this.AFFIX_ABILITY)
        super.Apply()
    }

    public override Remove() {
        this.Unit.Unit.removeAbility(this.AFFIX_ABILITY)
        super.Remove()
    }

    public override pause(pause: boolean) {
        // no logic needed atm
    }
}
