import { Constants } from 'src/AutoGenerated/Constants'
import { Wolf } from 'src/Game/Entities/Wolf'
import { DEFAULT_OVERHEAD_EFFECT } from 'src/Global/Globals'
import { Affix } from './Affix'

export class Unpredictable extends Affix {
    private AFFIX_ABILITY = Constants.ABILITY_UNPREDICTABLE
    private WANDER_ABILITY = FourCC('Awan')

    public constructor(unit: Wolf) {
        super(unit)
        this.name = 'Unpredictable'
    }

    public override Apply() {
        this.Unit.Unit.addAbility(this.WANDER_ABILITY) // Wander
        this.Unit.Unit.addAbility(this.AFFIX_ABILITY)
        this.Unit.OVERHEAD_EFFECT_PATH = ''
        super.Apply()
    }

    public override Remove() {
        this.Unit.Unit.removeAbility(this.WANDER_ABILITY) // Wander
        this.Unit.Unit.removeAbility(this.AFFIX_ABILITY)
        this.Unit.OVERHEAD_EFFECT_PATH = DEFAULT_OVERHEAD_EFFECT
        super.Remove()
    }

    public override pause(pause: boolean) {}
}
